### ISSUE TITLE
NVDA jpalpha_180820rでKCトーカーを読み込むとNVDAがクラッシュする

### ISSUE THREAD

**Issue by riku22** [nvdajp/nvdajp#101]
どこに報告すればよいかわからなかったのですが、一応こちらに報告させていただきます。

### 問題の再現手順

1. 「音声エンジンの選択」でKCトーカーを選択。
1. 設定を保存後、NVDAを再起動する。

### 期待されること

　正常に音声エンジンが読み込まれ、画面内容等を読み上げる。

### 実際に起きること

　「NVDAを読み込み中です。しばらくお待ちください。」という音声は流れるものの、読み込み中にエラー音が鳴り、NVDAがクラッシュしてしまう。  
　なお、「音声エンジンの選択」で音声エンジンを切り替えたときは、クラッシュしないようです。

### システム構成

- NVDA 日本語版 jpalpha_180820r インストール環境
- Windows 10 バージョン 1803 64ビット 日本語環境

### その他の質問

PC を再起動してもこの問題は再発する：はい
NVDA 日本語版 2018.1jp でも再現する：いいえ

### ログ内容
　NVDA起動時、ログに下記のエラーが記録されていました。

INFO - synthDriverHandler.setSynth (00:06:47.542):
Loaded synthDriver kctalker
CRITICAL - __main__ (00:06:47.739):
core failure
Traceback (most recent call last):
  File "nvda.pyw", line 214, in \<module\>
  File "core.pyo", line 245, in main
  File "speech.pyo", line 128, in speakMessage
  File "speech.pyo", line 549, in speakText
  File "speech.pyo", line 684, in speak
  File "addon\synthDrivers\kctalker\\_\_init\_\_.py", line 442, in speak
  File "wx\core.pyo", line 1940, in YieldIfNeeded
AttributeError: 'NoneType' object has no attribute 'Yield'

**Comment by nishimotz** [comment]
テンプレートの不備と思いますが 2018.2.1jp でも再現しますか？
それから KC トーカーのバージョンは確認可能ですか？
私がいま KC トーカー 1.0.4 と jpalpha_180820r で確認しましたが、特に問題はなく、
ご指摘のエラーをまだ再現できていません。

**Comment by riku22** [comment]
2018.2.1では発生しなかったように思います。  
　KCトーカーのバージョンは1.04です。  
　環境固有の問題ですかね。

**Comment by nishimotz** [comment]
さしつかえなければ起動直後からエラー発生までの
タイミングがわかるログをください。
「NVDAを読み込み中です。しばらくお待ちください。」
が聞こえたということはけっこう起動に時間がかかったわけですよね。。

**Comment by riku22** [comment]
ログ内容を下記に記します。  
INFO - \_\_main\_\_ (00:06:43.674):
Starting NVDA
INFO - core.main (00:06:44.013):
Config dir: C:\Users\user\AppData\Roaming\nvda
INFO - config.ConfigManager.\_loadConfig (00:06:44.013):
Loading config: C:\Users\user\AppData\Roaming\nvda\nvda.ini
INFO - core.main (00:06:44.279):
NVDA version jpalpha\_180820r
INFO - core.main (00:06:44.279):
Using Windows version 10.0.17134 workstation
INFO - core.main (00:06:44.279):
Using Python version 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]
INFO - core.main (00:06:44.279):
Using comtypes version 1.1.3
INFO - core.main (00:06:44.279):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - synthDriverHandler.setSynth (00:06:47.542):
Loaded synthDriver kctalker
CRITICAL - \_\_main\_\_ (00:06:47.739):
core failure
Traceback (most recent call last):
  File "nvda.pyw", line 214, in \<module\>
  File "core.pyo", line 245, in main
  File "speech.pyo", line 128, in speakMessage
  File "speech.pyo", line 549, in speakText
  File "speech.pyo", line 684, in speak
  File "addon\synthDrivers\kctalker\\_\_init\_\_.py", line 442, in speak
  File "wx\core.pyo", line 1940, in YieldIfNeeded
AttributeError: 'NoneType' object has no attribute 'Yield'

**Comment by nishimotz** [comment]
ありがとうございます。
そのエラーの前に
```
INFO - core.main (13:52:29.246):
Using wx version 4.0.3 msw (phoenix) wxWidgets 3.0.5
```
みたいなメッセージがないですね。
ということは wx の初期化が間に合っていない可能性があります。

相談があればKCトーカー側の対策はお手伝いできると思います。
購入された販売店や発売元に相談していただけると助かります。

**Comment by riku22** [comment]
私は、KCトーカーを直接ナレッジクリエーションから購入したので、先ほどナレッジクリエーションのほうにメールを送信しておきました。  
　とりあえず、ご報告まで。

**Comment by nishimotz** [comment]
KCトーカー 1.1 で修正されたと思います。
