### ISSUE TITLE
Excelで条件付き書式ルールの編集画面でカーソル位置が読み上げられない

### ISSUE THREAD

**Issue by dream945** [nvdajp/nvdajp#104]
下記の操作で編集画面のカーソル位置が読み上げられないようです。

1. Alt H 「ホーム」  L 「条件付き書式」を開きます。

2. タブキーで、「ルールの管理」まで移動して、エンターキーを押します。

3. タブキーで、「新規ルール」まで移動して、エンターキーを押します。

4. 下矢印キーで「数式を使用して書式設定セル決定」を選択します。

5. タブキーを1会押します。

6. F2キーを押して編集状態にします。

7. =COUNTIF(D6,"U*") などと入力します。

8. 左右矢印キーを押します。
　冒頭の「イコール」しか読まず、カーソル位置の確認ができません。

**Comment by nishimotz** [comment]
ご報告ありがとうございます。

ご指摘の状況は「新しい書式ルール」にフォーカスがあるけれど、
矢印キーで実際に移動しているのはシートの上のセルを表す点線の枠ですね。
（数式は =COUNTIF(D6+"U*")+$B$1 のようになります）

NVDA+矢印キーで1文字単位でエディットの数式が確認できるので、
それで確認していただく、というのが回避策と思います。

本家版と英語環境で確認して本家に報告すればいいのですが、
ナレーターでも正しく読み上げできないので、
マイクロソフトに報告するほうがよいのかも知れません。

ちなみにナレーターで同じことをすると、
セル A1 にフォーカスが移動して、
矢印キーでフォーカスそのものが動かないため、
やはり読み上げない、という状況でした。

**Comment by dream945** [comment]
ご返信ありがとうございます。
確かにナレーターでも読まないようですね。
しかしPC-Talkerでは読んでいます。
またWindows7ですが、FocusTalkでも読むようです。

**Comment by dream945** [comment]
NVDA+矢印キーを押すと、画面ではカーソルが動いているようですが読み上げがされないようです。

また、マクロでユーザーフォームにテキストボックスを挿入しても、テキストボックスの中はどの矢印キーを押しても読まないとの報告が来ています。

**Comment by dream945** [comment]
Excelで、F5キーを押して、セル番地を直接入力してジャンプできますが、このダイアログも行頭の文字しかよまず、カーソル位置の確認ができません。
他のダイアログについても同じではないかと思われます。
改善していただけると助かります。

**Comment by TetsuroOkane** [comment]
先日NVDAとMicroSoft Officeを使用した講習を行いましたが、半分近くの参加者の間でこのチケットに近い不具合が確認されました。

条件付き書式の他で発生した部分です。
•関数の引数ダイアログ
•シート名の編集
シート名の編集は別チケットで昨年報告したF2キーを押しても読まず、カーソルでの確認も出来ず、セルを直接編集するのチェックを外すと数式バーでは編集可能な状態のExcel(Office 365/2016)では、完全に無音で点字ディスプレイにも表示されない状態になりました。
Windows10であれば、NVDA+Rで文字認識で確認出来ますが、現状では確認操作に時間が掛かり、業務用としてExcelを使用する際には業務スピード低下に繋がっており、問題無く読み上げているJAWS、PC-Talker、FocusTalk等での使用が必須になると思われますが、早急な対応は望めない状態でしょうか？

**Comment by nishimotz** [comment]
本家プルリクエスト 9290 がこの問題を解決しそうなのでコメントしました。

**Comment by nishimotz** [comment]
nvda_jpalpha_190220i に本家 9290 の作業がマージされています。
本件の最初の報告、キャレットの文字は報告されるようになりましたが、
ちょっとレスポンスが悪い気がするので、もうすこし調べてみます。

**Comment by TetsuroOkane** [comment]
Version: nvda_jpalpha_190221qで条件付き書式・関数の引数・シート名の変更・ジャンプダイアログ等でタブキーまたはシフト+タブキーで入力済みの項目をに移動した時、「書式コロンエディットブランク」のように読まれ、左右矢印で移動しない限り、内容が確認出来ないようです。
レスポンスも1秒から3秒ほど掛かるように感じます。

**Comment by nishimotz** [comment]
@TetsuroOkane 
最初に報告された件と関係があるのか判断できないのですが、
なにか一つの現象に絞って再現手順を書いていただけますか？

**Comment by TetsuroOkane** [comment]
基本的には条件付き書式含め、ダイアログ形式で出て来る部分であれば再現可能です。

条件付き書式は既にこのチケットの先頭に再現手順があるので、ジャンプダイアログと関数の引数での再現手順を追記します。

ジャンプダイアログについての不具合内容もdream945さんが記載されております、 
「Excelで、F5キーを押して、セル番地を直接入力してジャンプできますが、このダイアログも行頭の文字しかよまず、カーソル位置の確認ができません。」と共通で詳細な再現手順となります。

ジャンプ機能の場合
1.Excelを起動し、ジャンプ機能を使いたいブックを開きます。
2.F5を押し、ジャンプダイアログを表示します。
3.ジャンプしたいセル番地を入力します。
4.タブキーで「移動先」「セル選択」「OK」「キャンセル」「参照先」と一巡して来ます。
5.参照先の読み上げを聴きます。
2018.4.1jpでは入力されている内容は読まれますが、jpalpha_190221qではブランクと読まれます。
6.左右矢印で「参照先」エディットフィールドの内容を確認します。
2018.4.1jpでは1文字目しか読まれず、jpalpha_190221qでは左右矢印での内容確認は出来ます。

関数の引数ダイアログの場合
1.Excelを起動し、関数を入力したいセルを選択します。
2.数式タブの関数ライブラリからIFやAVERAGE等を選び関数の引数ダイアログを表示します。(関数の種類は問わず再現します。)
3.1つ目のエディットフィールドに引数や数式を入力します。
4.タブキーで次のエディットフィールドに移り引数や数式を入力します。
5.シフト+タブキーで前のエディットフィールドに戻ります。。
2018.4.1jpでは入力されている内容は読まれますが、jpalpha_190221qではブランクと読まれます。
6.左右矢印でエディットフィールドの内容を確認します。
2018.4.1jpでは1文字目しか読まれず、jpalpha_190221qでは左右矢印での内容確認は出来ます。

期待される事
全てのダイアログや文字列の編集で、エディットフィールドにフォーカスした時に既に入力されている内容がある場合、その内容が読み上げられ、左右矢印で1文字ずつ確認や訂正も出来る

以上よろしくお願いいたします。

**Comment by nishimotz** [comment]
最初に報告された条件付き書式の問題は、最新の日本語アルファ版で解決したと私は判断していますが、いかがでしょうか。

**Comment by dream945** [comment]
最新の日本語アルファ版で解決しているのを確認しました。
ありがとうございました。

**Comment by nishimotz** [comment]
お手数ですが、別の問題は新しいチケットで議論させてください。
