### ISSUE TITLE
Windows XP/Vista 日本語環境でメッセージが表示されない

### ISSUE THREAD

**Issue by NVDAHelpDesk** [nvdajp/nvdajp#106]
### 問題の再現手順
1. インストールされたNVDAを起動する。

### 期待されること
NVDAが起動する。

### 実際に起きること
エラーが出てNVDAが起動しない。エラーメッセージはSee the logfile 'C:\Program Files (x86)\NVDA\nvda.exe.log' for detailsです。
ログは下記のようなものです。
Traceback (most recent call last):
  File "nvda.pyw", line 77, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8e in position 0: 

ordinal not in range(128)
Traceback (most recent call last):
  File "nvda.pyw", line 77, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8e in position 0: 

ordinal not in range(128)
Traceback (most recent call last):
  File "nvda.pyw", line 77, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8e in position 0: 

ordinal not in range(128)
Traceback (most recent call last):
  File "nvda.pyw", line 77, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8e in position 0: 

ordinal not in range(128)
Traceback (most recent call last):
  File "nvda.pyw", line 77, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8e in position 0: 

ordinal not in range(128)
Traceback (most recent call last):
  File "nvda.pyw", line 77, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8e in position 0: 

ordinal not in range(128)
Traceback (most recent call last):
  File "nvda.pyw", line 77, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8e in position 0: 

ordinal not in range(128)
Traceback (most recent call last):
  File "nvda.pyw", line 77, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8e in position 0: 

ordinal not in range(128)
Traceback (most recent call last):
  File "nvda.pyw", line 77, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8e in position 0: 

ordinal not in range(128)

### システム構成
ASUS X551CA
Windows8.1
64bit
NVDA2018.2.1jp

### その他の質問

PC を再起動してもこの問題は再発する
はい

NVDA 日本語版 2018.1jp でも再現する
インストーラーがないため再現チェックしていません。

**Comment by nishimotz** [comment]
この nvda.pyw line 77 は Windows XP / Vista の場合に実行される処理で、
このエラーが出ているなら、直後に exit するので NVDA は起動しないはずです。

問題はなぜ Windows 8.1 でこの処理が走ってしまうか、なのですが、
インストールが成功したあとで互換性のトラブルシューティングでなにか設定するなど、
特別なことをしていないでしょうか？

Windows XP / Vista でこのエラーが正常に出るかどうか、念のために確認してみます。

**Comment by nishimotz** [comment]
Windows Vista 32ビット 日本語環境で nvda_2018.2.1jp.exe を実行すると、
ご報告いただいたエラーが出ることを確認しました。
本来は
「指定されたプログラムは、新しいバージョンの Windows を必要とします。」
みたいなメッセージが表示されるはずです。

**Comment by nishimotz** [comment]
Python コンソールで下記を実行すれば正常にメッセージボックスが出ることを確認。

```
>>> import winUser
>>> import ctypes
>>> s = ctypes.FormatError(winUser.ERROR_OLD_WIN_VERSION)
>>> s = unicode(s.decode('mbcs'))
>>> winUser.MessageBox(0, s, None, winUser.MB_ICONERROR)
```

s.decode('mbcs') しないと下記のエラー：

```
>>> unicode(s)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8e in position 0: ordinal not in range(128)
```

**Comment by NVDAHelpDesk** [comment]
検証ありがとうございます。
NVDAが起動するようになりました。

元々、NVDAをWindows XPの互換モードで使用していました。起動に時間がかかる、NVDAを使用中の動作も遅いなどの不都合がありました。
9月10日今週月曜日に最後に起動しようとして、うまく起動しなくなり、急いでいたのでその時はシャットダウンしてSkype用に別デバイスを使いました。昨日、チケットの最初に書いたような現象になりました。
起動するまでの手順です。まずは、ナレーター等を使い、Program Filesのnvda.exeのプロパティを開き、互換性のタブで互換モードで実行のチェックを入れ、Windows7にして、パソコンの再起動をしましたが、再び同じエラーメッセージが出ました。
再びプロパティを開き、互換モードのチェックを外したら、起動するようになりました。起動に時間がかからなくなり、使用中の動作も非常に速くなり助かりました。
ありがとうございました。

**Comment by nishimotz** [comment]
起動するようになってよかったです。
UnicodeDecodeError を解決するまでこのチケットはオープンにしておきます。

**Comment by NVDAHelpDesk** [comment]
NVDAが起動するまでの手順の記載に一部間違いがありましたので訂正いたします。

誤）元々、NVDAをWindows XPの互換モードで使用していました。
正）元々、NVDAを互換モードで使用しているわけではありませんでした。

互換性の話を聞き、以下の操作をして、起動するようになりました。

1. NVDAの互換モードをWindows7にして再起動。NVDA起動せず。
2. NVDAの互換モードを外して再起動。NVDA起動しました。

NVDAを互換モードとして使用しているわけではなかったのに、互換モードで動作しているかのようなエラーになりました。

関連するかはわかりませんが、ブレイルメモBM24のドライバーをXPの互換モードにしています。点字設定を自動認識するようにNVDAがアップデートされた中で、NVDAも一緒に互換モード扱いになってしまうのでしょうか。上記1,2の操作を今回するまでは、BM24が自動でつながっていましたが（スリープからの復帰は自動ではありませんでしたが）、上記操作後は手動でしかつながらなくなりました。

**Comment by nishimotz** [comment]
2018.3jp で下記のように期待された画面が出るようにします。
もうすこし検証してからリリースします。
本家へのプルリクエストは 2018.4 に向けて行います。

![image](https://user-images.githubusercontent.com/76300/45722199-44721700-bbe6-11e8-99be-78b5e64351f5.png)

**Comment by nishimotz** [comment]
Python 2 と 3 両方で動くコードにしようと思ったら
```
s = s.decode('mbcs') if hasattr(s, 'decode') else s
```
みたいな書き方になりそう。。
