### ISSUE TITLE
NVDA jpalpha_180925vでFirefoxの読み上げが無音になる

### ISSUE THREAD

**Issue by riku22** [nvdajp/nvdajp#108]
### 問題の再現手順

1. デスクトップやスタートメニュー等からFirefoxを起動する。
2. Tabキー等で画面内の項目を移動する。  
　☆ Firefoxにフォーカスされていない場合は、フォーカスする。

### 期待されること

　Firefoxの画面内の項目を読み上げる。

### 実際に起きること

　Firefoxの画面内の項目が読み上げられず、Alt+Tabキーでアプリを切り替えたりしてもまったくしゃべらなくなる。

### システム構成

- NVDA 日本語版 jpalpha_180925v インストール環境
- Windows 10 バージョン 1803 64ビット 日本語環境
- Firefox 62.0.2 64ビット版

### その他の質問

- PC を再起動してもこの問題は再発する：はい
- NVDA 日本語版 2018.1jp でも再現する：いいえ

### その他

- アドオンを無効化して、再起動：効果なし
- Windowsを再起動した後、NVDAを上書きインストール：効果なし
- jpalpha_180920kでは再現しません。

**Comment by nishimotz** [comment]
同じシステム構成で確認しましたが、再現できていません。

NVDA 「ツール」「COM登録の修復」はなにか効果がありそうでしょうか？

**Comment by NVDAHelpDesk** [comment]
NVDAヘルプデスク　野々垣です。
私も再現出来ていません。
NVDAがポータブル環境なのが、問題が報告されている環境と違うところではあります。

NVDA 日本語版 jpalpha_180925v ポータブル環境
Windows 10 バージョン 1803 64ビット 日本語環境
Firefox 62.0.2 64ビット版

**Comment by riku22** [comment]
お世話になります。

　いろいろ試していましたが、どうも設定プロファイルを利用しているのが原因のようでした。  
　設定プロファイルを削除したら、正常に読み上げが可能になりました。  
　とりあえず、しばらくはこれで利用してみます。

**Comment by nishimotz** [comment]
報告ありがとうございます。
設定プロファイル関連で本家のバグ修正を反映したので、
次の日本語アルファ版で状況が変わるかも知れません。

**Comment by riku22** [comment]
お世話になります、

　NVDA jpalpha_180926qに更新したところ、正常に読み上げるようになりました。
　ありがとうございました。
