### ISSUE TITLE
Excel:テーブルの行列の見出しが点字ディスプレイに報告されない

### ISSUE THREAD

**Issue by dream945** [nvdajp/nvdajp#109]
NVDA 2018.3-JPにおいて、エクセルなどの行列の見出しが点字ディスプレイに報告されなくなりました。

### 問題の再現手順

1. NVDA+Shift+C NVDA+Shift+R を使って、行列の見出しを設定します。
2. 上下矢印キーでセル内を移動します。
3. 音声では見出しを読み上げていますが、点字ディスプレイには通知されません。

### 期待されること

見出しが点字ディスプレイに表示される。
以前のバージョンでは報告されていました。
どのバージョンから報告されなくなったのかは確認できていません。

**Comment by nishimotz** [comment]
nvdajp-team 8136 でもご報告いただきました。
確認中です。

日本語版 2014.3jp の独自作業
Excel の見出し自動通知が点字ディスプレイ出力で有効にならない
https://ja.osdn.net/projects/nvdajp/ticket/30308

**Comment by nishimotz** [comment]
下記の日本語アルファ版で修正を行っています。
http://s.nvda.jp/nvda_jpalpha_180928m.exe
同じ修正をした 2018.4jp-beta を作業中です。

**Comment by nishimotz** [comment]
2018.4jp ベータ版を公開しました。
http://s.nvda.jp/nvda_2018.4jp-beta-180928s.exe

**Comment by dream945** [comment]
早速ご対応いただきありがとうございます。
こちらでも見出しが点字ディスプレイに報告されるようになりました。
