### ISSUE TITLE
「書式とドキュメント情報」の「テーブル」の設定に関して

### ISSUE THREAD

**Issue by riku22** [nvdajp/nvdajp#111]
表題のとおり、書式とドキュメント情報の設定ダイアログで「テーブル」にチェックを付けた際の挙動について、個人的な要望を書かせていただきます。

#### 現状の動作

　この設定をオンにすると、ブラウザでホームページを閲覧中にテーブルを見つけた場合、「テーブル  X行Y列のテーブル」のようにテーブルがある旨と、テーブルの行や列の数を報告します。
　また、上下矢印で移動した場合、行や列の番号が報告されます。
　これがオフの場合、これらの報告は行われませんが、Excelでの行や列の見出しの自動読み上げが行われなくなります。

#### 要望
　この設定項目のオン・オフで、Excelでの行や列の見出しの自動読み上げが行われなくなることは、ユーザーガイド「10.2.1. 行や列の見出しの自動読み上げ」には書かれていません。
　そのため、ユーザーガイドに

書式とドキュメント情報の「テーブル」にチェックをつける必要があります。

という記述を追加するか、この設定のオン・オフにかかわらず、行や列の見出しの自動読み上げが動作するようにしていただけたらと思います。
　また、テーブル内で上下矢印を押したときの行や列の番号の報告は、「セル番地の報告」に統合してはいかがでしょうか。
　もちろん、これらの要望は本家NVDAプロジェクトとも相談しなければならないと思いますが、1つの要望として検討していただけると幸いです。

**Comment by nishimotz** [comment]
まずは以下のような課題だと整理してよいでしょうか。

セットアップ

* NVDA 本家版 2018.3.2 および日本語版 2018.3.2jp （いま確認しました）
* 書式とドキュメント情報「テーブル情報」
  * テーブル：チェックなし
  * 行と列の見出し：チェック
  * セル番地：チェックなし

(1) Firefox 62.0.2 でウェブを閲覧した場合

例えば NVDA コマンド一覧表
http://www.nvda.jp/nvda2018.3.2jp/ja/keyCommands.html

* 1文字ナビゲーション t で最初のテーブルに移動し、Ctrl+Alt+矢印キーでセルを移動する
* 例えば2行目でセルの内容と「デスクトップ用キー」「ラップトップ用キー」などの見出しを読み上げる

(2) Excel (Office 365) の場合

行と列の見出しを NVDA+Shift+C / NVDA+Shift+R で設定したシートを作る

* セルを移動してもセルの内容だけで、見出しを読み上げない
* 書式とドキュメント情報「テーブル情報」テーブルをチェックにすれば見出しを読み上げる

この挙動は一貫性がない。
Excel においても「テーブル」がチェックなしで「行と列の見出し」がチェックの場合に見出しを読み上げるべきである。

**Comment by riku22** [comment]
簡潔にまとめていただいて、ありがとうございます。
　要するにそういうことです。

　ユーザーガイドには、

> この機能を使うためには、まずNVDA設定ダイアログ → 書式とドキュメント情報カテゴリで「テーブルの行列見出しの報告」にチェックをします。

とあるのに、ここにチェックを下だけでは動いていないので、不思議に思った次第です。

**Comment by nishimotz** [comment]
コードを読んでいると、もしかすると Excel の仕様が意図された仕様で、Firefox の実装のほうが意図されてない仕様なのかもしれない、という気がしてきたので、もうすこしよく調べます。

ユーザーガイドを下記のように修正して、これをこのチケットのとりあえずの作業とします。

この機能を使うためには、まず[NVDA設定ダイアログ #NVDASettings] → 書式とドキュメント情報カテゴリ「テーブル情報」で「テーブル」および「行と列の見出し」にチェックをします。

**Comment by nishimotz** [comment]
当初のご要望通りの対応ではないのですが、ユーザーガイドを更新したので、
いったんクローズとさせてください。
