### ISSUE TITLE
SAPI5 DTalker 音声利用時の読み上げ

### ISSUE THREAD

**Issue by mitsugusakamoto** [nvdajp/nvdajp#115]
### 問題の再現手順

1. SAPI5音声を選んで、dtalkerの声で読み上げるように設定する。
2. 記号の読み上げレベルを「ほとんど読み上げ」にする。 		
3. notepad起動
4. 以下のように入力する。
(abc)
5. 行読みさせる。

### 期待されること

カッコエービーシーカッコトジ
と読み上げる。

### 実際に起きること

カッコカッコエービーシーカッコトジ
と読み上げる

### システム構成

Windows 10 バージョン 1709 日本語環境
Windows7 (ビルド 7601: Service Pack 1)日本語環境
NonVisual Desktop Access (NVDA)
Version: 2018.2jp-beta-180529l
### その他の質問

NVDA 日本語版 2018.1jp では再現しない。

ワークアラウンドとして、読み上げ辞書で音声エンジンに記号を送らないようにすると解決する。

**Comment by nishimotz** [comment]
SAPI5 DTalker 環境を作り直したので確認しましたが、解決しているはずです。
