### ISSUE TITLE
JTalk "–"（エンダッシュ）の二重読み上げ

### ISSUE THREAD

**Issue by msuzu15** [nvdajp/nvdajp#118]
Wordで"a - b"（a、スペース、ハイフン、スペース、bと入力）と入力してEnterキーを押すと、"-"（ハイフン）が"–"（エンダッシュ）に変換されます。
この状態で、以下の操作をすると、それぞれ以下のような読み上げがされます。

1. 上矢印キーを押してカーソルを"a – b"の行に移動させると、「aエンダッシュエンダッシュb」と"–"（エンダッシュ）が二重読み上げされます。
2. 左右矢印キーを使ってカーソルを"–"（エンダッシュ）の左に移動させると、「エンダッシュ」とだけ読み上げされます（二重読み上げはされない）。

二重読み上げされると入力を間違えたと思って紛らわしいので、二重読み上げされないようにしてほしいです。

**Comment by nishimotz** [comment]
時間がたってしまって申し訳ありませんでした。

文字説明の実装の見直しの一環でこちらを検証しました。

* NVDA 2024.1jp-beta-240327l で JTalk を使用
* Windows 11 Pro
* Microsoft 365 Word バージョン 2402

オートコレクト → 入力オートフォーマット

* ハイフンをダッシュに変更する：チェック

この状況で再現をこころみましたが、二重読み上げしませんでした。

クローズしますが、音声エンジンに依存しない現象の可能性もあるので、別の再現手順があればまたご報告いただけるとありがたいです。

**Comment by msuzu15** [comment]
ありがとうございます。
この現象は、NVDA 2023.1jpまでで発生していて、NVDA 2023.2jp-r2以降ではなくなっているようです。
