### ISSUE TITLE
CHMファイル内のドキュメントを閲覧するとhh.exeが強制終了する

### ISSUE THREAD

**Issue by riku22** [nvdajp/nvdajp#121]
### 問題の再現手順

1. 何らかのヘルプファイル（拡張子が「CHM」のもの）を開く。
1. 目次から閲覧したいコンテンツを選択し、Enterキーを押す。
1. 表示されたドキュメントを閲覧するために、F6キーを押す。

### 期待されること

　ドキュメント部分にフォーカスが移り、ブラウズモードでページ内の読み上げが可能。

### 実際に起きること

　NVDAのログに下記のエラーが記録され、ヘルプファイル閲覧用のアプリケーション「hh.exe」が強制終了する。

    Traceback (most recent call last):
      File "virtualBuffers\__init__.pyo", line 439, in _loadBuffer
    WindowsError: [Error 1726] リモート プロシージャ コールに失敗しました。

### システム構成

- NVDA 日本語版 jpalpha_181102x インストール環境
- Windows 10 バージョン 1809 64ビット 日本語環境

### その他の質問

- PC を再起動してもこの問題は再発する：はい
- NVDA 日本語版 2018.1jp でも再現する：いいえ

### 備考
　下記OSとNVDA日本語版のバージョンでの組み合わせでは発生しないことを確認済みです。

- Windows7 32ビット、jpalpha_181102x インストール環境
- Windows10 1809 64ビット、jpalpha_181029o インストール環境

**Comment by nishimotz** [comment]
Python のヘルプファイル (python371.chm) でご指摘の状況が再現できました。
こちらは Windows 10 バージョン 1803 です。
jpalpha_181029o では起きていなくて、それ以降に起きたリグレッションの可能性が高いですね。
本家版の変更を確認してみます。

**Comment by riku22** [comment]
jpalpha_181110vで、改善していることを確認しました。

　ありがとうございました。
