### ISSUE TITLE
eSpeak NG の Japanese 音声で日本語文がアルファベットのスペル読みになってしまう

### ISSUE THREAD

**Issue by NVDAHelpDesk** [nvdajp/nvdajp#128]
### 問題の再現手順

1. NVDAメニューの設定、設定、音声、音声エンジンの「変更する」から、音声エンジンをeSpeakNGにする。
2. 音声エンジンの次の項目「音声」はJapaneseにする。
3. 日本語部分（例えば「音声」という言葉）が、onseiとアルファベットのスペル読みで読み上げられる。

サポートされている場合自動的に言語を切り替える
サポートされている場合自動的に方言を切り替える
サポートされている場合スペル読み機能を使用
などのチェックの有無には関係なく、日本語の文字がアルファベットのスペル読みになってしまうようです。

### 期待されること

日本語で、音声ならおんせいと読み上げられる
音声の設定が日本語以外だと、たどたどしい感じの日本語で「おんせい」と読まれる。

### 実際に起きること

音声が「オーエヌエスエーアイ」と読み上げられる。

### システム構成
NVDA 日本語版 2018.4jp インストール環境
Windows 10 バージョン 1803 日本語環境

### その他の質問
PC を再起動してもこの問題は再発します。
他のバージョンでの動作はわかりません。

**Comment by nishimotz** [comment]
NVDA 2018.4 本家版にも eSpeak NG の Japanese 音声があります。
カタカナとひらがなは読めますが、漢字は Chinese Letter としか読まないので、
実用的な日本語音声エンジンではありません。

NVDA日本語版には English 音声での簡易的な日本語読み上げ機能がありますが、
過去の eSpeak には Japanese 音声がなかったので、
Japanese での動作を想定していません。

「日本語版の説明」にはこのことが書かれているべきだとは思います。
（Japanese 音声が選べることに気づいていませんでした）

あるいは eSpeak NG の Japanese は選択肢として不適切なので削除するように、 
NVDA 本家版に提案するべきかも知れません。

eSpeak で日本語を読めるようにした当時は、
選択中の音声エンジンがエラーになると必ず eSpeak が選ばれていたため、
NVDA がまったく操作できない、という状況を回避する必要がありました。
現在の NVDA ではそのようなトラブルは起こりにくくなっています。

eSpeak に日本語をしゃべらせるニーズや、
ご報告いただいた状況によって起こりうるトラブルなど、
なにか補足していただけることがあるでしょうか。

**Comment by nishimotz** [comment]
2019.1jp で以下のように修正しました。

* eSpeak NG に Japanese という選択肢は表示されない
* 言語の自動切り替えをチェックしても内部的に Japanese 音声は選択されない
