### ISSUE TITLE
日本語入力の読み上げが右Ctrlキーに未対応

### ISSUE THREAD

**Issue by NVDAHelpDesk** [nvdajp/nvdajp#129]
### 問題の再現手順
1. メモ帳を開く
2. 日本語変換オンでabcdefgと入力する
3. F9,F10,Ctrl+Tのいずれかで、アルファベットに変換する
4. abcdefgと関係なさそうなアルファベットが読み上げられる

### 期待されること
abcdefgがエービーシーディーイーエフジーと読み上げられる

### 実際に起きること
abcdefgと関係なさそうなアルファベットが読み上げられる。

### システム構成
NVDA 日本語版 2018.4jp インストール環境
Windows 10 バージョン 1803 日本語環境

### その他の質問
PC を再起動してもこの問題は再発します。

**Comment by nishimotz** [comment]
再現できないので、もうすこし詳しく手順を教えてください。

私が試している環境を書いておきます。

* Windows 10 version 1803 64bit
* Microsoft IME でローマ字入力
* IMEのキー割り当て: F9 は全角英数、F10 と Ctrl+T は半角英数
* 音声: Windows OneCore

実際に起きることは、以下のような感じです。

* a を押すと表示「あ」読み上げ「ア」
* b を押すと表示「あｂ」読み上げ「ビー」
* c を押すと表示「あｂｃ」読み上げ「シー」

**Comment by nishimotz** [comment]
途中で書き込んでしまったので続きです。

* Ctrl+T を押すと表示「abc」読み上げ「半角 英字 エービーシー」
* Enter を押すと確定された表示「abc」読み上げ「エービーシー」

**Comment by NVDAHelpDesk** [comment]
音声エンジン、音声の設定項目の記載が抜けていました。
すみませんでした。
音声エンジン eSpeak NG
音声 Japanese
です。
これも、eSpeakの日本語利用が想定されていない、に関連するのかもしれないですね。

**Comment by NVDAHelpDesk** [comment]
岡根です。
この事について検証しました。

問題の再現手順

    メモ帳を開く
    日本語変換オンでabcと入力する
    右Ctrl+Tで、アルファベットに変換する
   アブク、エービーシー、アブクと読まれる

期待されること

左Ctrl+Tと同じように、「半角英字エービーシー」、「半角英字大文字エービーシー」、「半角英字大文字エー、半角英字ビーシー」と読み上げられる
実際に起きること

左Ctrl+Tでは正常にアルファベット変換が読み上げられるが、右Ctrl+Tでは正常に読み上げされない。
システム構成

NVDA 日本語版 2018.4jp インストール環境
Windows 10 バージョン 1803 日本語環境(岡根側は1809)
その他の質問

PC を再起動してもこの問題は再発します。
はい

**Comment by nishimotz** [comment]
こちらの環境は先ほどと同じですが、
左コントロールと右コントロール、
どちらの Ctrl+T も半角英字への変換は期待通りに動いています。

NVDA を入力ヘルプにして、
右コントロールキーを押すと、
「右コントロール」として動作していることが確認できますが、
いかがでしょうか。

**Comment by NVDAHelpDesk** [comment]
試してくださり、ありがとうございます。
こちらでも、入力ヘルプにして「左コントロール」「右コントロール」の読み上げを確認しました。
同じ現象を再現出来た機種は
Mouse　MBook 13 (Win10 1803)
ASUS E203NA (Win10 1809)
Lenovo ThinkPad E440 (Win10 1803)
MacBook Pro (BootCampでWin10 1803で動作)
MacBook (BootCampでWin8.1)
の5台です。
アドオンを無効化して再起動しても再現します。

**Comment by nishimotz** [comment]
お使いの音声エンジンと日本語IMEの種類をもう一度おしえていただけますか？

**Comment by nishimotz** [comment]
2013年ごろに NVDA 日本語版で独自に追加した処理の中で、
左側のコントロールキーだけを処理対象にしている箇所がありました。

右側のコントロールキーを使ったときにも、左と同じように動作させたい、
という要望だと理解してよいでしょうか？

**Comment by nishimotz** [comment]
このチケットでは、
日本語入力の読み上げを右Ctrlキーに対応させる件を扱います。
別の問題があれば、別のチケットを作ってください。

それから、
もし複数の人がひとつのアカウントを共有しておられる場合は、
おひとりずつアカウントを作って使ってくださると、
議論がわかりやすくなって助かります。

**Comment by NVDAHelpDesk** [comment]
野々垣です。
別のチケット件かもしれません。
abcdefgを入力して変換すると、最初hと読むような長いアルファベット文字列になりました。
後ほど録音してお送りしようと思っています。
昨日の昼頃の書き込みは岡根さんと御園さんの依頼で野々垣です。

**Comment by nishimotz** [comment]
こちらで再現できる手順がわかれば、録音は不要です。
右Ctrlキーでなくても起きる現象であれば、別のチケットでお願いします。
GitHub アカウントはおひとり一つずつでお願いします。

**Comment by NVDAHelpDesk** [comment]
野々垣です。
日本語変換オンの状態でabcdefgと入力し、画面上abcdefgとなるようにキーを押し（ここの読み上げが長くて不思議な文字列）、確定すると普通にabcdefgと読み上げられます。
日本語IMEはMicrosoft IMEです。

録音した音声ファイル（mp3、ドロップボックスリンク)
https://www.dropbox.com/s/cmi1telb2084373/NVDA%E8%8B%B1%E8%AA%9E%E9%9F%B3%E5%A3%B0.mp3?dl=0

**Comment by nishimotz** [comment]
右Ctrlキーに関係あるかどうか知りたいので、
もうすこし具体的に、キー操作の手順例を教えてください。

**Comment by yamahubuki** [comment]
@NVDAHelpDesk 野々垣 さん

投稿されているファイルを確認したところ、おそらく
「半角英字………」という文字列を「hancacu………」と読み上げてしまっているようです。


[こちら](https://github.com/nvdajp/nvdajp/issues/128) にて話題になっている件かと思います。

こちらのページは右Ctrlキーに関するものですので、もし何かあれば上記ページにてお願いします。

**Comment by nishimotz** [comment]
本件の修正を jp2018.4 ブランチに入れていたので、このまま 2018.4.1jp に反映させます。
