### ISSUE TITLE
設定：入力ジェスチャー

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#130]
### 問題の再現手順

1. 設定→入力ジェスチャー を開く
2. 入力ジェスチャー画面で、適用な位置で追加を行う
　（この時、追加ボタンの押下のみで、ジェスチャーの登録はしない）
3. OKボタン押下で画面を閉じる
4. 再度入力ジェスチャー画面を開こうとすると
　「NVDA設定ダイアログを表示中です。表示中のダイアログを閉じてください。」の
　エラーメッセージが表示される。
5. 以降、他の設定関連画面を開こうとしても同様のエラーが発生する

### 期待されること

再度、入力ジェスチャー画面が正常に開くことができる

### 実際に起きること

上記のエラーメッセージが表示される

### システム構成

NVDA 日本語版 2018.4jp インストール環境
Windows 10 Home バージョン 1809 日本語環境

**Comment by nishimotz** [comment]
確認しましたが再現できません。

「追加ボタンの押下のみで、ジェスチャーの登録はしない」

と書かれている箇所では、ジェスチャーの入力を待っているので、
例えば Tab キーを押して
「タブ（デスクトップ配列）」
「タブ（ラップトップ配列）」
のような選択肢が出てきたところで、それをキャンセル、
という手順になりますが、正しいでしょうか？

その後ダイアログのOKを押して閉じたのですが、
ご指摘の現象は起きていません。

NVDAのログビューアーに何かこれに関連するエラーが出ていれば、
教えていただけると助かります。

**Comment by koichimase** [comment]
事象発生手順としては、「追加」→「OK」ボタンのみです。
マウスによるアクションというのがポイントで、「追加」ボタン押下の後、
TABによるキー操作を行おうとした場合はこの事象が発生しないのは確認しています。

ちなみにこの時のログを貼り付けておきます。
=======================================================
ERROR - unhandled exception (14:02:58.914):
Traceback (most recent call last):
  File "wx\core.pyo", line 3240, in <lambda>
  File "gui\settingsDialogs.pyo", line 2931, in _addCaptured
  File "wx\core.pyo", line 1382, in _EvtHandler_Bind
  File "wx\core.pyo", line 1453, in Bind
RuntimeError: wrapped C/C++ object of type InputGesturesDialog has been deleted
=======================================================

**Comment by koichimase** [comment]
事象発生手順としては、「追加」→「OK」ボタンのみです。
マウスによるアクションというのがポイントで、「追加」ボタン押下の後、
TABによるキー操作を行おうとした場合はこの事象が発生しないのは確認しています。

ちなみにこの時のログを貼り付けておきます。
ERROR - unhandled exception (14:02:58.914):
Traceback (most recent call last):
File "wx\core.pyo", line 3240, in 
File "gui\settingsDialogs.pyo", line 2931, in _addCaptured
File "wx\core.pyo", line 1382, in _EvtHandler_Bind
File "wx\core.pyo", line 1453, in Bind
RuntimeError: wrapped C/C++ object of type InputGesturesDialog has been deleted

**Comment by nishimotz** [comment]
本家 2018.4 で再現しました。

**Comment by nishimotz** [comment]
2021.2jp-beta-210813m で確認しました。
追加ボタンと OK ボタンをマウスで操作しましたが、再現しませんでした。
wxPython がバージョンアップしているので、解決したのではないかと思います。
最近のバージョンで再現できるようでしたら、お知らせください。
