### ISSUE TITLE
ディスプレイの解像度が低い場合の要素リスト画面の見切れ

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#131]
### 問題の再現手順

1. 要素リスト画面を開く(NVDA+F7)
2. 「フィルター」フィールドおよび下部の３ボタンが見切れた状態で表示される

### 期待されること

項目、ボタン類が正しく表示されること

### 実際に起きること

表示見切れ
音声での操作自体は可能であるが、晴眼者による支援時に不適

### システム構成

NVDA 日本語版 2018.4jp インストール環境
Windows 10 Home バージョン 1809 日本語環境

**Comment by nishimotz** [comment]
この部分ですよね。
（画面キャプチャーで失礼します）

![image](https://user-images.githubusercontent.com/76300/50530264-1aae8180-0b3f-11e9-90b3-81886ba1e38e.png)

そちらではどのような状況でしょうか？

**Comment by koichimase** [comment]
![default](https://user-images.githubusercontent.com/46223642/50533640-46e2f600-0b71-11e9-927e-07d85786313a.png)

上記のような状態となります。
他のPCでも同様の事象となるのは確認しています。
また少なくとも前のNVDA 2018.3.2jpでも同様の事象が発生していました。

**Comment by nishimotz** [comment]
ディスプレイの解像度を 1024x768 に設定すると、ご報告いただいた状況になりました。

**Comment by koichimase** [comment]
参考までに、問題発生時PCはノートPCの1366x768で発生していました。
他のノートPCの1280x800でも同様の事象が発生しています。

**Comment by nishimotz** [comment]
本家 2018.4 で再現しました。

**Comment by nishimotz** [comment]
本家に issue を作りました。
https://github.com/nvaccess/nvda/issues/9148

**Comment by nishimotz** [comment]
本家 2019.3 で修正される予定です。
