### ISSUE TITLE
アドオンマネージャー：アドオンの無効化時のメッセージ

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#132]
### 問題の再現手順

1. アドオンマネジャーを開く
2. 稼働状態（有効状態）の任意のアドオンを選択し、「アドオンの無効化」ボタンを押下
3. 「閉じる」ボタンを押下
4. 以下のメッセージが表示される
　アドオンを変更しました。有効にするにはNVDAを再起動する必要があります。
　今すぐNVDAを再起動しますか？

### 期待されること

有効化→無効化の指示なのに、メッセージが「有効にするには...」となるので、どちらの
状態に変更しようとするのか紛らわしく、混乱する可能性がある。
「変更を反映させるには...」の方が良いのでは？

### システム構成

NVDA 日本語版 2018.4jp インストール環境

**Comment by nishimotz** [comment]
変更案です。
Committed revision 46965.

```
@@ -7899,8 +7899,8 @@
 "Changes were made to add-ons. You must restart NVDA for these changes to "
 "take effect. Would you like to restart now?"
 msgstr ""
-"アドオンを変更しました。有効にするにはNVDAを再起動する必要があります。今すぐ"
-"NVDAを再起動しますか？"
+"アドオンの変更を適用するにはNVDAを再起動する必要があります。今すぐ再起動しま"
+"すか？"

 #. Translators: Title for message asking if the user wishes to restart NVDA as addons have been added or removed.
 msgid "Restart NVDA"
```
