### ISSUE TITLE
入力ジャスチャーの追加定義反映がおかしい

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#134]
### 問題の再現手順

1. 設定 → 入力ジェスチャー に画面遷移する
2. 「全般 － 再起動」に（仮に）「Ctrl+Alt+P（キーボード、すべての配列）」の定義を追加する
3. OKボタン押下で画面を閉じる
4. NVDAを再起動する
5. 入力ジェスチャー画面を開くが、上記の定義が無い
6. OKボタン押下で、入力ジェスチャー画面を閉じる
7. 再度、入力ジェスチャー画面を開くと、上記の定義が表示される

### 期待されること

追加定義した内容が表示反映されること

### システム構成

NVDA 日本語版 2018.4jp インストール環境

### その他の質問

定義読み込みの不具合もしくは表示更新処理の問題？

**Comment by nishimotz** [comment]
ご報告から時間が過ぎてしまい、すみませんでしたが、
2021.2jp-beta-210813m で確認したところ、再現できませんでした。
なにか追加していただける情報があればお知らせください。
