### ISSUE TITLE
www.nvaccess.orgのURL表記

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#137]
### 期待されること

http://www.nvaccess.org/ の表記が残っている箇所がある
（https://www.nvaccess.org/ に修正済みの箇所もある）

該当箇所：
・「NVDA 2018.4jp ユーザーガイド」（userGuide.html）内の記述
・「NVDAについて」画面内のURL欄
　（ヘルプ → NVDAについて...）

### システム構成

NVDA 日本語版 2018.4jp インストール環境

**Comment by nishimotz** [comment]
ユーザーガイドの最後の記述は下記のように変更します。

Committed revision 46968.

```
--- userGuide.t2t       (revision 46966)
+++ userGuide.t2t       (working copy)
@@ -2782,6 +2782,6 @@
 | serviceDebug | DWORD | 0(既定)で無効, 1で有効 | 有効にするとセキュアデスクトップでセキュアモードを使用しません。セキュアデスクトップでPythonコンソー
ルやログビューアが有効になります。セキュリティに関する問題が強く懸念されるためこのオプションの利用は非推奨 |

 + さらに詳細な情報 +[FurtherInformation]
-NVDAに関して、さらに詳細な情報や助けが必要な場合は、NVDAのサイト、NVDA_URLを参照してください。
+NVDAに関して、さらに詳細な情報や助けが必要な場合は [NVDAのサイト https://www.nvaccess.org/] を参照してください。
 ここには追加のドキュメント、そして技術サポートやコミュニティーのリソースがあります。
 また、NVDA開発に関する情報やリソースも提供しています。
```

「NVDA について」画面内のURLは翻訳可能文字列ではないので、
すくなくとも本家版を変更するためにはプルリクエストが必要ですが、
以下の理由から、今回は対応を見送ります。

* ハイパーリンクではないためセキュリティの懸念がない
* NVDA 本家のソースコードのコメントがすべて http:// のURLであり、この URL はこのまま使い続ける意図があると考えられる
* http から https へのリダイレクトを nvaccess.org が行っている

やや余談になりますが www.nvda.jp が http と https の両方でのアクセスを
ユーザーが切り替えできるようにしている（強制的に https にリダイレクトしていない）理由は、
ユーザーの使っている OS やブラウザで https が利用できない場合にも、
NVDA をダウンロードできたほうがよい、と考えているからです。
