### ISSUE TITLE
時刻（短い形式）の午前付き形式での時刻の読み上げ

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#138]
### 問題の再現手順

1. 時刻の読み上げ機能（NVDA＋F12）で時刻を読み上げる
　「1：18」の場合、「イチジ ジューハップン」と読み上げる
2. Windowsの設定 → 時刻と言語 → 地域 に遷移
3. 「データ形式を変更する」リンク → 時刻（短い形式）を以下のように変更
　（変更前：デフォルト）9:40 → （変更後）午前 9:40
4. 時刻の読み上げ機能（NVDA＋F12）で時刻を読み上げる
　「午前 1：18」の場合、「ゴゼン イチジ コロン ジューハチ」と読み上げる

### 期待されること

時刻形式が「午前/午後」付きになっても、正しい時刻の読み上げを行う

### 実際に起きること

時刻の分の読みが「コロン (数字読み)」となる

### システム構成

NVDA 日本語版 2018.4jp インストール環境
Windows 10 Home バージョン 1809 日本語環境

**Comment by nishimotz** [comment]
作業メモ

```
>>> text = winKernel.GetTimeFormatEx(winKernel.LOCALE_NAME_USER_DEFAULT, winKernel.TIME_NOSECONDS, None, None)
>>> text
'午後 6:00'
>>> mo = re.match('(\d{1,2}):(\d{2})', text)
>>> mo
>>> mo = re.match('([^\d]+)(\d{1,2}):(\d{2})', text)
>>> mo
<re.Match object; span=(0, 7), match='午後 6:00'>
>>> mo.group(1)
'午後 '
>>> mo.group(2)
'6'
>>> mo.group(3)
'00'
```

**Comment by nishimotz** [comment]
作業メモ

"09:40" や "午前 09:40" の形式が選択される可能性もある

![image](https://user-images.githubusercontent.com/76300/70001659-387f3480-15a1-11ea-9b35-5d0aef3356f3.png)

**Comment by nishimotz** [comment]
「時刻（短い形式）」4種類に対応できたと思います。

**Comment by nishimotz** [comment]
betajp ブランチ

* 分や秒が 00 01 02 など2桁の数字の場合にのみ最初のゼロの削除を行うように修正

**Comment by nishimotz** [comment]
2019.3jp-beta-200102n に修正を反映しました。
