### ISSUE TITLE
コマンドラインオプション：ログファイルオプション

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#141]
### 問題の再現手順

1. コマンドライン(cmd.exe)を開く
2. NVDAのフォルダに移動(cd)する
3. 以下のコマンドを実行する
　nvda --log-file=c:\nvda.log

【エラーメッセージ】
Error occurred
The logfile 'C:\Program Files (x86)\NVDA\nvda.exe.log' could not be opened:
[Errno 13] Permission denied: 'C:\Program Files (x86)\NVDA\nvda.exe.log'

【補足】
このコマンドは「NVDA 2018.4jp ユーザーガイド」(userGuide.html）の
「15.1. コマンドラインオプション」に記載されているもの

### 期待されること

指定した場所に正しくログファイルが出力された状態で起動すること
またはアクセス権限の問題であればそれが正しく伝われるメッセージであること

### 実際に起きること

上記のエラーが表示される

### システム構成

NVDA 日本語版 2018.4jp インストール環境
Windows 10 Home バージョン 1809 日本語環境

### その他の質問

当初管理者権限としてコマンドプロンプトを起動したか否かによる問題かと
考えたが、このそれに関係なくエラーが発生する。
試しに「c:\test」フォルダを作成し、
　nvda --log-file=c:\test\nvda.log
を実行した場合は、正常に起動し、ログファイルが出力される。
Cドライブ直下もしくはそれらに準じたアクセス権等による問題で
あれば正しい実行条件が明確になっていれば問題がないと考えられる。
ここでの疑問として２つ。

1)エラーメッセージにあるログファイルのPATH名の怪しく、このPATH名から
　何が原因であるかが判明しない。（ログファイル名のPATH生成エラーか？）

2)（正常に起動できる環境が何であるか判明しないが）
　そもそもコマンド実行例（PATHの指定例）として適切なのか？
　実行するにあたっての条件等を追記もしくは、別のPATH名を掲示した方が
　良いのでは？

**Comment by nishimotz** [comment]
確認しました。

コマンドプロンプトで実行するとたしかに nvda.exe.log が作れないというエラーが出ます。

ですが、管理者権限でコマンドプロンプトを実行するとちゃんと NVDA が起動して、
c:\nvda.log が作成されました。またこの nvda.log は管理者権限でしか削除できません。

本件はこれ以上の対応を見送ります。理由は以下の通りです。

* 指摘された手順では NVDA の起動中の処理のどこかで nvda.exe.log を実際に作ろうとしてエラーが出ていると考えられるので、開発者はその情報を知る必要がある。
* c:\nvda.log というファイルを一般ユーザーが作成する権限があるかどうかは環境に依存するので、正しいとも正しくないとも言えない。
* 実行例として他のパスを書くとしても、他に適切な例がない。例えば c:\test や d:\ が存在するか、利用可能であるか、といったことは、やはり環境に依存する。
* パスを指定してログファイルを作成するユーザーは、こういった環境に依存する制約を理解していないとは考えにくい。
