### ISSUE TITLE
ユーザーガイド：「13.5. Windows OneCore 音声」内リンクエラー

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#142]
### 問題箇所

ユーザーガイド：「13.5. Windows OneCore 音声」内に記載されている
以下の部分のリンクがエラーとなる

利用できる音声の一覧とインストール方法は Microsoft の記事を参照してください:
https://support.microsoft.com/en-us/help/22797/windows-10-narrator-tts-voices 

### システム構成

NVDA 日本語版 2018.4jp インストール環境

### その他の質問

他にもユーザーガイド内の外部リンクにおいてhttp:→https:になっていたり、
メーカーサイトのリンクが変わっている（削除、移動）ものがいくつかあるようです。
とりあえずインパクトのありそうなマイクロソフト関連のリンクエラーについてのみ
報告しました。

**Comment by nishimotz** [comment]
日本語ユーザーガイドではリンク先を下記に変更しておきます。
https://support.microsoft.com/ja-jp/help/22805/windows-10-supported-narrator-languages-voices
