### ISSUE TITLE
コマンドラインオプション：-k/--check--runningの挙動

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#143]
### 問題の再現手順
該当オプションの機能である、実行中の有無を確認。
コマンドプロンプトから以下のコマンドを順次実行。

【-k オプション】
C:\Program Files (x86)\NVDA>nvda ← NVDA起動状態
C:\Program Files (x86)\NVDA>nvda -k  ← 疑問点(2)
C:\Program Files (x86)\NVDA>echo %errorlevel%
0

C:\Program Files (x86)\NVDA>nvda -q ← NVDA停止状態
C:\Program Files (x86)\NVDA>nvda -k
C:\Program Files (x86)\NVDA>echo %errorlevel%
0 ← 疑問点(1)

【--check-running オプション】
C:\Program Files (x86)\NVDA>nvda ← NVDA起動状態
C:\Program Files (x86)\NVDA>nvda --check-running  ← 疑問点(2)
C:\Program Files (x86)\NVDA>echo %errorlevel%
0

C:\Program Files (x86)\NVDA>nvda -q ← NVDA停止状態
C:\Program Files (x86)\NVDA>nvda --check-running
C:\Program Files (x86)\NVDA>echo %errorlevel%
0 ← 疑問点(1)

### 期待されること

前述の「疑問点(1)」で、「1」が返ってくること

### 実際に起きること

・前述の「疑問点(1)」で、「0」が返ってくる
・「疑問点(2)」の時に「使用不能」と読み上げられるが、意味が不明。
　NVDAが停止中の時は何の読み上げもない。どの挙動が正しい？

### システム構成

NVDA 日本語版 2018.4jp インストール環境
Windows 10 Home バージョン 1809 日本語環境

### その他の質問

使用方法が間違っていたり、終了コードの確認方法が間違っていたら
指摘して頂きたい。

**Comment by nishimotz** [comment]
Python 3.7.2 とコマンドプロンプトで下記のように確認できます。

```
> cd "C:\Program Files (x86)\NVDA"

> py -3
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.call(['nvda', '-k'], shell=True)
1
```

**Comment by koichimase** [comment]
%errorlevel%での確認はできない、ということなんですね。
それと、起動状態の時に「nvda -k」で「使用不能」と読み上げるのは仕様なのでしょうか？
それとも何か実行のタイミング等の別の要因でたまたま「使用不能」と読み上げているのでしょうか？
