### ISSUE TITLE
コマンドラインオプション： --launcher、--ease-of-access

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#144]
### 問題の再現手順

ユーザーガイドの「15.1. コマンドラインオプション」に各種起動オプションの
説明があるが、「nvda --help」で表示されるUsageの中の以下の２つオプション
についての説明がない。

 --launcher            Started from the launcher
 --ease-of-access      Started by Windows Ease of Access

### システム構成

NVDA 日本語版 2018.4jp インストール環境

### その他の質問

「--launcher」は実際に試してみると、使用許諾画面が表示されるが、
一度同意されたものがリセットされるのか等々、この画面の意味が不明
なので、このオプションの意図を確認したい。

**Comment by nishimotz** [comment]
これらはインストール環境で使用されることが想定されていないオプションです。
前者は Nulsoft Install System との連携のため、後者は Windows Vista / 7 で
「コンピューターの簡単操作」からサードパーティのスクリーンリーダーを使用する
機能への対応の目的で導入されました。
