### ISSUE TITLE
完全アンインストール/クリーンインストール

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#145]
### 背景（不満や不便なこと）
NVDAを利用していて、各種設定変更やアドオン追加を行った後、
NVDAを完全初期化しようと単にアンインストールの後、再インストールを
行っても以前の設定やアドオンモジュールが残っているため、初期化できない。

手動でアドオンの削除や、変更した内容を個別に定義削除等を行ったりすれば
良いことは理解しているが追加・変更した内容を完全に覚えていない場合も
あるのでただ単純に各種定義や追加モジュール類一式を完全インストールする
手段が欲しい。
またアンインストール後に「C:\Users\mase\AppData\Roaming\nvda」フォルダ
を手動削除すれば対応できるが（これで完全であるかどうかは分からないが）、
パソコンに詳しくないユーザーにはわかりづらい方法である。

### 提案したい機能や方法
アンインストール時のオプションとして、完全アンインストールができるモード
が欲しい。（いわゆるクリーンインストールするための前提作業として）
もちろん、再インストール時に前回の設定内容を引き継ぎたい場合もあるので
現在のアンインストールのモードはそのまま残すことは必須。

### 関連する情報があればお書きください

すでに代案が提示済みであれば教示いただい。

**Comment by nishimotz** [comment]
下記に設定情報が保存されている場所の説明があり、
その内容を削除すると設定情報の初期化とアドオンの削除ができます。

ユーザーガイド 11.5. 設定プロファイルの保存場所
http://www.nvda.jp/nvda2018.4jp/ja/userGuide.html#LocationOfConfigurationFiles

トラブルシューティングのための機能としては「アドオンを無効化して再起動」や、
コマンドラインの --config-path オプションなどがあります。

ご提案いただいたようなオプションが間違って使用されると困るので、
面倒かも知れませんがフォルダを個別に削除していただくほうが安全だと思います。
