### ISSUE TITLE
「ヘルプを独自のウィンドウで開く」ON時のヘルプ画面の操作中に音声が止まってしまう

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#147]
### 問題の再現手順

1. 設定 → 日本語設定 → 「ヘルプを独自のウィンドウで開く」ONにする
2. ヘルプ → 「NVDA日本語版の説明」でヘルプ画面を開く
3. ヘルプ画面内のタイトル部「NVDA日本語版の説明 2018.4jp」の適当な文字の上で
　ダブルクリックする
4. 音声読み上げが停止し、何も読まなくなる

ヘルプ画面内だけでなく他の画面に切り替えても、読み上げ停止状態となる。

補足：
「3.」については何がトリガーになっているのかについては不明。
画面内の適当な空白で、マウスのクリックを連打すると割とこの事象が発生
しやすいようである。

### 期待されること

マウス操作による操作が行われても、音声読み上げが止まらないこと

### 実際に起きること

音声の読み上げが止まる。
ただししばらく放置すると復旧する（音声の読み上げが再開する）ケースもある。
復旧が待てない場合はNVDAの再起動を行う。

### システム構成

NVDA 日本語版 2018.4jp インストール環境
Windows 10 バージョン 1809 日本語環境

### その他の質問

再現手順がの確認が難しく、一番単純で発生確率が高いものが
「NVDA日本語版の説明 2018.4jp」の適当な文字の上でのダブルクリックだった。
そのためこのダブルクリックについては特に意図があるものではない。

**Comment by nishimotz** [comment]
#123 に書きましたが「ヘルプを独自のウィンドウで開く」は将来使えなくなる
（廃止を検討している）オプションであるため、対応を見合わせます。

ですが、音声エンジンが短時間に大量の文字列を受け取った場合の不具合は、
本家でも検討されている課題であり、本件もそれに関係がありそうです。

より確実に再現できて、未報告の課題があれば、あらためてご報告ください。
