### ISSUE TITLE
要素リスト表示状態でNVDAが終了できない

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#149]
### 問題の再現手順
1. 要素リストが開いた状態にする（WebブラウザやWord等）
2. NVDAを終了する（終了ダイアログでOKボタンを押下）

### 期待されること
要素リスト画面を強制的に閉じ、NVDAが終了する。
もしくは、関連ウィンドウが開いたままなのでNVDAが終了できない旨の
メッセージが表示され、NVDAは終了しない。

【補足】
他のNVDAの各種設定画面等においては、画面が開いた状態でもNVDAを終了
指示するとすべて（？）の画面が閉じられ、NVDAが終了する。

### 実際に起きること
要素リスト画面が残ったままで、終了しない。

### システム構成
NVDA 日本語版 2018.4jp インストール環境

### その他の質問
よくこの手の強制終了時の動きとして、警告の意味で背面にあった要素リスト
がスクリーン前面にアクティブに表示されたりしていない。
（前面表示されること自体は晴眼者対象の動きではあるが）

**Comment by nishimotz** [comment]
「ようこそ画面」などの NVDA のダイアログが表示されている状態では NVDA の終了はできません。
現時点では仕様だとご理解ください。
