### ISSUE TITLE
設定項目「NVDAのエラーを音で報告」の機能説明がガイドにない 

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#152]
### 問題点
設定 → 日本語設定 → 設定項目「NVDAのエラーを音で報告」について、
機能説明がガイドに無い。

「NVDA日本語版の説明 2018.4jp(readmejp.html)」の「13.10. 2017.1jp の変更点」に
この機能について追加された旨の記載はあるが、具体的な機能内容についての記述
をガイド等に見つけることができない。

### システム構成
NVDA 日本語版 2018.4jp インストール環境

**Comment by nishimotz** [comment]
#16 の説明と重複しますが、旧チケットシステムの下記が本件の経緯です。

MMメール2がNVDA日本語ベータ版で頻繁にエラー音を出す

https://osdn.net/projects/nvdajp/ticket/36904

本家版 NVDA は下記の仕様になっています。

* リリース版ではエラーを音で報告しない
* アルファ版やベータ版ではエラーを音で報告する

本家では、リリース版で（音で報告されない）実行時エラーが出るが、それ以外に問題がないような事象は、不具合としては対応されません。（私が関わったかぎりではそのように思います）

日本語版ではリリース版かどうかの区別ではなく、このオプションで制御できるようにしたので、ベータ版やアルファ版でも実行時エラーを無視することが可能です。

アドオンや関連アプリの開発者などが、エラーを音で確認したい場合は、このオプションをチェックしてください。

一般ユーザーには不要な機能であること、ご指摘の通り 2017.1jp の変更点から見つけていただけるので、このままにさせてください。
