### ISSUE TITLE
「NVDA日本語版の説明 2018.4jp(readmejp.html)」ドキュメント

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#153]
### ドキュメントレビュー フィードバック
「NVDA日本語版の説明 2018.4jp(readmejp.html)」ドキュメントに対する内容確認結果

【表記ゆれ/ゆらぎ/画面表記】
・3. NVDAの起動
　ショートカットキー CTRL+ALT+N で起動できます/... Ctrl+Alt+N ...

・5.2.2. 大文字の前に大文字と読む
　併う/伴う [補足]読めなくもないが、スクリーンリーダーで読め上げないこともあり...

・5.3.1. 日本語のテーブル
　LibLouis/Liblouis [補足]先頭のみ大文字が正しい表記(cf http://liblouis.org/)

・5.4. NVDA設定ダイアログ「キーボード」カテゴリ
　「Caps LockキーをNVDA制御キーとして使用」/[実画面の表記と合っていない]

・8.1. ヘルプ
　「ヘルプを既定のブラウザではなくHTAで開く」/[実画面の表記と合っていない]

・9.2. Microsoft Word サポート
　書式情報「段落インデントの報告」を有効にしてお使いください/[実画面の表記と合っていないと思われる]

・ドライバ/ドライバー [文書内全般的に]

【その他】
・2. システム要件とインストール
　120MB/193MB [補足] 2018.4jpのポータブル版USBメモリでの消費量の実測確認

・8.2. スピーチビューアーと点字ビューアー
　Alt+スペースでシステムメニューを開いて最大化できるようにする/[実画面でこの操作はできない]

### システム構成
NVDA 日本語版 2018.4jp インストール環境

**Comment by nishimotz** [comment]
変更をコミットしました。
日本語ベータ版の次回更新で反映されます。
