### ISSUE TITLE
コマンドプロンプトでのレビューカーソルでの文字読み上げ

### ISSUE THREAD

**Issue by riku22** [nvdajp/nvdajp#154]
### 問題の再現手順

1. コマンドプロンプトを開く。
1. 例として、「echo abcテスト」と入力し、Enterキーを押す。
1. テンキー7で「abcテスト」というところまで移動する。
1. テンキー1とテンキー3で文字読みをさせる。
1. 英字部分は正常に読み上げるが、日本語部分が「スペース」もしくは「ブランク」と読み上げる。

### 期待されること
　日本語部分も正常に読み上げる。  
　（例）：「カタカナ テ、カタカナ ス、カタカナ ト」

### 実際に起きること
　日本語部分が「スペース」もしくは「ブランク」と読み上げられる。

### システム構成

- NVDA jpalpha-181214v
- Windows 10 1809 64ビット版

### その他の質問

- PC を再起動してもこの問題は再発する：はい

**Comment by nishimotz** [comment]
元の報告
https://osdn.net/projects/nvdajp/ticket/37131

フォントをラスターフォントにするという回避策があった。

最近確認した状況

* 本家 2019.2 rc2 高度な設定「ターミナルで UI オートメーション」を有効にすると解決する
* 日本語版 2019.2jp-beta-190807v では解決していない
* py37jp ブランチの日本語アルファ版では解決している

本家チケット
https://github.com/nvaccess/nvda/issues/2157

**Comment by nishimotz** [comment]
新しい日本語アルファ版でこの件が解決しているでしょうか

http://s.nvda.jp/nvda_jpalpha_190815s.exe

**Comment by nishimotz** [comment]
2019.3 で解決するはずなのでクローズします。
日本語アルファ版で
「高度な設定」
Microsoft UI オートメーション → Windows コンソール
「自動設定」（デフォルトのまま）
でご確認ください。
