### ISSUE TITLE
絵文字「スペード」「クラブ」「ダイヤ」(U+266x) の読み上げレベル

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#158]
### 問題の再現手順

1. Win+.（ピリオド）で絵文字入力画面を開く
2. 「記念日とオブジェクト」グループを選択
3. 「スペード」および「クラブ」に矢印でカーソルを移動

念のため上記操作時の画面をキャプチャーしたものを添付
[絵文字.zip](https://github.com/nvdajp/nvdajp/files/2741412/default.zip)

### 期待されること
それぞれの絵文字が「スペード」、「クラブ」と読み上げられること

### 実際に起きること
スペードの絵文字が「117の295  レベル2」と読み上げられ
クラブの絵文字が「118の295  レベル2」と読み上げられ、マーク部分を読み上げない

ちなみに
ハートの絵文字は「ハート  119の295  レベル2」、
ダイヤの絵文字は「ダイヤ  120の295  レベル2」と正しく読み上げられる

### システム構成
NVDA 日本語版 2018.4jp インストール環境
Windows 10 Home バージョン 1809 日本語環境

### その他の質問
【補足事項】
・ナレーターでは正しく読み上げている
・そもそも「xxx の xxx レベル x」の読み上げは必要？（抑制できない？）

**Comment by nishimotz** [comment]
U+2660 ♠️
U+2663 ♣️
U+2665 ♥️
U+2666 ♦️

**Comment by nishimotz** [comment]
それぞれ文字は登録されていますが、それぞれの文字の記号読み上げレベルが違うため、設定によっては上記の状況が起こることを確認しました。

```
♣	クラブ	most
♦	ダイヤ	some

♠	スペード	most

♥	ハート	none
```

**Comment by nishimotz** [comment]
ハートの読み上げレベル none に他の3文字を合わせる変更をします。

これは「句読点／記号読み辞書」でカスタマイズできますが、デフォルト値を変えることになります。
