### ISSUE TITLE
Symbols.dic不備（誤記等）

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#159]
### Symbols.dic
symbols.dic(591行目):	カコウカープ
　「カコウカーブ」の誤記

symbols.dic(593行目):	ミギヤジルシ
　「ヒダリヤジルシ」の誤記

symbols.dic(1596行目):	フキゲン
　誤記（少なくとも「不機嫌」ではない）
　characters.dic にも影響あり
　characterDescriptions.dic にも影響あり

symbols.dic(1696行目):	リョキャクセン
　「キャクセン」もしくは「リョカクセン」の誤記
　characters.dic にも影響あり
　characterDescriptions.dic にも影響あり

### システム構成
NVDA 日本語版 2018.4jp インストール環境

### その他の質問
絵文字関連の機能検証中にSymbols.dic内における比較的クリティカルな問題であると
考えたものを報告対象とした。

**Comment by nishimotz** [comment]
本家翻訳チーム revision 46589

```
Index: symbols.dic
===================================================================
--- symbols.dic	(revision 46548)
+++ symbols.dic	(working copy)
@@ -588,9 +588,9 @@
 ➿	フリーダイヤル	none
 
 ⤴	ジョウショウカーブ	none
-⤵	カコウカープ	none
+⤵	カコウカーブ	none
 
-⬅	ミギヤジルシ	none
+⬅	ヒダリヤジルシ	none
 ⬆	ウエヤジルシ	none
 ⬇	シタヤジルシ	none
 ⬛	シカクケイ	none
@@ -1593,7 +1593,7 @@
 😿	ナミダ	none
 🙀	ラクタンノヒョウジョウ	none
 🙁	シカメッツラ	none
-🙂	フキゲン	none
+🙂	スコシエガオ	none
 🙃	サカサマ	none
 🙄	ウワメヅカイ	none
 🙅	ヒテイ	none
@@ -1693,7 +1693,7 @@
 🛫	リリク	none
 🛬	チャクリク	none
 🛰	ジンコウエイセイ	none
-🛳	リョキャクセン	none
+🛳	リョカクセン	none
 
 🤐	チンモク	none
 🤑	カネノモウジャ	none
```
