### ISSUE TITLE
クリップボード履歴(Win+V)の読み上げ不良

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#162]
### 問題の再現手順

1. Win+Vでクリップボードを開く
　（初回起動時に「有効にする」で、履歴を参照できるようにする）
2. TABで矢印キーで各種操作を行う

### 期待されること
・クリップボード履歴の内容について、時刻およびその内容が読み上げられる
・「すべてクリア」のリンクにフォーカスが移動した時に、その旨が読み上げられる

### 実際に起きること
・各履歴にフォーカスが移動しても、先頭（最新）のクリップボード履歴を読み上げる
・時刻を「ｘ コロン ｘ」の形式で読み上げる
・「すべてクリア」のリンクにフォーカスが移動した時に、その旨が読み上げられない

### システム構成
NVDA 日本語版 2018.4.1jp インストール環境
Windows 10 バージョン 1809 日本語環境

### その他の質問
ナレーターで操作した場合、期待した読み上げになっているので、それに準拠した
動きとなることを想定

**Comment by nishimotz** [comment]
#211 で対応できたと思います。

**Comment by koichimase** [comment]
下記の２点については改善されていないと思われますが、いかがでしょうか？
（前述の報告通り、ナレーターでの動作と比較した上での指摘です）

・時刻を「ｘ コロン ｘ」の形式で読み上げる
・「すべてクリア」のリンクにフォーカスが移動した時に、その旨が読み上げられない

**Comment by nishimotz** [comment]
Windows バージョン 1903 日本語環境でやや仕様が変わっているようで、
時刻や「すべてクリア」などは視覚的にも表示されておらず、
ナレーターでも読み上げはありません。
Windows の更新に合わせて今後も仕様が変わるとご理解ください。
