### ISSUE TITLE
ブラウズモードでの検索ボックス

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#169]
### 問題の再現手順
1. ブラウズモードで検索操作を行う（NVDA+Ctrl+F）

該当画面：
![find](https://user-images.githubusercontent.com/46223642/51628203-b9d06880-1f87-11e9-8ef1-90e76c46ec1a.png)

### 期待されること
検索機能としては特に問題なし

### 実際に起きること
晴眼者視点の指摘として、検索ダイアログ内の各種コントロールの配置が悪く、
コントール間が詰まっていたり、ダイアログのフレームに接地するような
デザインとなってしまっている。

### システム構成
NVDA 日本語版 2018.4.1jp インストール環境
Windows 10 バージョン 1809 日本語環境
画面解像度：1366ｘ768

**Comment by nishimotz** [comment]
2019.3 本家版に修正が提案され、改善する予定です。
日本語アルファ版でご確認いただけます。
