### ISSUE TITLE
コマンドプロンプトの終了

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#170]
### 問題の再現手順

1. コマンドプロンプト(CMD.EXE)を起動する（起動方法は任意）
2. ウィンドウ右上の「閉じる」を押下して終了する

### 期待されること
コマンドプロンプトが終了しても、NVDAの操作が継続できる

### 実際に起きること
「閉じる」を押下し終了させると、NVDAが落ちてしまう。

コマンドプロント画面からのExitコマンドによる終了および
Alt+F4での終了では特に問題はない。

### システム構成
NVDA 日本語版 2018.4.1jp インストール環境
Windows 10 バージョン 1809 日本語環境

**Comment by nishimotz** [comment]
2019.2 の「高度な設定」
「可能な場合に Windows コンソールで UI オートメーションを使用」
で解決するでしょうか。

2019.3 に向けた開発版では
「高度な設定」 Windows Console Support を「自動設定」にしてみてください。

**Comment by nishimotz** [comment]
2019.3 で Windows コンソールへの対応が改善されます。
日本語アルファ版 191129p でもクラッシュしないことを確認しています。
