### ISSUE TITLE
PowerShellの終了

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#171]
### 問題の再現手順
1. Windows PowerShellを起動する（起動方法は任意）
2. ウィンドウ右上の「閉じる」を押下して終了する

### 期待されること
PowerShellが終了しても、NVDAの操作が継続できる

### 実際に起きること
「閉じる」を押下し終了させると、NVDAが落ちてしまう。

PowerShell画面のExitコマンドによる終了およびシステムメニューの
「閉じる」での終了では特に問題はない。

### システム構成
NVDA 日本語版 2018.4.1jp インストール環境
Windows 10 バージョン 1809 日本語環境

**Comment by nishimotz** [comment]
#170 と同じ作業で解決するはずです。
