### ISSUE TITLE
Microsoft Edgeの「検索またはWebアドレスを入力」の日本語入力切り替えが正常に読まれない

### ISSUE THREAD

**Issue by TetsuroOkane** [nvdajp/nvdajp#184]
### 問題の再現手順

1. Microsoft Edge を開く
2. 全角半角キーで日本語入力にする
3. "NVDA日本語版" とキー入力する
4. NVDAnihongoと読まれてしまう

問題の再現に必要なファイルは ZIP 形式のアーカイブで添付

### 期待されること

「Firefox」や「Chrome」同様入力時は「NVDAniにhoほnnんgoご」変換時は「NVDA日曜日の日、本箱の本、言語の語」と読み上げられる

### 実際に起きること

「文字変換」「変換停止」やビープ音での入力モードの切り替えが報告されず、入力内容も「NVDAnoにhoほnnんgoご」が「NVDAnihongo」とアルファベットしか読まれない
変換も確定後に左右矢印で確認した時しか読まれない

### システム構成

NVDA 日本語版 2018.4.1jp インストール環境

Windows 10 バージョン 1809 日本語環境

Microsoft Edge

機種 SurfaceLaptop

### その他の質問

PC を再起動してもこの問題は再発する
NVDA 日本語版 2019.1jp-beta-190308aでも再現する

**Comment by nishimotz** [comment]
再現手順をもう少し詳しく教えてください。
Edge でどこに入力したらいいですか？
Microsoft IME で試せばいいでしょうか？

**Comment by TetsuroOkane** [comment]
Edge起動直後またはCtrl+Lを押して「検索またはWebアドレスを入力」と読まれる位置でも、予めBingやGoogle、Yahoo!等の検索サイトを開いて、検索欄に入力しても同じ状態になります。
音声のみで確認していると、Edgeでは日本語入力モードに出来ない不具合のように感じられますが、画面上ではモードが変わる時に「あ」や「A」が表示され「あ」の状態では日本語で入力されていますが、音声はアルファベットで入力内容を読んでいます。
IME関連はデフォルトのままとのことなので、Microsoft IMEなはずです。
(先程自分の所有しているパソコンでも確認したところ、、ASUS ZenBookで再現しました。)

**Comment by nishimotz** [comment]
日本語アルファ版 190304l では気づかなかったのですが、
日本語ベータ版ではたしかにご指摘の状況です。

本家アルファ版でも現象を確認できたので、
本家の過去バージョンの状況を調べてみます。

~~Windows 10 version 1803 でも再現できるようです。~~


もしわかれば以下をお知らせください。

* Edge で Microsoft 日本語 IME が期待通りに動いていた Windows 10 と NVDA の各バージョン
* Edge 以外にこの現象が起きるアプリがあるか

**Comment by nishimotz** [comment]
日本語アルファ版 190304l と Windows 10 version 1803 の組み合わせで、以下を確認しました。

* NVDA がインストールされている場合は Edge で Microsoft IME は変換前の文字列や「文字変換」「変換停止」を読み上げる
* インストーラーで「動作を継続」した場合はローマ字入力のアルファベットしか読み上げない。「文字変換」「変換停止」も読み上げない

UI オートメーションの影響だと思うのですが、インストールされた NVDA でないと期待通りに動かない可能性があることはいちおうお伝えしておきます。

**Comment by nishimotz** [comment]
2019.1jp-beta-190308a がインストールされた環境で下記を確認しました。

* Windows 10 version 1803 : Edge + Microsoft IME は読み上げしている
* Windows 10 version 1809 : Edge + Microsoft IME は本件で報告された状況になる

このことから判断して 1809 の Edge に NVDA が対応できていない、という可能性があります。

本家版に修正が必要なのか、日本語版の独自変更に関わることなのか、まだ判断できていません。

**Comment by nishimotz** [comment]
本家 beta1 で確認した結果を下記に報告しました

https://github.com/nvaccess/nvda/issues/9362

**Comment by nishimotz** [comment]
この件の現状を確認されていますか？

**Comment by TetsuroOkane** [comment]
Version: 2020.1jp-beta-200414qでアドレス検索バーでは正常に動作することを確認しました。
レガシーバージョン、Chromiumバージョン共に半角全角キーで文字変換、変換停止と読まれ、文字変換状態で「yaや maま」と読まれ、スペースキーを押すと、「やまさんみゃくのさん」と読まれ「山」に変換できています。
しかし、直接google.co.jpを開き、検索入力欄に入力する際に、レガシーバージョンでは文字変換や変換停止や入力した文字の確認時に無音になる事がある(フォーカスを外して戻すと喋る)、Chromiumバージョンでは、左右キーでの読み上げで不具合があり、「あいうえお」と入力した場合「あいええ無音」と言う謎な症状が出る事があり、こちらもフォーカスを外して戻すと正常に読まれています。

**Comment by nishimotz** [comment]
解決したと判断して本家のチケットも取り下げます。
残った課題は別のチケットを作っていただけると助かります。
