### ISSUE TITLE
espeak-ng: NVDAJP-based customizations no longer work

### ISSUE THREAD

**Issue by zersiax** [nvdajp/nvdajp#185]
### 問題の再現手順

1. Set Espeak-NG as your speech synthesizer.
2. Have it read the word おはよう.

問題の再現に必要なファイルは ZIP 形式のアーカイブで添付

### 期待されること

Using jTalk processing, eSpeak-NG should aproximate the word and pronounce it.

### 実際に起きること

Espeak-ng reads " o h a y o u ", which is also what happens in the English version of NVDA.

### システム構成

NVDA 2019.1 alpha.

Windows 10 バージョン 1809 English 

Tested both with an already existing profile and a completely seperate portable copy of the latest alpha.

**Comment by nishimotz** [comment]
discussed in Japanese as follows
* #128
* #65

**Comment by nishimotz** [comment]
fixed in 2019.1jp beta, as well as the latest Japanese alpha.
