### ISSUE TITLE
記号読み上げレベル「ほとんど読み上げ」で "," を読み上げない

### ISSUE THREAD

**Issue by misonojapan** [nvdajp/nvdajp#189]
### 問題の再現手順

1. NVDA+P で「ほとんど読み上げ」にする
2. メモ帳やWordなどを開く
3. 「,	コンマ	-	never」と入力する
4. エンターキーを押す
5. 上矢印キーを押す
6. １行読みされる
7. , 記号を読まない
※jtalk使用

### 期待されること

symbols.dicで同じように定義されている

(	カッコ	-	never
)	カッコトジ	-	never

などは「ほとんど読み上げ」で対応する読み方で読み上げる。

### 実際に起きること

, を 「コンマ」と読み上げるようにしたい

### システム構成

NVDA 日本語版 2019.1.jp インストール環境
Windows 10 バージョン 1809 日本語環境
Microsoft Office 2019またはメモ帳

### その他の質問

PC を再起動してもこの問題は再発する
はい
NVDA 日本語版 2018.1jp でも再現する
はい

**Comment by nishimotz** [comment]
現状と過去の経緯を確認しています。

U+002c は en の symbols.dic で
```
,	comma	all	always
```
になっていて、
ja の symbols.dic では
```
,	コンマ	-	never
```
になっています。

level は第3フィールドで、 "-" は default を表すので、
en で定義された all の値が使われます。

その結果「ほとんど読み上げ」では読み上げない、
「すべて」で読み上げる、という動作になっています。

2012年に私が作業をするようになってからずっと、
この文字についてはこの仕様のようです。

もしご提案どおりにユーザーが設定を変更すると、
ユーザー設定フォルダーの symbols-ja.dic が下記のようになります。

```
symbols:
,	-	most
```

この状態で問題がないか考えてみましたが、例えば
1,234
のような数字の位取りの読み上げは大丈夫のようです。

もうすこし調べてみます。

**Comment by nishimotz** [comment]
コンマを all から most に変更します。

Committed revision 48677

```
Index: symbols.dic
===================================================================
--- symbols.dic	(revision 48675)
+++ symbols.dic	(working copy)
@@ -70,7 +70,7 @@
 )	カッコトジ	-	never
 *	アスタリスク	some
 +	プラス
-,	コンマ	-	never
+,	コンマ	most	never
 -	マイナス	some
 .	ピリオド	some
 /	スラッシュ	some
```
