### ISSUE TITLE
Excelのドロップダウンリストが選べない

### ISSUE THREAD

**Issue by TetsuroOkane** [nvdajp/nvdajp#192]
### 問題の再現手順

1. Excelを開き、A1に「好きな季節」と入力し、A2に移動します。
2. 「データ」タブの「データツール」グループの「データの入力規則」を選びます。
3. 「入力値の種類」を「リスト」にし、「元の値」に「春,夏,秋,冬」と入力し、OKボタンでエンターキーを押します。
4. 手順3までで作られたドロップダウンリストをAlt+下矢印で展開し、選択しようとすると無音になる。

### 期待されること

ドロップダウンリストの内容が読み上げられ、項目の選択が出来る

### 実際に起きること

画面上では上下矢印で項目の選択は出来ているが、読み上げされない

### システム構成

例：NVDA 日本語版 Version:2019.1.1jp-beta-190408l インストール/ポータブル版共

Windows 10 バージョン 1809 日本語環境

Microsoft Office 2013

### その他の質問

PC を再起動してもこの問題は再発する
はい
NVDA 日本語版 2019.1jp でも再現する
はい

#### 他のバージョンの NVDA と比較している場合はその結果

アルファ版jpalpha_190408pでも再現する為報告しました。

**Comment by nishimotz** [comment]
本家 2019.1.1rc1 で同様の操作をすると Excel がクラッシュするようです。
報告したいと思います。

**Comment by nishimotz** [comment]
本家版と英語環境で確認して本家に issue を立てたのですが、
なぜか英語環境だと再現に手間がかかります。
（何回かドロップダウンを開いたり閉じたりするとやっとクラッシュする）

**Comment by nishimotz** [comment]
本家 alpha 版で久しぶりに確認したら、クラッシュを再現できなくなりました。
日本語版の最近のバージョンではまだ確認していません。

**Comment by nishimotz** [comment]
本家版では「再現できなくなったから解決ということで」になりそうです。
日本語版でも現在のアルファ版（未配信ですが 191023j で先ほど確認）では再現できません。
どのあたりで解決したか、正確には把握できていませんが、
いったんクローズとします。
