### ISSUE TITLE
NVDAの言語が日本語の場合にeSpeakの読み込みに失敗する

### ISSUE THREAD

**Issue by riku22** [nvdajp/nvdajp#195]
### 問題の再現手順

1. 新規作成したポータブル版等、eSpeakの設定が何もされていない設定ファイルを用意する。
　※具体的には、「nvda.ini」の「[speech]」セクションに「[espeak]」のセクションが存在しないファイルを用意する。
1. 「一般設定」で言語を「既定の言語」もしくは「日本語」に設定する。
1. 「音声エンジンの選択」で「eSpeak NG」を選択し、Enterキーを押す。
1. 音声エンジンの読み込みに失敗した旨のエラーが表示される。

### 期待されること

　eSpeakが正常に読み込まれ、読み上げが行われる。

### 

　音声の読み込みに失敗した旨のエラーが表示され、ログに下記のエラーが出力される。
　また、この際、ほかの音声エンジンに切り替えようとしても、うまく音声が出力されなくなり、再起動が必要となる。

    INFO - synthDrivers.espeak.SynthDriver.__init__ (09:53:21.266):
    Using eSpeak NG version 1.49.3 dev
    ERROR - synthDriverHandler.setSynth (09:53:21.309):
    setSynth
    Traceback (most recent call last):
      File "synthDriverHandler.pyo", line 112, in setSynth
      File "synthDriverHandler.pyo", line 84, in getSynthInstance
      File "synthDriverHandler.pyo", line 31, in changeVoice
      File "synthDrivers\espeak.pyo", line 233, in _set_voice
      File "synthDriverHandler.pyo", line 384, in _get_language
    KeyError: 'ja'

### システム構成

- NVDA日本語版 jpalpha_190426s
- Windows 10 バージョン 1809 日本語環境

### 補足

　1度NVDAの言語を英語にしたうえで、eSpeakを読み込むと、上記のエラーは発生しません。
　また、この状態で設定を保存しておけば、NVDAの言語を既定の言語や日本語に切り替えても、上記のエラーは発生しなくなります。
　なお、過去のバージョンでもテストしようと思いましたが、手元にインストーラが残っていなかったため、テストできませんでした。

**Comment by nishimotz** [comment]
nvda.ini の espeak セクションを削除して確認しましたが、再現できません。
何か espeak を上書きするアドオンをお使いではないでしょうか？

**Comment by riku22** [comment]
ご指摘ありがとうございます。
すみません、もう1度ちゃんと調べてみたところ、こちらで利用している音声エンジンの問題だったようです。
ご迷惑をおかけしました。
