### ISSUE TITLE
絵文字の読み上げについて

### ISSUE THREAD

**Issue by riku22** [nvdajp/nvdajp#207]
### 問題の再現手順

1. メモ帳を開く。
1. 日本語入力をオンにして、「ハート」と入力し、絵文字を選んで確定する。
　※ここでは、「青いハート」を選択したものとして説明する。
1. 上下矢印や左右矢印を押しても、「ハート」としか読まれず、絵文字の説明が行われない。

### 期待されること

　上下左右の矢印を押すと、「青いハート」と読み上げる。

### 実際に起きること

　上下左右の矢印を押しても、「ハート」としか読み上げない。

### 補足事項

　NVDAの言語を英語にして、音声エンジンを「eSpeak NG」にすると、上下左右の矢印を押した際も「Blue heart」と読み上げるため、日本語版固有の問題だと思われる。
　あくまで推測だが、「句読点/記号読み上げ辞書」に日本語版独自で絵文字の読み方を登録しているためではないだろうか。

### システム構成

- NVDA日本語版 jpalpha_190528v
- Windows10 1903 64ビット版

### その他の質問

- PC を再起動してもこの問題は再発する：はい

**Comment by nishimotz** [comment]
青いハート u+1f499 ですね。
たしかに nvdajp の辞書は「ハート」で、
「Unicode コンソーシアムのデータ」には「青いハート」が入っているようです。

**Comment by nishimotz** [comment]
簡単なツールを作って不一致の内容をチェックしているところです。
今回は「ハート」に関わる辞書エントリだけ更新しようと思います。

NVDA日本語版独自の文字説明辞書はずっとカタカナで読みを記述してきました。
「Unicode コンソーシアムのデータ」は漢字カナ交じりで表記されています。

より多くの絵文字や記号を「Unicode コンソーシアムのデータ」に揃えていく方針にした場合に、

* Unicode コンソーシアムのデータをカタカナ表記に手作業で書き換える
* 文字説明が漢字カナ交じり表記であってもよいことにして「Unicode コンソーシアムのデータ」で内容を置き換える

といった作業案になります。

歴史的に詳細読み辞書はカタカナ表記で作られてきました。
理由は、音声エンジンの読み付与の誤りを回避するためと思われます。

ですが、すでに NVDA でも「Unicode コンソーシアムのデータ」に関しては、漢字カナ交じり表記が使われてしまっています。
多くの場合は「日本語版の独自辞書」が優先されるために気づかれていないと思います。

漢字で表記したほうがイントネーションが正しくなったり、点字ディスプレイでより適切に表示されるようになる、といったメリットもあります。

将来的に「Unicode コンソーシアムのデータ」と重複するような独自辞書を持つことをやめるという方針もあり得ます。

**Comment by nishimotz** [comment]
作業メモ（たぶん文字化けしている）
いちばん右が CLDR （Unicode コンソーシアムのデータ）

```
$ py -3 cldr_to_chars.py
symbols.dic:538 ['♥', 'ハート', 'none'] => ハート
symbols.dic:605 ['❣', 'ハート', 'none'] => ハートのびっくり
symbols.dic:606 ['❤', 'ハート', 'none'] => 赤いハート
symbols.dic:1325 ['�', 'ハート', 'none'] => ドキドキするハート
symbols.dic:1327 ['�', 'ハート', 'none'] => 2つのハート
symbols.dic:1328 ['�', 'ハート', 'none'] => きらきらハート
symbols.dic:1329 ['�', 'ハート', 'none'] => 大きくなるハート
symbols.dic:1330 ['�', 'ハート', 'none'] => ハートに矢
symbols.dic:1331 ['�', 'ハート', 'none'] => 青いハート
symbols.dic:1332 ['�', 'ハート', 'none'] => 緑のハート
symbols.dic:1333 ['�', 'ハート', 'none'] => 黄色のハート
symbols.dic:1334 ['�', 'ハート', 'none'] => 紫のハート
symbols.dic:1335 ['�', 'ハート', 'none'] => ハートにリボン
symbols.dic:1336 ['�', 'ハート', 'none'] => 回転するハート
symbols.dic:1337 ['�', 'ハート', 'none'] => ハートデコ
characters.dic:541 ['♥', '2665', '[ハート]', 'ハートノ エモジ'] => ハート
characters.dic:612 ['❣', '2763', '[ハート]', 'ハート'] => ハートのびっくり
characters.dic:613 ['❤', '2764', '[ハート]', 'ハート'] => 赤いハート
characters.dic:8496 ['�', '1f493', '[ハート]', 'ハートノ エモジ'] => ドキドキするハート
characters.dic:8498 ['�', '1f495', '[ハート]', 'ハートノ エモジ'] => 2つのハート
characters.dic:8499 ['�', '1f496', '[ハート]', 'ハートノ エモジ'] => きらきらハート
characters.dic:8500 ['�', '1f497', '[ハート]', 'ハートノ エモジ'] => 大きくなるハート
characters.dic:8501 ['�', '1f498', '[ハート]', 'ハートノ エモジ'] => ハートに矢
characters.dic:8502 ['�', '1f499', '[ハート]', 'ハートノ エモジ'] => 青いハート
characters.dic:8503 ['�', '1f49a', '[ハート]', 'ハートノ エモジ'] => 緑のハート
characters.dic:8504 ['�', '1f49b', '[ハート]', 'ハートノ エモジ'] => 黄色のハート
characters.dic:8505 ['�', '1f49c', '[ハート]', 'ハートノ エモジ'] => 紫のハート
characters.dic:8506 ['�', '1f49d', '[ハート]', 'ハートノ エモジ'] => ハートにリボン
characters.dic:8507 ['�', '1f49e', '[ハート]', 'ハートノ エモジ'] => 回転するハート
characters.dic:8508 ['�', '1f49f', '[ハート]', 'ハートノ エモジ'] => ハートデコ
characterDescriptions.dic:514 ['♥', '(ハートノ エモジ)'] => ハート
characterDescriptions.dic:586 ['❣', '(ハート)'] => ハートのびっくり
characterDescriptions.dic:587 ['❤', '(ハート)'] => 赤いハート
```
