### ISSUE TITLE
Windows + V クリップボード履歴の読み上げ

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#211]
### 問題の再現手順

1. メモ帳を開く
2. 何かを選択して Ctrl+C でコピーする
3. Windows+V でクリップボード履歴を開く
4. 上下の矢印キーで確認する

### 期待されること

クリップボード履歴を読み上げる

### 実際に起きること

フォーカスがメモ帳のままである

### システム構成

NVDA 2019.2jp-beta-190712k

#### 他のバージョンの NVDA と比較している場合はその結果

本家 2019.2 beta3 ではこの問題は起きない

**Comment by nishimotz** [comment]
下記で解決することがわかった

1. 本家 beta ブランチ appModules にある windowsinternal_composableshell_experiences_textinput_inputapp.py を、日本語ベータ版のユーザー設定フォルダ、開発者スクラッチパッドの appModules にコピー
2. NVDA日本語ベータ版を再起動

どうやら #122 の作業を revert したほうがよさそう。

**Comment by nishimotz** [comment]
2019.2jp-beta-190720d に更新しました。

**Comment by yama3nomori** [comment]
バージョン 21H1 (OS ビルド 19043.1165)
2021.2.jp beta210907p
でクリップボード履歴の読み上げ不具合を確認しました。
オブジェクトカーソルでは閲覧できますが、通常のカーソルでフォーカスできていないようです。
