### ISSUE TITLE
ブラウズモードにおけるNVDAの検索機能利用時の日本語入力における不具合

### ISSUE THREAD

**Issue by riku22** [nvdajp/nvdajp#212]
### 問題の再現手順

1. ブラウズモードを利用できるアプリケーション（InternetExplorerやFirefox、MicrosoftOffice Word等、ブラウズモードが利用できるアプリケーションであればどれでもよい）を起動する。
1. ブラウズモードになっていない場合は、NVDA+スペースでブラウズモードにする。
1. Ctrl+NVDA+Fを押して、検索ダイアログを開く。
1. 日本語変換をオンにして、「テスト」と入力し、Escキーを押す（Enterキーで確定しないこと）。
1. 検索ダイアログが閉じてしまう。

### 期待されること

日本語入力がキャンセルされ、検索ダイアログは閉じない。

### 実際に起きること

日本語入力のキャンセルとともに、検索ダイアログが閉じてしまう。

### システム構成

- Windows 10 1903 64ビット
- NVDA日本語版 jpalpha_190705u

### その他の質問

- PC を再起動してもこの問題は再発する：はい
- NVDA 日本語版 2019.1.1jp でも再現する：いいえ

### 備考

- 筆者環境ではInternetExplorer、Firefox、MicrosoftOffice Wordで上記の現象を確認した。
- 正確なバージョンはわからないが、検索ダイアログの検索文字列の入力コントロールがコンボボックスになったバージョンから上記の現象が発生しており、エディットボックスであれば発生しない。

**Comment by nishimotz** [comment]
報告ありがとうございます。

本家版 beta3 よりも新しいビルドで下記を確認しました。

* 2019.1.1 : 検索履歴なし。Esc を押すと期待通りに動作する
* nvda_snapshot_beta-18133,b29acb42 : 検索履歴あり。Esc を押すと IME のキャンセルではなく、ダイアログが閉じてしまう

確認した環境
Windows 10 version 1903
Microsoft IME
Internet Explorer のブラウズモード

**Comment by nishimotz** [comment]
本家に報告しました

https://github.com/nvaccess/nvda/issues/9954

**Comment by nishimotz** [comment]
技術的に検索履歴の修正をすることが難しいため、
検索履歴そのものを 2019.2 でキャンセルして、
この問題を回避することになりました。

ユーザーガイドの翻訳などに影響がおよぶため、
本家 2019.2 のリリースがさらに遅れることになりそうです。

この件は韓国語や中国語のIME対応にも影響する不具合だったそうです。
本家に報告できてよかったと思います。

**Comment by nishimotz** [comment]
本家版はおそらく rc2 になりますが、
日本語版 2019.2jp-beta-190802j にて検索履歴がないバージョンに戻しました。
