### ISSUE TITLE
Windows10 1903での使用時の音量と明るさの報告機能にオンオフ機能が欲しい

### ISSUE THREAD

**Issue by TetsuroOkane** [nvdajp/nvdajp#215]
### 背景（不満や不便なこと）
NVDA2019.1.1jpで音量のや画面の明るさを変更した時にWindows10 1903では常時そのレベルを報告するように改善されているが、全文読みなどで読み上げている最中に操作すると読み上げが途切れ、音量を読み上げ始めるのが不便。
最新ベータ版(190720b)に更新したところ、報告その物がなくなり、無音時に音量変化がわかりません。
また画面の明るさの報告も併せて報告されなくなり、全盲者が明るさ0で使用している場合、文字認識機能が使えないことがあり、不具合と誤認される可能性があります。

### 提案したい機能や方法
書式とドキュメント情報の各要素の報告のチェックボックスのように、必要に応じて音量や明るさの報告のオンオフができるようになっているとありがたいです。(ロービジョンでは明るさもわかる為、不要な人もいると思われる為)
また、読み上げ中に音量を変化させた場合は感覚的にわかるため、音量の数値の報告はなく、無音時に音量を変化させた場合にのみ数値を読み上げるように改善されると、とてもわかりやすいです。
要約すると
・音量　読み上げ中は報告しない　無音時は報告する　または　音量の報告のオンオフ機能の搭載
・画面の明るさ　常時報告を維持またはオンオフ機能の搭載
となります。
### 考慮した代案があればお書きください
NVDAヘルプデスク版アドオン使用時はアドオン内の設定メニューで「メディアキー読み上げする」にチェックを入れていると、音量を上げるまたは下げると読むため、最新ベータ版との組み合わせでも無音時の操作でも音量の確認が可能です。
但し、NVDAヘルプデスク版アドオンには明るさの報告機能がない為、明るさの報告機能はNVDA本体に必要な機能と言えます。

### 関連する情報があればお書きください
「 Windows 10 May 2019 アップデートにおいて、ファイルエクスプローラーにフォーカスがあるときにハードウェアボタンで音量を変更すると不適切に頻繁に音量の通知をしていた不具合を修正しました。 (#9466)」に関連していると思われます。

**Comment by nishimotz** [comment]
音量の報告が日本語ベータ版でなくなったとしたら、
要望ではなく不具合として報告をお願いします。

あとで調べてみます。

**Comment by nishimotz** [comment]
確認しましたが、本家版でも日本語版でも音量の変更の通知の不具合はないと思います。

ただ、私の「最新情報」の翻訳がわかりにくかったので、確認した仕様などを整理します。

* Windows 10 version 1903 では、ハードウェアボタンで音量を変更したときの通知は、ファイルエクスプローラーにフォーカスがある場合にのみ行われる。別のアプリにフォーカスがある場合には通知は行われない。
* NVDA 2019.2 では、ファイルエクスプローラーにフォーカスがある場合の通知を聞き取りやすくなった。つまり、音量を上げるボタンや下げるボタンを何度も押したときに、最後の値だけが聞こえるようになった。
* これらの仕様について、本家版と日本語版を比較して、特に違いは見つかっていない。
* ファイルエクスプローラーにフォーカスがない場合には音量の通知をしない仕様なので、全文読み上げの途中で音量通知が行われることなどを、本家は想定していないのではないか。
* Windows 10 version 1809 までは音量の通知の仕様が異なっていた可能性がある。（別の API が使われていたため）

**Comment by TetsuroOkane** [comment]
調査ありがとうございます。
音量については、現在の仕様で大きな問題は無い気もするので、明るさの報告のみを不具合として報告しなおしました。
音量についてはこちらでももう少し、最新のベータ版を使い込んで改善が必要なように感じたら追加で報告させていただきます。

**Comment by nishimotz** [comment]
明るさの報告も、私が確認した限りでは、ファイルエクスプローラーにフォーカスがある場合のみ通知される、というのが現在の NVDA の仕様で、不具合ではなさそうに思います。

文字認識機能と画面の明るさは私はまだ検証できていませんが、関係があるとしたら、不便なので改善してほしい、という要望はできると思います。

**Comment by nishimotz** [comment]
NVDAヘルプデスク版アドオンを入手していないので判断できませんが、もしメディアキーの読み上げについて、有益な改善がうまく実装できているのであれば、NVDA 本家版の開発に貢献していただきたいです。
本家に提案して、何らかの理由で却下されたら、それはそれで有益な情報が得られるはずです。
