### ISSUE TITLE
Windows10バージョン2004における日本語変換の詳細読み対応

### ISSUE THREAD

**Issue by yama3nomori** [nvdajp/nvdajp#220]
### 問題の再現手順

1. メモ帳などのエディタを開く
2. 半角キーを押して日本語変換を有効にする
3. "あさ"　と入力してスペースキーを繰り返し押す

### 期待されること
漢字変換の詳細読みが行われる

### 実際に起きること
2番目以降の詳細読みがされず、番号と熟語のみがアナウンスされる

### システム構成
NVDA 日本語版 2019.2jp-beta-190720d

インストール環境
Windows 10 Home Insider Preview バージョン 1903 (OS ビルド 18922.1000) 日本語環境

### その他の質問

PC を再起動してもこの問題は再発します。

NVDA 日本語版 2019.1.1jp では発生していません。

**Comment by nishimotz** [comment]
ビルド 18922 は正式なバージョン 1903 ではないので、タイトルを変更しました。

Insider Preview で日本語 IME の実装が変わることは把握していますが、
現在の Insider Preview は2020年春に向けた開発版だと理解しております。
既知の問題として、もうすこし時間をいただければ幸いです。

Windows 日本語 IME の実装方法は最近大きく変化していて、
NVDA 側の対応は、他の言語の IME に関する作業と重複または
衝突する可能性が高くなっています。
絵文字パネルやクラウドクリップボードも IME 対応と衝突します。

このような状況を踏まえて、今後、日本語IME対応は、
必要な作業をなるべく本家版に提案していきたいと考えています。

**Comment by nishimotz** [comment]
関連しそうなチケット

Windows 10 ビルド 18277 日本語IME #122
Windows + V クリップボード履歴の読み上げ #211

**Comment by nishimotz** [comment]
暫定的に 2019.1.1jp の状態に戻していただく方法ですが、
scratchpad を有効にして、appModules に旧バージョンの

windowsinternal_composableshell_experiences_textinput_inputapp.py

を置いてください。
以下、直接 raw file URL

https://raw.githubusercontent.com/nvdajp/nvdajp/jp2019.1/source/appModules/windowsinternal_composableshell_experiences_textinput_inputapp.py

クリップボード履歴読み上げができなくなる不具合があるため
2019.2jp では元に戻すことにしました。

**Comment by yama3nomori** [comment]
対応策をありがとうございます。
変換の詳細読みがされるようになりました。

**Comment by yama3nomori** [comment]
インサイダープレビューの設定を確認してみたところ「リリースプレビュー」になっていました。
ですので、このバージョンは今年の秋にリリース予定の物のようです。

**Comment by nishimotz** [comment]
本家版に最低限の実装を提案するとこうなるというメモ。
このコードは本家 alpha 18399 と Windows Insider build 18956 で、
本家版の従来の日本語IME対応に相当する動作を確認。
だがクリップボード履歴と絵文字パネルの対応を捨てた状態になっている。

```
# windowsinternal_composableshell_experiences_textinput_inputapp.py
import appModuleHandler
import api
import speech
import braille

class AppModule(appModuleHandler.AppModule):

	def event_UIA_elementSelected(self, obj, nextHandler):
		s3 = obj.parent.parent.parent.UIAElement.cachedClassName + ":" + obj.parent.parent.parent.UIAElement.cachedAutomationID
		s2 = obj.parent.parent.UIAElement.cachedClassName + ":" + obj.parent.parent.UIAElement.cachedAutomationID
		s1 = obj.parent.UIAElement.cachedClassName + ":" + obj.parent.UIAElement.cachedAutomationID
		s  = obj.UIAElement.cachedClassName + ":" + obj.UIAElement.cachedAutomationID
		if (
			s3 == "Windows.UI.Core.CoreWindow:" and
			s2 == "pane:IME_Candidate_Window" and
			s1 == "ListView:IME_Candidate_Window" and
			s == "ListViewItem:"
		):
			speech.cancelSpeech()
			api.setNavigatorObject(obj)
			speech.speakSpelling(obj.name, useCharacterDescriptions=True)
			braille.handler.message(braille.getBrailleTextForProperties(name=obj.name, role=obj.role, positionInfo=obj.positionInfo))
		nextHandler()
```

**Comment by nishimotz** [comment]
本家に報告というか問題提起をしました
https://github.com/nvaccess/nvda/issues/10093

**Comment by nishimotz** [comment]
下記の組み合わせで状況が変わっていないので、対応を検討します。

* Windows 10 バージョン 2004 ビルド 19041.153
* NVDA 2020.1jp-beta-200407t

**Comment by nishimotz** [comment]
以下のバージョンで暫定的な対応を行いました。

* 2020.1jp-beta-200410w
* jpalpha_200411j

作業メモ

* 基本的にはナビゲーターオブジェクトの制御と、不要なイベントの無視だけを追加している
* 絵文字パネルとクリップボード履歴と同じ appModule であるが、これらは引き続きちゃんと動作しているはず
* 日本語版では appModule ではなくコンポジション側で読み上げ処理を行っているので、モジュール側は動作を抑止するだけでよい
* 本家版に変更を提案する場合は、モジュール側で出力処理を行う必要がある
