### ISSUE TITLE
ブレイルメモ使用時のキーバインディングの不具合

### ISSUE THREAD

**Issue by yncat** [nvdajp/nvdajp#232]
### 問題の再現手順

1.  ブレイルメモをNVDAに接続する。
2. テキストエディターを開く。
3. ブレイルメモから何らかの文字列を入力後、ブレイルメモのスペースキー、または、ブレイルメモのリターンキーを押す。

### 実際に起きること
スペースキーを押すと、改行が入力される。
リターンキーを押すと、バックスペースキーがエミュレートされて、直前の文字が消える。

### 期待されること
スペースキーを押すと、スペースが入力される。
リターンキーを押すと、改行が入力される(展示入力を返還して、リターンキーを押すNVDAのアクションがトリガーされる)。

### システム構成

NVDA 日本語版 2019.2.1jp-beta-191004q

Windows 10 バージョン 1903 (OS ビルド 18362.418)

KGS ブレイルメモ BM32

### その他の質問

BM32以外の機種では確認していないが、同様の動作になると考えられる。
入力ヘルプで確認すると、リターンキーがどっと7、スペースキーがどっと8になっている(これはたぶんSDKの仕様上は正しいので、NVDA側のキーバインディングを探すときの FYI です)

**Comment by nishimotz** [comment]
点字ディスプレイドライバーは自動選択でお使いですか？

**Comment by yncat** [comment]
自動では認識しないようだったので、ブレイルメモ(experimental)を使用しています。

**Comment by nishimotz** [comment]
experimental ドライバーはキーバインドがすこし違う仕様になっています。
（2級点字入力の検証用）
kgs ドライバーに切り替えていただくことは可能でしょうか？

**Comment by yncat** [comment]
KGS ドライバーに切り替えたところ、期待する動作になりました。先に experimental を選んでしまって、こちらのドライバーを見落としていたようです。ありがとうございました！

**Comment by nishimotz** [comment]
ありがとうございます。
以下が気になります。またどこかの機会に。

* そちらの環境で自動認識できていない理由
* 日本の点字ユーザー向けに漢点字などの文字入力用キーバインドをどうすればいいのか
