### ISSUE TITLE
你(なんじ)が無音になる

### ISSUE THREAD

**Issue by TetsuroOkane** [nvdajp/nvdajp#233]
### 問題の再現手順

1.  Chrome を開く
2. www.google.com を開く
3. 「你は你好にも使われています」と入力する
4. 変換時はコードのみ読まれ確定後は你のみが無音になる

問題の再現に必要なファイルは ZIP 形式のアーカイブで添付

### 実際に起きること

「你」が無音になるまたは無視される

### 期待されること

「你」は「なんじ」、「你好」は「ニーハオ」と読まれる

### システム構成

NVDA 日本語版 2019.2.1jp インストール環境

Windows 10 バージョン 1903 日本語環境

### その他の質問

PC を再起動してもこの問題は再発する
はい

NVDA 日本語版 2017.3jp でも再現する
はい

#### 他のバージョンの NVDA と比較している場合はその結果
最新ベータ版やアルファ版でも発生します。
音声エンジンはJTalk、OneCore共に発生します。

**Comment by nishimotz** [comment]
U+4F60
你

**Comment by nishimotz** [comment]
波ダッシュ対応
https://github.com/nvdajp/nvdajp/issues/440
と関連するので検討しています。

ただし「你好」を「ニーハオ」と読む件はわけて検討します。

**Comment by nishimotz** [comment]
文字説明はできるようになった。
なめらか読みさせると当該文字が無視される。

**Comment by nishimotz** [comment]
まず本家版ではこうあるべき。
日本語音声エンジンが読まないことが自明な文字：
なめらか読みさせるには source/locale/ja/symbols.dic にレベル none で登録する。
文字説明させるためには source/locale/ja/characterDescriptions.dic に登録する。

**Comment by nishimotz** [comment]
「你は你好にも」
は「ナンジはナンジヨシミにも」などと読んでしまう。
これを回避するには読み上げ辞書で「你好」を登録してもらわなくてはならない。

整理すると

* 音声エンジンがある文字を読むか読まないかをNVDAが知ることができない
* 文字コードから判断して特定の漢字には強制的に決まった読みを与えている
* これは記号辞書で「読み上げレベルにかかわらず読む」というレベル設定 (none) を使って実現している

**Comment by nishimotz** [comment]
2024.1jp-beta-240327l
