### ISSUE TITLE
JTalk の「自動言語切換」対応を無効化

### ISSUE THREAD

**Issue by riku22** [nvdajp/nvdajp#244]
# 問題の再現手順

1. ユーザー名にマルチバイト文字が含まれる環境でNVDA日本語版をインストールする、もしくはマルチバイト文字が含まれるフォルダにポータブル版を作成する。
※今回は「E:\テスト\nvda」にポータブル版をインストールしました。
2. NVDAを起動する。
3. NVDA制御キー+Ctrl+Sで「音声エンジンの選択」ダイアログを開く。
4. JTalkを選択し、Enterキーを押すと、NVDAが強制終了する。
この際、特にログ等は出力されていない。

### 実際に起きること

JTalkを選択して、Enterキーを押すと、NVDAが強制終了する。

### 期待されること

JTalkが正常に読み込まれる。

### システム構成

- NVDA日本語版 jpalpha_191206l ポータブル
- Windows10 1909 64ビット

### その他の質問

- PC を再起動してもこの問題は再発する：はい

#### 他のバージョンの NVDA と比較している場合はその結果

NVDA日本語版 2019.2.1JPでも再現します。

**Comment by nishimotz** [comment]
報告ありがとうございます。
さらに前のバージョンで起きていたかどうか、
もしお分かりだったら教えてください。

**Comment by riku22** [comment]
手元に残っていたインストーラーでポータブル版を創って調べてみたところ、下記のような結果になりました。

- NVDA 2019.1.1JPまでは正常にJTalkが読み込まれ動作する
- NVDA 2019.2JPでは報告した問題の現象が発生する。

**Comment by nishimotz** [comment]
調査に取り掛かっています。すみませんがもう少しお待ちください。

**Comment by nishimotz** [comment]
「自動言語切換」で使っている espeak の問題のようです。
本家に関連するバグ報告があったので、もう少し調べてみます。

**Comment by nishimotz** [comment]
本家 10607 
NVDA 2019.3Beta1 crashes when setting synthesizer to eSpeak NG if path name contains accented character

スナップショットがありますがまだ解決していません。
https://ci.appveyor.com/project/NVAccess/nvda/builds/29581261/artifacts

暫定的に JTalk の「自動言語切替」を無効にしてみます。

**Comment by nishimotz** [comment]
以下のバージョンで一時的に JTalk から eSpeak NG を使わないようにしました。

nvda_jpalpha_191222t.exe
nvda_2019.3jp-beta-191222s.exe

本家の eSpeak NG 対応のバグが修正されたら元に戻そうと思います。

**Comment by nishimotz** [comment]
本家 2019.3 でこの不具合が修正されそうにないので、
2019.3jp では JTalk の多言語対応を無効化します。
残念ですがご了承ください。
