### ISSUE TITLE
NVDA RemoteアドオンにWindows Defenderにより脅威が検出される

### ISSUE THREAD

**Issue by minakononogaki** [nvdajp/nvdajp#245]
アドオンについてなので、迷いましたが上げさせていただきます。
NVDA Remoteアドオン

### 問題の再現手順
1. Chrome, Edge, Internet Explorerなど、Webブラウザを開く
2. NVDA remoteバージョン2.2のダウンロードをする
3. Windows Defenderにより脅威が検出され（トロイの木馬）、ダウンロードが出来ない

または、
1.すでにダウンロードされているNVDA Remoteバージョン2.2についてWindows Defenderでスキャンを行なう。
2. 脅威が検出される（トロイの木馬）

### 実際に起きること
Windows Defenderにより脅威が検出される

### 期待されること
脅威が検出されない

### システム構成
WIndows 10 1903
NVDA 2019.2.1jpインストール環境
WIndows Defender 悪意のあるソフトウェアの削除ツールx64 2020年1月 (KB890830) インストール済

### その他の質問
PCを再起動してもこの問題は再発します。
NVDAを起動していなくても起こります。
久しぶりに起動したパソコンで、WIndows Defender 悪意のあるソフトウェアの削除ツールx64 2020年1月 (KB890830) がインストールされる前は、脅威として検出されませんでしたので、このツールがあるかないかで変わっている感じがしています。

**Comment by minakononogaki** [comment]
Windows Defenderにより脅威が検出されたファイル名とダウンロード元について、Windows Defenderの画面でいったん許可をすると、同じダウンロード元からダウンロードすることが出来ました。また、インストールも出来、NVDAメニュー、ツール、リモート、オプションで、NVDAリモートのオプション画面を表示することが出来ました。

**Comment by nishimotz** [comment]
本家 nvda-addons でも議論されていますが、実際には脅威ではないとされています。
Microsoft には情報提供されているようです。
https://nvda-addons.groups.io/g/nvda-addons/topics

**Comment by nishimotz** [comment]
NVDA 2019.3 に対応する Remote 2.3 がリリースされています。

https://nvdaremote.com/download/

もし Defender 対応の問題が解決していたらお知らせください。

**Comment by minakononogaki** [comment]
NVDA Remoteの2.2と2.3、両方のダウンロードで、Windows Defenderで脅威が検出されませんでした。
特に脅威の例外と指定していない方のWindows10パソコンです。
Windows Defender Antivirusのセキュリティインテリジェンス更新プログラムが1.309.886.0というのが最後に入っています。
悪意のあるソフトウェアの削除ツールの2月分は今ダウンロード待ちになっている状態です。

**Comment by nishimotz** [comment]
最近のバージョンで問題が起きていたらまたお知らせください。
