### ISSUE TITLE
default color の翻訳

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#246]
NVDA 2019.3 の時点で default color は「標準色」と翻訳されています。

例によってマイクロソフトのランゲージポータルによると
「既定の色」
または
「既定色」
と翻訳されています。

**Comment by KatsutoshiTsuji** [comment]
「規定の色」への翻訳テキストの変更、良いと思います。

**Comment by nishimotz** [comment]
#221 にまとめます。
