### ISSUE TITLE
OneCore音声で全文読み中に頻繁に停止する

### ISSUE THREAD

**Issue by TetsuroOkane** [nvdajp/nvdajp#247]
### 問題の再現手順
1. 音声エンジンをWindows OneCore音声またはMicrosoft Speech API Version5のHaruka Desktopにする
2. メモ帳やOutlook(届いたメールの本文)などを開く
3. 以下の例文をメモ帳やOutlook(自分宛に送付)などで開いた状態にする。
例： 「この番組は
ざくろの森音楽研究所制作、
オカテツ電子研究所の提供でお送りしました。
来週はゲストをお迎えしての生放送です。

お便りはEメールまたはお葉書でお送りください。
皆様からのお便りお待ちしています。」
※実際にメールで問題が起きた時の文面はテレビ番組の内容につき、著作権保護の為架空の番組に内容を変えています。
4. NVDA+↓(NVDA+A)で全文読みさせると、数行読み上げて停止する。

問題の再現に必要なファイルは ZIP 形式のアーカイブで添付

### 実際に起きること

「提供でお送りしました。」で停止し、再度全文読みさせると次は「お葉書でお送りください。」の直後で読み上げが停止する。

### 期待されること

文書の末尾まですべて読み上げる

### システム構成

NVDA 日本語版 2019.3jp-beta-200121k インストール環境
(アルファ版 200114nポータブル環境でも発生)

Windows 10 バージョン 1909 日本語環境

Microsoft Office 2019

### その他の質問

PC を再起動してもこの問題は再発する
はい

NVDA 日本語版 2017.3.jp でも再現する
いいえ

#### 他のバージョンの NVDA と比較している場合はその結果
最新のアルファ版とベータ版で発生を確認しました。
2019.2.1jpとそれ以前では再現しません。

#### 音声エンジンを変えての再現性
JTalk　止まらない
OneCore Haruka、Ichiro、Ayumi共に止まる
ProTALKER(SAPI4)　止まらない
SAPI5　ドキュメントトーカー(JAWS付属品)止まらない
SAPI5　Haruka　Desktop　止まる

#### ナレーターでのテスト
ナレーターではAyumi、Haruka、Ichiro共に全文を読み上げています。

**Comment by nishimotz** [comment]
報告ありがとうございます。いただいた内容はこちらでも再現できています。

本家版と動作を比較しました。
https://www.nvaccess.org/post/nvda-2019-3beta2-now-available-for-testing/

本家 2019.3beta2 + OneCore + メモ帳で、ちゃんと行単位でテキストカーソルが移動して、
最後の行まで読み続けました。

日本語版が変更した処理で、この挙動に影響を与えるとしたら、

「すべて読み上げ」で改行をまたぐ単語を適切に読み上げない

https://osdn.net/projects/nvdajp/ticket/33823

だと思います。

2019.3 対応作業 #219

```
NVDAは、コミュニティーの援
助によりNV Accessが開発しました。
```

現在も本家版 2019.3beta2 では「援助」を正しく読めない、
日本語ベータ版では（途中で止まらなければ）「エンジョ」と読める、
という状況です。

もういちどこの件で書き換えた処理を確認したいと思います。

**Comment by nishimotz** [comment]
続きは #219 で進捗報告します

**Comment by nishimotz** [comment]
nvda_2019.3jp-beta-200128m.exe
に更新しました。

「「すべて読み上げ」で改行をまたぐ単語を適切に読み上げない」
に関する日本語版の独自処理を削除しています。

本家版 2019.3beta2 と同様に「すべて読み上げ」を行うことを
OneCore で確認しています。

これから日本語アルファ版も同様に更新します。

この件はこれでクローズさせていただき #219 で
「日本語の改行をまたぐ単語」の作業を再検討させてください。
