### ISSUE TITLE
2019.3.1jp - チェックボックスのオン/オフの変更を読み上げない

### ISSUE THREAD

**Issue by msuzu15** [nvdajp/nvdajp#253]
### 問題の再現手順

1. NVDA+Nを押してNVDAメニューを開き、設定→設定と選択。
2. カテゴリとして、例えば「書式とドキュメント情報」を選択、その後、Tabキーを押して、チェックボックスで設定する任意の項目（例えば「フォント名」）にフォーカスを移動する。
3. フォーカスが移動した時点で、「チェックなし」あるいは「チェック」などと現在のボックスの状態が読み上げられる。
4. チェックボックスの状態を変更するために（チェックボックスのオンとオフを切り替えるために）、スペースキーを押す。

### 実際に起きること

上記手順4.の時点で、チェックボックスの状態の変化が報告されない。

### 期待されること

スペースキーを押すごとに、「チェック」、「チェックなし」などと状態の変更の結果が読み上げられる。

### システム構成

NVDA 日本語版 2019.3.1jp ポータブル版
Windows 10 Enterprise バージョン 1803 (OS ビルド 17134.1184) 英語環境

### その他の質問

PC を再起動してもこの問題は再発する。
NVDA 日本語版 2019.2.1jp では再現しない。
音声エンジンはJTalkを使用しています。

#### 他のバージョンの NVDA と比較している場合はその結果

NVDA 日本語版 2019.2.1jpではこの現象は再現しない。
（スペースキーを押すごとに「チェック」、「チェックなし」などと状態の変化を読み上げる）

**Comment by nishimotz** [comment]
ご報告ありがとうございます。
私は Windows 10 バージョン 1909 でしか試していませんが、
報告いただいた状況を再現できていません。

JTalk 以外の音声エンジンで試していただくことは可能でしょうか？

キーボード設定「入力文字の読み上げ」はどういう設定になっているでしょうか？
入力文字を読み上げる設定になっている場合には、
スペースキーを押すごとに
「スペース、チェック」
「スペース、チェックなし」
が期待される読み上げだと思いますが、そちらの状況はいかがでしょうか？

**Comment by msuzu15** [comment]
自分のところではJTalk以外では日本語読み上げができないため、
いったんNVDAの言語を英語に切り替えてから音声エンジンをWindows OneCore音声（音声はデフォルトのMicrosoft David）を選択して試したところ、スペースキーを押すごとに"Space, checked", "Space, not checked"と読み上げられました。
「入力文字の読み上げ」のチェックボックスは、当初からオンになっています。

**Comment by nishimotz** [comment]
他のご報告と合わせて推測なのですが、
オーディオ出力デバイスに近い処理の不具合で、
読み上げるたびにオーディオ出力の後半が欠落する、
といった現象ではないかと思います。
なにか特殊なハードウェア環境をお使いでしょうか？

**Comment by msuzu15** [comment]
使用しているパソコンはLenovo ThinkPad T470pで、特にオーディオ/サウンドデバイスの変更はしていません。

**Comment by msuzu15** [comment]
ちなみに、スピーチビューアでは、以下のように「チェック」、「チェックなし」が記録されています。

フォント名(F)  チェックボックス  フォーカス  チェックなし  Alt+f
スペース
チェック
スペース
チェックなし

しかし、音声としては、「チェック」や「チェックなし」は読み上げされません。

また、他の環境として、AzureにあるWindows Server 2012 R2（英語版）の仮想マシンにリモートデスクトップで接続してリモートオーディオを有効にしてサーバーのサウンドをローカルPCに返す形でNVDA 2019.3.1jpを起動して確認したところでは、状況は同じでした（「チェック」、「チェックなし」は音声としては読み上げられない）。

**Comment by msuzu15** [comment]
スピーチビューアでは記録が2行に分かれるが音声読み上げは一度に行われる箇所で今回のような現象が発生していると思われます。

例えば今回の現象の場合、スピーチビューアの記録は以下の通りです。

1:スペース
2:チェック
3:スペース
4:チェックなし

チェックボックス上でスペースキーを一度押すと本来であれば「スペース、チェック」と一度に読み上げされますが、スピーチビューア上では上記のように1行目と2行目に分かれて記録されて、2行目が音声で読み上げされません。
チェックボックス上でもう一度スペースキーを一度押すと本来であれば「スペース、チェックなし」と一度に読み上げされますが、スピーチビューア上では上記のように3行目と4行目に分かれて記録されて、4行目が音声で読み上げされません。

**Comment by nishimotz** [comment]
「JTalk以外では日本語読み上げができない」とのことですが、
eSpeak NG でどうなるか比較していただくことは可能でしょうか？
（日本語の発音がとても悪いので恐縮ですが）

**Comment by msuzu15** [comment]
eSpeak NGでは、チェックボックス上でスペースキーを押すごとに「スペース、チェック」、「スペース、チェックなし」と読み上げされます。

**Comment by nishimotz** [comment]
ご報告ありがとうございます。
JTalk に問題がありそうです。
引き続き調査させてください。

**Comment by msuzu15** [comment]
音声をtohoku-f01にしてNVDAを再起動したら、この現象は発生しなくなりました。
しかし、その後音声をliteやmeiにすると、この現象が再現します。

**Comment by nishimotz** [comment]
こちらで不具合を再現できました。ありがとうございます。

**Comment by nishimotz** [comment]
JTalk の不具合対応のテスト版です。

http://s.nvda.jp/nvda_2019.3.1jp-beta-200214w.exe

ご確認いただけると助かります。

**Comment by msuzu15** [comment]
ありがとうございます。#253、#254、#256が解消されていることを確認しました。
