### ISSUE TITLE
2019.3.1jp - NVDA+Tabでテキストボックスの内容を読み上げない

### ISSUE THREAD

**Issue by msuzu15** [nvdajp/nvdajp#254]
### 問題の再現手順

1. Windowsキー+Rで「ファイル名を指定して実行」ダイアログを開く。
2. テキストボックス内に、例えば"notepad"とタイプする。
3. NVDA+Tabキーを押す。

### 実際に起きること

手順3.で、「エディット  フォーカス  Alt+o」としか読み上げられない。

### 期待されること

「エディット  フォーカス  Alt+o  notepad 選択」と読み上げられる。

### システム構成

NVDA 日本語版 2019.3.1jp ポータブル版
Windows 10 Enterprise バージョン 1803 (OS ビルド 17134.1184) 英語環境

### その他の質問

PC を再起動してもこの問題は再発する。
NVDA 日本語版 2019.2.1jp では再現しない。
音声エンジンはJtalkを使用しています。
同様の現象はGoogle Chromeでも発生します。
（Chromeを開いて、Ctrl+Lでアドレスバーに移動して、URLをタイプ後NVDA+Tabを押しても入力したURLを確認することができない）

#### 他のバージョンの NVDA と比較している場合はその結果

NVDA 2019.2.1jpでは「エディット  フォーカス  Alt+o  notepad 選択」と読み上げられます。

**Comment by nishimotz** [comment]
私の環境では再現できていません。
JTalk で話者や音声の速さを変更すると、何か違いがあるでしょうか？

**Comment by msuzu15** [comment]
上記テストは話者をmeiにして行いましたが、話者をlightやtohoku001に変えたり、高速読み上げのチェックボックスのオン/オフを切り替えたり速さを変えたりしても状況は変わりません。

**Comment by msuzu15** [comment]
なお、「名前を指定して実行」ダイアログのテキストボックス上でNVDA+Tabキーを押したときのスピーチビューアの記録は以下のようになっています。

1:エディット  フォーカス  Alt+o
2:notepad

音声では、1行目だけが読み上げられて2行目は読み上げされません。

**Comment by msuzu15** [comment]
音声をtohoku-f01にしてNVDAを再起動したら、この現象は発生しなくなりました。
しかし、その後音声をliteやmeiにすると、この現象が再現します。
