### ISSUE TITLE
2019.3.1jp - JTalkで「大文字にビープ音を付ける」が有効にならない

### ISSUE THREAD

**Issue by msuzu15** [nvdajp/nvdajp#256]
### 問題の再現手順

1. NVDA+Nを押してNVDAメニューを開き、設定→設定を選択。「音声」カテゴリを選択し、音声エンジンにJTalk、音声にmeiを選択する。「大文字にビープ音を付ける」のチェックボックスをオンにする。
2. メモ帳を開く。
3. Shiftキーを押しながらAキーを押して、大文字のAを入力する。
4. 3.の後、左矢印キーを押して、カーソルを入力した文字の左側に移動する。

### 実際に起きること

手順3.では「エイ」、手順4.では「エー」とだけ読み上げされる。

### 期待されること

手順3.では「ピッ」という短いビープ音が鳴った後に「エイ」、手順4.では「ピッ」という短いビープ音が鳴った後に「エー」と読み上げされる。

### システム構成

NVDA 日本語版 2019.3.1jp ポータブル版
Windows 10 Enterprise バージョン 1803 (OS ビルド 17134.1184) 英語環境

### その他の質問

PC を再起動してもこの問題は再発する。
NVDA 日本語版 2019.2.1jp では再現しない。

#### 他のバージョンの NVDA と比較している場合はその結果

NVDA 2019.2.1jpではこの現象は再現しません。

**Comment by nishimotz** [comment]
こちらでは「大文字にビープ音を付ける」は JTalk で動作しています。
ですが、他の音声エンジンと比べると、ビープ音が鳴るタイミングが少し遅いようです。

確認ですが、
「大文字にビープ音を付ける」をオンにしたあとで、
「適用」または「OK」を押して変更を反映させておられますか？

**Comment by msuzu15** [comment]
「適用」や「OK」は押していますが変わりません。

**Comment by msuzu15** [comment]
実際の内部構造を知らないのであくまで推測ですが、以下のようなことはないでしょうか？

1) NVDA 2019.3.1jp内では、はじめにアルファベットを読み上げる命令（「エイ」とか「ビー」とか）が先に書いてあって、その後に大文字の場合に短いビープ音を鳴らす命令が書いてある。ただし、この2つは並列的に同時に実行されるようになっている。
2) 西本様の環境では、この2つが並列同時実行でなく、直列に順番に実行される（つまり「エイ」とか「ビー」とかアルファベットを読み上げてから、ビープ音が鳴る命令が実行される）。そのため、他の音声エンジンと比べてビープオンが遅いタイミングで聞こえる。
3) 私の環境では、この2つを並列同時実行しようとするが、先に書かれているアルファベットを読み上げる命令だけが実行され、後に書いてあるビープ音を鳴らす命令は何らかの原因で実行されない（命令が無視される、先の命令とかぶって実行されない、など）。

**Comment by msuzu15** [comment]
音声をmeiからtohoku-f01に変更して再起動したら、ビープ音が鳴るようになりました。
しかし、ビープ音の鳴るタイミングが、アルファベットを読み上げた後に鳴るタイミングになっています。
NVDA 2019.2.1jpではビープ音が鳴ってからアルファベットを読み上げていますし、
NVDA 2019.3.1jpでもJTalk以外の音声エンジン（Windows OneCore等）を選択した場合は、ビープ音が鳴ってからアルファベットの読み上げになっています。
NVDA 2019.3.1jpで音声エンジンにJTalkを選択した場合でも、ビープ音が鳴ってからアルファベットの読み上げがされるようにしてほしいです。
また、JTalkで音声をtohoku-f01以外（lite、mei等）に選択した場合は今回の現象が発生するので、こちらも解消していただきたいです。
