### ISSUE TITLE
━が複数回読まれるとNVDAがクラッシュする

### ISSUE THREAD

**Issue by KatsutoshiTsuji** [nvdajp/nvdajp#260]
添付ファイルには「━」(よこだいけいせん)が書かれた行が複数行あります。
手元では「━」が24個並んだ行を読ませようとしたときにNVDAが動作を停止しました。

### Steps to reproduce:

1. メモ帳などで添付のテキストファイルを開く
2. ファイルの先頭から順番に下矢印キーを押してファイルの内容を読み進める
3. 「━」が24個書かれた行に移動するとNVDAが動作を停止する

### Actual behavior:

NVDAが動作を停止する

### Expected behavior:

他の行と同じようにNVDAが停止しないまま行を読み進められる

#### NVDA installed/portable/running from source:

インストール済みのNVDA及びポータブル版で問題が再現する

#### NVDA version:

2019.3.1jp

#### Windows version:

10.0.18363 workstation

#### Name and version of other software in use when reproducing the issue:

- Notepad++ V7.8.4
- Microsoft Teams バージョン 1.3.00.3564

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

- NVDA 2019.1.1jpではこの問題は再現しない
- NVDA 2019.3.1ではこの問題は再現しない

#### If addons are disabled, is your problem still occuring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

No
[crash_nvda_with_symbol_test.txt](https://github.com/nvdajp/nvdajp/files/4322741/crash_nvda_with_symbol_test.txt)

**Comment by nishimotz** [comment]
音声を JTalk にした場合に現象を再現できました。
報告ありがとうございます。

**Comment by nishimotz** [comment]
確認したら U+2501 という文字でした。

BOX DRAWINGS HEAVY HORIZONTAL
https://www.fileformat.info/info/unicode/char/2501/index.htm

**Comment by nishimotz** [comment]
JTalk の中で mecab のバッファがオーバーランしているようです。
根本的な対策をしようと思ったのですが、
ひとつの形態素の文字数が無限に長くなることはないとわかったので、
バッファサイズを2倍にすることで対応したいと思います。

**Comment by nishimotz** [comment]
2020.1jp-beta-200328p にて修正しました。
