### ISSUE TITLE
Zoomの入退室者の自動通知やチャットの自動通知のオンオフが出来る機能が欲しい

### ISSUE THREAD

**Issue by TetsuroOkane** [nvdajp/nvdajp#267]
### 背景（不満や不便なこと）
・Zoomを使用している際に、電波状況が不安定な参加者がいる場合、頻繁に「誰々が参加しました」、「誰々が退出しました」と読まれてしまい、チャット等の入力が中断されてしまう。
・上記の状況でノートを取る為に、テキストエディターを使用していると、フォーカスがテキストエディターにあっても通知が読まれ続け、入力が中断される。
・大勢の人の出入りがある場合やチャットで回答を書かなければならない会議やウェビナーで入力を中断する形で通知が読まれてしまい、他の人が入力を終わるまで、入力を進められない。

### 提案したい機能や方法
JAWS(2019及び日本未発売の2020)ではAlt+WindowsでZoomの通知をオンオフする機能が実装されているので、アドオンでも良いので、同等の機能を提供して欲しい。
可能であれば、入退室の通知とチャットの通知を分けてオンオフできると良い。

### 考慮した代案があればお書きください
聴いているだけの会議やウェビナーの場合、NVDA+Sで読み上げ無しにするか、スリープモードを使用して凌いだ。

### 関連する情報があればお書きください

JAWS 2019 and 2020
    Alt+Windows enables or disables event alerts, such as when someone has left the meeting room

https://unimelb.edu.au/accessibility/tutorials/zoom/zoom-meetings-and-jaws
より抜粋

**Comment by nishimotz** [comment]
NVDAのオブジェクト表示設定の以下が関係あるかもしれませんが、いかがでしょうか？

* ツールチップ情報の報告
* 通知の報告
* 動的コンテンツの変化の報告

**Comment by TetsuroOkane** [comment]
・「オブジェクト表示」の「通知
の報告」や「動的コンテンツの変化の報告」をオフにする。
・ツールチップ情報の報告のチェックを外す。
何れも試して変化がありませんでした。

NV Access宛てに質問リプライを送ったものの返信は
We haven't implemented a keystroke for that - If that alt+windows is a Zoom command then it should work.  If it's a Jaws command then we don't currently have an equivalent, however you are welcome to file an issue to request 
(そのためのキーストロークを実装していません-そのalt + windowsがZoomコマンドである場合、動作するはずです。 Jawsコマンドの場合、現在のところ同等のものはありませんが、リクエストして問題を報告することはできます。)との回答が来ました。

メモ帳でチャットを書いて貼り付ける方法が使えないかを検証しましたが、メモ帳にフォーカスがあっても入力を中断してアラートの読み上げが始まります。
※１　上記設定にすると、画面右下に出るメールの新着通知やカーソルを当ててそのままにすると出て来る説明などは読まれなくなっているので、Zoomの通知以外では正常に動作していると思われます。
※２　3月19日のイベントでは2台パソコンを用意し、Zoomが動いているパソコンはNVDAをスリープモードにして、実演用のパソコンのみNVDAを動作させていました。

**Comment by nishimotz** [comment]
Zoom バージョン 5.2 の設定「接近性」「画面リーダーのアラート」で

* IMチャットの受信
* 参加者がミーティングに参加済み／退出済み（ホストのみ）

などを無効化できるようになっています。

これで解決できるかどうか、ご確認いただければと思います。

**Comment by TetsuroOkane** [comment]
検証遅くなり失礼いたしました。
Zoomアプリを更新後に個別に設定変更して検証したところ、意図した動作になっていました。
Zoom側に設定できる機能が標準搭載されたので、このチケットはクローズして良いと思います。
