### ISSUE TITLE
Word 要素リスト内でのアクセスキーの定義不備

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#268]
Wordで要素リストを利用している際、アクセスキーを利用した操作で、想定外の挙動となる。
原因はアクセスキーが重複しているためで、ユニークとなる適切なアクセスキーの定義が必要。

### 問題の再現手順
1. Wordで任意のドキュメントを開く
2. 要素リストを開く(NVA+F7)
3. 種別「リンク」を選び、ツリービュー内の任意のリンクを選択する
4. 種別「コメント」を再選択しようとするとアクセスキー Alt+A を押す

### 実際に起きること
「アクションの実行」が実行される

### 期待されること
種別「コメント」が再選択される

### システム構成
NVDA 日本語版 2020.1jp インストール環境
Windows 10 バージョン 1909 日本語環境
Microsoft Word 2016

### その他の質問
NVDA 日本語版 2019.3.1jp でも再現する

**Comment by nishimotz** [comment]
遅くなってしまいましたが、上記が本家版、下記が日本語版（いずれもアルファ版）で、
本家版では「アクションの実行」に A が割り当てられていないことを確認しました。

NVDA version alpha-22709,5603440a
![image](https://user-images.githubusercontent.com/76300/118348110-fe320900-b582-11eb-82aa-0ddc0b1d7db7.png)

NVDA version jpalpha_210420o
![image](https://user-images.githubusercontent.com/76300/118348151-4e10d000-b583-11eb-9540-3355d766256a.png)

**Comment by nishimotz** [comment]
本家 2021.1 に向けて最近修正されました。
https://github.com/nvaccess/nvda/issues/6167
