### ISSUE TITLE
Word 書式情報の読み上げで「段落」情報が正しく読み上げられない場合がある

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#270]
Word内でのいくつかの段落設定において、書式情報が正しく読み上げられないケースがある。

### 問題の再現手順
1. Wordを起動する
2. 段落設定として「行間 1.15」を設定されたものをNVDA+Fで書式情報を読み上げる
3. 段落設定として「行間 最小値 12pt」を設定されたものをNVDA+Fで書式情報を読み上げる
4. 段落設定として「行間 固定値 16pt」を設定されたものをNVDA+Fで書式情報を読み上げる

添付：Word書式 段落情報 不正表示例.zip
実際に段落設定されたWord、段落設定画面、NVDA書式情報画面をキャプチャーしたもの
[Word書式 段落情報 不正表示例.zip](https://github.com/nvdajp/nvdajp/files/4611041/Word.zip)

### 実際に起きること
2. 段落設定として「行間 1.15」を設定されたものをNVDA+Fで書式情報を読み上げる
　→「行間 1.2行」と表示される（小数点以下２位の精度で値が返らない）
3. 段落設定として「行間 最小値 12pt」を設定されたものをNVDA+Fで書式情報を読み上げる
　→「行間 最低 12.0 pt」と表示される（Word用語「最小値」とNVDA用語「最低」と不一致）
4. 段落設定として「行間 固定値 16pt」を設定されたものをNVDA+Fで書式情報を読み上げる
　→「行間 固定値」と表示される（pt 情報が表示されない）

### 期待されること
Wordの段落情報と同じ情報が読み上げられること

### システム構成
NVDA 日本語版 2020.1jp インストール環境
Windows 10 バージョン 1909 日本語環境
Microsoft Word 2016

### その他の質問
NVDA 日本語版 2019.3.1jp でも再現する

**Comment by nishimotz** [comment]
行間 1.15 という設定は私が使っている環境の Word では選択肢がなく確認できませんでした。

「最小値 12pt 」はご指摘の通り Word の設定ダイアログでは「最低値」で NVDA の翻訳が「最小」になっています。
後述のとおり変更したいと思います。

行間 固定値 で pt 情報が欠落する現象は、再現できませんでした。

```
c:\work\nvda\srt\ja>svn diff nvda.po |nkf
Index: nvda.po
===================================================================
--- nvda.po     (revision 63855)
+++ nvda.po     (working copy)
@@ -6,7 +6,7 @@
 "Project-Id-Version: NVDA bzr main:5884\n"
 "Report-Msgid-Bugs-To: \n"
 "POT-Creation-Date: 2021-08-06 00:01+0000\n"
-"PO-Revision-Date: 2021-08-02 12:04+0900\n"
+"PO-Revision-Date: 2021-08-13 17:36+0900\n"
 "Last-Translator: Takuya Nishimoto <nishimotz@gmail.com>\n"
 "Language-Team: NVDA Japanese Team <nishimotz@gmail.com>\n"
 "Language: ja\n"
@@ -12215,7 +12215,7 @@
 #, python-format
 msgctxt "line spacing value"
 msgid "at least %.1f pt"
-msgstr "最低 %.1f pt"
+msgstr "最小値 %.1f pt"

 #. Translators: line spacing of x lines
 #, python-format
```
