### ISSUE TITLE
読み上げを途中で停止させるとカーソルがドキュメント末尾に移動する

### ISSUE THREAD

**Issue by msuzu15** [nvdajp/nvdajp#276]
### 問題の再現手順

1. Internet Explorerで次のURLを開く：https://ja.wikipedia.org/wiki/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%83%AA%E3%83%BC%E3%83%80%E3%83%BC
2. Hキーを何度か押して、「概説」という見出しに移動する。
3. NVDA+↓キーを押して、全文読み上げを開始する。
3. 「視覚障害者がパソコンを操作する際、健常者が行うように…」と読み上げられたあたりで、Ctrlキーを押して読み上げを停止させる。
4. 3.で読み上げを停止させた後、↓キーを押す。

### 実際に起きること

「6. ^“日本語音声合成エンジンの設定について…」と読み上げされる。その後Shift+Hキーを押すと、「脚注」という見出しが読み上げされる。つまり、カーソルがドキュメントの最後のセクションの位置まで移動してしまっている。

### 期待されること

「画面を操作する場合に特に困難が伴う。特に全盲のユーザが支援技術無しにマウス操作することは…」と、読み上げを停止した近辺から読み上げされる。

### システム構成

NVDA 日本語版 2020.1jp ポータブル版
Windows 10 バージョン 17134 英語環境
Internet Explorer 11

### その他の質問

PC を再起動してもこの問題は再発する。
NVDA 日本語版 2019.3jp以前のバージョンでは再現しない。
JTalkで再現する。
Internet Explorerでは再現するがGoogle Chromeでは再現しない。

#### 他のバージョンの NVDA と比較している場合はその結果

NVDA 2020.1jpでしか再現しない。

#### アドオンを無効化するとこの問題は解決しますか？

解決しない。

#### NVDAメニュー / ツール / COM登録の修復ツールを使うとこの問題は解決しますか？

解決しない。

**Comment by nishimotz** [comment]
状況を把握できました。ありがとうございます。
フォーカスハイライトの動き方も違いますね。

**Comment by nishimotz** [comment]
* nvda_2019.3.1jp-beta-200214w.exe ではこの現象が起きていないので #253 の副作用ではなさそう
* 本家の speech モジュールのリファクタリングのマージの影響という可能性
* ひきつづき過去のスナップショットを調べて、問題の原因になったコミットを探す予定

**Comment by nishimotz** [comment]
nvda_2020.1jp-beta-200312t.exe

* おきない
* betajp-1308
* https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/31418863/artifacts
* https://github.com/nvdajp/nvdajp/commit/f60d86194ae1efa6272f0b44f8ff8506fed964a3

途中のコミット

* https://github.com/nvdajp/nvdajp/commit/c2b07a9780633b2c85335868ede7fb12be87b101 関係がありそう（source/sayAllHandler.pyのリファクタリングがある）

nvda_2020.1jp-beta-200323q.exe

* おきる
* betajp-1314
* https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/31645641/artifacts
* https://github.com/nvdajp/nvdajp/commit/337889facbb7f84cd83b8f41547c1d2cf29860cd

**Comment by nishimotz** [comment]
2020.2jp-beta-200706t で（完全かどうかわかりませんが）修正しました。

http://s.nvda.jp/nvda_2020.2jp-beta-200706t.exe

ご確認いただけると助かります。

**Comment by msuzu15** [comment]
確認しました。問題は解消されています。

**Comment by nishimotz** [comment]
ありがとうございます。
もともとの 2019.3 対応が不完全で、たまたま 2019.3 ではうまく動いていた、
ということだと思われます。
