### ISSUE TITLE
記号の読み方が状況により異なる

### ISSUE THREAD

**Issue by hrk-fujii** [nvdajp/nvdajp#285]
### 問題の再現手順

1. notepadなど、テキストエリアを開く
2. 各種記号を入力する
3. 2で入力した記号の一部を削除する
4. 入力内容を１文字ずつ確認する

### 実際に起きること

記号の読み方が場合により異なる
例　記号 : 手順2,3 -> 手順4
{ : 中括弧 -> 開き波括弧　（j-talkは"ヒラキハカッコ"と発音）
^ : べき乗 -> サーカムフレックス
' : シングル -> ストレートアポストロフィ
等他多数

### 期待されること

上記手順にかかわらず、これまで同様の記号読みが行われる
あるいは、その方法が提供される

### システム構成

NVDA 日本語版 2020.4jp-beta-201223l インストール環境

Windows 10 バージョン 20H2 日本語環境

ATOK 2016

### その他の質問

PC を再起動してもこの問題は再発する : はい

NVDA 日本語版 2020.3jp でも再現する : いいえ

アドオンを無効化するとこの問題は解決しますか？ : いいえ

NVDAメニュー / ツール / COM登録の修復ツールを使うとこの問題は解決しますか？ : いいえ

**Comment by nishimotz** [comment]
ご報告ありがとうございます。

2020.4jp-beta-201201q では再現できませんが、2020.4jp-beta-201223l ではご報告いただいた状況であることを、
こちらでも確認しました。

比較的最近の作業の影響と思いますが、日本語版独自の作業を行っていないので、本家版をマージした影響と考えられます。

もうすこし調べてみます。

**Comment by nishimotz** [comment]
こちらで把握しているスナップショット

2020.3jp と同じ

* 2020.4jp-beta-201204k (build 1435)
* https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/36653413/artifacts
* https://github.com/nvdajp/nvdajp/commit/9f0de45a5502cd9072b65245dcbde4710d1228d9

2020.3jp と異なる

* 2020.4jp-beta-201210o (build 1439) 
* https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/36755143/artifacts
* https://github.com/nvdajp/nvdajp/commit/d331ed54046682b7027238204887df36074bc841

**Comment by nishimotz** [comment]
include/cldr-emoji-annotation が include/cldr に変わったことの影響と考えられる。

https://github.com/nvdajp/nvdajp/tree/9f0de45a5502cd9072b65245dcbde4710d1228d9/include
https://github.com/nvdajp/nvdajp/tree/d331ed54046682b7027238204887df36074bc841/include

**Comment by nishimotz** [comment]
過去の作業 #90

**Comment by nishimotz** [comment]
ポータブル版を作って locale/ja/cldr.dic を比較。

右側 (201210o) で「開き波括弧」などが追加されている。

![image](https://user-images.githubusercontent.com/76300/103543216-815e9680-4ee1-11eb-8e96-dc7de6fbcb5b.png)

cldr.dic には絵文字しか入っていないので、他の辞書よりも優先順位を高くして処理していたが、
含まれる記号が増えてしまったため、他の辞書の優先順位が下がったことにより、
今回の挙動の変化が起きたと考えられる。

**Comment by nishimotz** [comment]
2020.3jp までは、記号の読み定義の優先順は高いほうから順に

* nvdajp 独自の（ユーザー設定フォルダー） charaters-ja.dic 
* nvdajp 独自の（ユーザー設定フォルダー） charaterDescriptions-ja.dic 
* CLDRを有効にした場合は NVDA 内蔵 cldr.dic
* nvdajp 独自の NVDA 内蔵 characters.dic
* NVDA 内蔵 locale/ja/charaterDescriptions.dic

2020.4jp からの仕様案、記号の読み定義の優先順は高いほうから順に

* nvdajp 独自の（ユーザー設定フォルダー） charaters-ja.dic 
* nvdajp 独自の（ユーザー設定フォルダー） charaterDescriptions-ja.dic 
* nvdajp 独自の NVDA 内蔵 characters.dic
* NVDA 内蔵 locale/ja/charaterDescriptions.dic
* CLDRを有効にした場合は NVDA 内蔵 cldr.dic

**Comment by nishimotz** [comment]
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp-q4r95/builds/37111336

試してみたのですが、完全には CLDR 辞書の優先順位を制御できておらず、
かえっておかしな挙動になってしまったようです。

優先度は元に戻して、cldr.dic から問題になりそうな記号を削除する、という方針に変更したいと思います。

**Comment by nishimotz** [comment]
作業メモ

unicodedata.category() を使って "So" = other symbols のものだけを cldr.dic に残す
 
http://www.unicode.org/reports/tr44/#General_Category_Values

**Comment by nishimotz** [comment]
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/37111977/artifacts

これでは十分ではなかったので "Cn" = "Unassigned" の場合も出力対象とする。
（Python のバージョンによって unicodedata の判定が違う）

**Comment by hrk-fujii** [comment]
@nishimotz ご対応いただき、ありがとうございます。
