### ISSUE TITLE
Excelの矢印キーでのセル移動が不安定

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#286]
[nvda-japanese-users:2983] NVDA 2020.3jp + Office 365 - Excelの矢印キーでのセル移動が不安定

からのやり取りで、西本が再現できた手順をこのチケットにまとめます。

マウスポインタを使わない場合の現象も報告されているのですが、ひきつづき調査させてください。

(1)
新しいシートの A1 から下に向かって「あ」「い」「う」と入力。
つまり A3 に「う」が入力されている。

(2)
Ctrl+Home で現在のセルを A1 に戻す。

(3)
マウスで A4 をクリックして現在のセルを A4 に移動する。
NVDA は何も読み上げない。

(4)
上矢印キーを押す。
A3 にセルは移動するが、NVDA は「A4」と読み上げる。
さらに上矢印を押す。
A2 に移動するが「う A3」と読み上げる。
さらに上矢印を押す。
A1 に移動するが「い A2」と読み上げる。

**Comment by msuzu15** [comment]
上記ステップをこちらでも試してみましたが、同じような現象はこちらでは再現しません。

こちらでは、添付Excelファイルを使うと、以下のような現象が発生します。
[Excel読み上げテスト_データマッピング.zip](https://github.com/nvdajp/nvdajp/files/6059304/Excel._.zip)
（注意：以前のファイルには個人情報が含まれていたため、差し替えました。以前のファイルは削除いただきますようお願い致します）

・Excelを開いたとき、BQ60セルが選択されている。
・左矢印キーを9回押すと、BH60と読み上げされる。
・そこからさらに左矢印キーを押すと、BH60と読み上げされる。
・そこからさらに左矢印キーを押すと、BG60と読み上げされる。
・そこからさらに左矢印キーを押すと、BF60と読み上げされる。
・そこからさらに左矢印キーを押すと、AE60からBE60と読み上げされる（結合セル）。
・そこから右矢印キーを押すと、AC60からAD60と読み上げされる（結合セル）。
・そこからさらに右矢印キーを押すと、AE60からBE60と読み上げされる（結合セル）。
・そこから左矢印キーを押すと、BF60と読み上げされる。
・そこからさらに左矢印キーを押すと、AE60からBE60と読み上げされる（結合セル）。
・そこから右矢印キーを押すと、AC60からAD60と読み上げされる（結合セル）。
・そこからさらに右矢印キーを押すと、AE60からBE60と読み上げされる（結合セル）。

こちらの環境は以下の通りです。

NVDA 2020.3jp インストール環境
音声エンジンはJTalkを使用
Windows 10 バージョン 1909 英語版
Microsoft® Excel® for Microsoft 365 MSO (16.0.13231.20620) 32-bit 英語版

いまのところ、以下のことがわかっています。

・この現象はNVDA 2019.2.1jpでは発生しない。
・この現象はNVDA2020.1jp、2020.2jp、2020.3jpで再現できる。
・この現象が再現するExcelファイルのシートの内容の条件は不明。ただ、以下の傾向が見られる。
　○ブランクのシート（セルにデータがない）では発生しない。
　○列の幅の広い列（列の幅が40以上等）があるとこの現象が発生しやすいように思われる。
　○添付のサンプルには結合セルが使用されているが、結合セルのないシートでも同様の問題が発生している。
・同様の問題は、少なくとも5人が経験していて同様の問題が報告されている。

**Comment by msuzu15** [comment]
NVDA 2019.3.1jpではこの現象は再現しませんでした。

**Comment by msuzu15** [comment]
本家版でも同じ問題が発生したので、本家githubにも登録しました。
https://github.com/nvaccess/nvda/issues/12108

**Comment by nishimotz** [comment]
本家 2023.2 で改善されたはずです。
