### ISSUE TITLE
Googleドキュメントの点字サポートオンでの複数行箇条書き読み上げの不具合

### ISSUE THREAD

**Issue by minakononogaki** [nvdajp/nvdajp#287]
問題の再現手順
1. Chromeを開き、Googleドキュメントを開く。
2. ツールのユーザー補助設定でスクリーンリーダーのサポートと点字サポートを有効にする。
3. 2行にわたる箇条書きを書く。
4. 上下矢印キーで箇条書きの2行目の先頭にカーソルを移動する。

実際に起きること
箇条書きのその項目の1行目の先頭から、その項目全体が読み上げられる。

期待されること
カーソルがある2行目の先頭から読み上げられる。（日本語ならよから、英語ならpから）

参考ファイル（状態が再現可能なように編集可能状態です。書き換えませんようにお願いいたします）
https://docs.google.com/document/d/1ZpP_zpviR59QPeKG9YPuopP6YffoWugnaBIXgOd1fp8/edit?usp=sharing

システム構成
NVDA日本語版2020.3jpインストール環境

Windows10 Pro バージョン2004 日本語環境

Google Chrome
Beta 89.0.4389.47
Canary 90.0.4420.0

なお、Google Chrome Official 88.0.4324.182では起きません。

点字ディスプレイ　Orbit Reader 20

その他の質問
PCを再起動してもこの問題は再発する→はい。
NVDA日本語版2019.2.1jp、2017.3jpでも再発する→はい。
他のバージョンのNVDA→NV AccessのNVDAで再現（Windows, Google Chrome, Googleアカウントにて英語環境）。
アドオンの無効化により解決→いいえ。
COM登録の修復ツールで解決→いいえ。

英語版、NV AccessのNVDAについてのチケットを、NV Accessの方に、同様の内容で上げたいと思います。

**Comment by ji6czd** [comment]
Google docsのことだったので調べてみました。すでに解決されているように思います。おそらくクローズしても大丈夫かと思います。

環境は、

* Windows 11 OS ビルド 23403.1001
* Chrome 111.0.5563.64
* NVDA: 2022.04JP

です。

**Comment by nishimotz** [comment]
ご報告ありがとうございます。
