### ISSUE TITLE
jpalpha_210711k でレビューカーソルでの1文字読みがおかしい

### ISSUE THREAD

**Issue by riku22** [nvdajp/nvdajp#297]
### 問題の再現手順

1. メモ帳を開く。
2. 「abc」と入力する。
3. NVDA+左矢印を押して1文字読みさせる。

### 実際に起きること

「半角 英字 シー」と読み上げられる。

### 期待されること

「シー」とのみ読み上げられる。

### システム構成

- NVDA jpalpha_210711k ポータブル版
- Windows 21H1 64ビット版

#### PC を再起動してもこの問題は再発しますか？
はい

#### 他のバージョンの NVDA と比較している場合はその結果
2020.4では問題ありません。

#### アドオンを無効化するとこの問題は解決しますか？
いいえ

#### NVDAメニュー / ツール / COM登録の修復ツールを使うとこの問題は解決しますか？
いいえ

### 補足

日本語設定でフォネティック読みを有効にすると、2020.4との挙動の違いがわかりやすいと思います。

**Comment by nishimotz** [comment]
ご報告ありがとうございました。
nvda_jpalpha_210711r.exe に更新しました。

**Comment by riku22** [comment]
更新ありがとうございます。
jpalpha_210711r で問題ないことを確認できました。


_____


これと同じような問題だと思うので、追加ですみません。
NVDA+ピリオドを押した時の挙動も2020.4と異なるようです。
具体的に書くと、「c」にカーソルをあわせた状態でNVDA+ピリオドを押すと、2020.4では「シー」と読み上げられていましたが、 jpalpha_210711k 以降では「半角 英字 シー」と読み上げられてしまいます。
それから、NVDA+Ctrl+ピリオドでの単語の報告ですが、3回押した際の文字説明での報告もうまく動作していないようで、2回押した時と同じ挙動になっているようです。
別のIssueを作った方がよければ、お知らせください。

**Comment by nishimotz** [comment]
報告ありがとうございます。追加の内容もこの issue でカバーします。

**Comment by nishimotz** [comment]
アルファ版、ベータ版を以下に更新しました。
nvda_jpalpha_210711u.exe
nvda_2021.1jp-beta-210711t.exe

**Comment by riku22** [comment]
jpalpha_210711u での修正を確認しました。
お手数をおかけしました。
ありがとうございました。
