### ISSUE TITLE
日本語漢点字・六点漢字への対応

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#306]
https://osdn.net/projects/nvdajp/ticket/34647 の内容をこちらでカバーします。

**Comment by nishimotz** [comment]
2017.4jp の説明
https://www.nvda.jp/nvda2021.1jp/ja/readmejp.html#toc82
「実験的な機能として、点字ディスプレイからの文字入力で
日本語カナと六点漢字の入力テーブルが選べるようになりました。」

チケット
https://github.com/nvdajp/nvdajp/issues/50
このときの作業の内容
https://github.com/nvdajp/nvdajp/pull/48/files

新しいバージョンのお知らせを @brlat さんからいただきました
https://github.com/brlat/Liblouis-Japanese-kanji-braille-tables

liblouis 本家版
https://github.com/liblouis/liblouis

**Comment by nishimotz** [comment]
新しい漢点字のリポジトリと紹介ページの情報をいただきました。

https://github.com/brlat/liblouis-ja-kantenji

NVDAで楽しむ「漢点字」
https://brlat.github.io/

**Comment by nishimotz** [comment]
本家アルファ版ですが

https://www.nvaccess.org/files/nvda/snapshots/

NVDA alpha-24329,d3444424

で出力テーブルに kantenji が選択できることを確認しました。
（入力テーブルとしては選べないように NVDA 側で実装されたようです）

点字ビューアーで確認した範囲では、漢点字が正しいかどうかは判断できませんが、
それらしい出力になっていると思います。

本家版 NVDA には KGS ドライバーがないから、試せない人がいるでしょうが。。

いわゆる 7 8 の点が使われている文字で、
テキストカーソルの点滅がわかりにくいことがありますね。。
まあ漢点字に固有の問題ではないのでしょうが。。

NVDA の liblouis の更新は下記のプルリクエストで作業されたことを確認しました。
https://github.com/nvaccess/nvda/pull/13141

**Comment by nishimotz** [comment]
2022.1jp での作業案

* 従来の日本語版独自の入力テーブルは「日本語六点漢字」から「日本語6点漢点字(入力用)」に変更（出力用には選択不可）
* 本家に入った出力用テーブルを「日本語6点漢点字」と表示。このまま入力用には選択不可とする？？

@brlat さんが liblouis に提供された漢点字テーブルは入力用としても選択できた方がいいでしょうか？

**Comment by brlat** [comment]
こんにちは。Liblouis用の漢点字テーブルですが、いくつかの理由で入力用に使うことを私は作成自体をしていません。Liblouisのテーブルの中でそのテーブルはforward translation用なのか、back-translation(点字から墨字、目で読む文字、テキスト)へ逆変換するためのものか、それとも両方のためのものか指定するようになっています。私はforward translation用として書いています。理由は一つは逆変換用のテーブルをどうやって作ったらいいかわからないからでもあり、もう一つの理由としては、漢字の点字方式での墨字(目で読む文字)の入力は、「やむ(八六)6点」を使ってNVDA上で可能だからです。NVDA本体で漢字の点字の入力をサポートすることは優先ではないと私は思うのですがどうでしょうか。
作り方がわからないという意味はこういうことです。
Liblouisの8点式点字と、漢点字(8点漢字)の8点のシステムでは、メインの6点の位置が異なっています。
通常のLiblouisの8点では、左の一番上から下に1 2 3 7という点のナンバリングがされているのに対して、8点漢字の8点では左の上から下に7 1 2 3のようにナンバリングされています。
たとえばアルファベットのaを入力するために、通常のLiblouisでは1を入力しますが、8点漢字ではaを入力するためには2を押さなければなりません。
表示された点字を読む場合には、相対的な位置関係なので、データ上2であっても1のaとして読むことができますが、入力するときに2でaを入力するのは不便です。
すみません、うまく説明できていないと思いますが、またメーリングリストに書いてみます。

**Comment by nishimotz** [comment]
補足ありがとうございます。

「日本語6点漢点字(入力用)」はひきつづき実験的機能として（従来の仕様のまま）提供することにします。

**Comment by mitsugusakamoto** [comment]
点字表示テーブルの選択の「日本語6点漢点字」は「日本語漢点字」とかにするべきかと思います。ここら辺は正確にしておいたほうが良いと考えます。6点のようなものを入れなければ翻訳の都合で行けない場合は、「日本語8点漢点字」が100歩譲っていいのかもしれません。

**Comment by nishimotz** [comment]
現状の表記が不正確であるというご指摘なのですが、
@brlat さんのご意見をお聞かせいただけますか？

**Comment by nishimotz** [comment]
指摘されている状況は以下です。補足があればお願いします。

https://www.nvda.jp/nvda2022.4jp/ja/readmejp.html#toc29

現状

5.3.3. 出力テーブル「日本語6点漢点字」
出力テーブル「日本語6点漢点字」が NVDA 2022.1 本家版に追加され、NVDA 2022.1jp でも利用可能になりました。これは本家版の点訳エンジン Liblouis を使用する漢点字の出力テーブルです。

指摘されている内容

* この設定で実際に出力されるのは「日本語8点漢点字」

**Comment by KatsutoshiTsuji** [comment]
@mitsugusakamoto さんが指摘してくれているとおり、出力されるのは日本語漢点字なので、出力テーブルの名称を変更した方が良いと思います。

- 日本語：「日本語漢点字
- 英語： 「Japanese (Kantenji) literary braille」
に変更したいと思いますが @brlat さんいかがでしょうか？
(CC: @nishimotz )

**Comment by nishimotz** [comment]
TODO

* 直すとしたらどこが影響範囲なのか把握する

**Comment by nishimotz** [comment]
本家版 nvda.po 確認しましたが、英語では Kantenji としか書かれていないことに気づきました。
私が誤解して誤訳してしまったことになります。ごめんなさい。

```
#. Translators: The name of a braille table displayed in the
#. braille settings dialog.
msgid "Japanese (Kantenji) literary braille"
msgstr "日本語6点漢点字"
```

**Comment by nishimotz** [comment]
NVDA日本語版の説明

5.3.3. 出力テーブル「日本語6点漢点字」
https://www.nvda.jp/nvda2022.4jp/ja/readmejp.html#toc32

を次のリリースで「日本語漢点字」に修正します。
