### ISSUE TITLE
更新チェックに失敗する場合がある

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#309]
Twitter で以下のご指摘をいただきました

https://twitter.com/nyanchan2013/status/1443913034578100224

www.nvda.jp は Let's Encrypt を使用しているため、9月30日ごろのルート証明書の移行で
失敗する懸念はあったのですが、こちらでは現象を再現できずにいました。

サーバー側のログを調べていたら、versionType=stable というリクエストが来た場合に、
レスポンスに失敗していることがわかりました。

updateCheck.py の _updateWindowsRootCertificates() で versionType=stable というリクエストを使って
Windows API に足りないルート証明書を登録しているのですが、
この処理が失敗していると考えられます。

NVDA 日本語版では versionType として nvdajp, nvdajpalpha, nvdajpbeta の3種類だけを
使っているつもりでした。

ひとまず versionType=stable がエラーにならないようにサーバー側を修正します。

**Comment by nishimotz** [comment]
10月7日17時20分ごろ、サーバー側を修正しました。
すこし様子を見ます。

**Comment by yncat** [comment]
NVDA 2021.2jp portable
で失敗しているログを添付します。実施したのは、本日の20時7分 JST 頃です。
```
INFO - updateCheck.AutoUpdateChecker._started (20:07:03.479) - MainThread (10468):
Performing automatic update check
DEBUGWARNING - updateCheck.UpdateChecker._bg (20:07:03.588) - updateCheck.UpdateChecker.check (13776):
Error checking for update
Traceback (most recent call last):
  File "urllib\request.pyc", line 1350, in do_open
  File "http\client.pyc", line 1277, in request
  File "http\client.pyc", line 1323, in _send_request
  File "http\client.pyc", line 1272, in endheaders
  File "http\client.pyc", line 1032, in _send_output
  File "http\client.pyc", line 972, in send
  File "http\client.pyc", line 1447, in connect
  File "ssl.pyc", line 423, in wrap_socket
  File "ssl.pyc", line 870, in _create
  File "ssl.pyc", line 1139, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "updateCheck.pyc", line 250, in _bg
  File "updateCheck.pyc", line 140, in checkForUpdate
  File "urllib\request.pyc", line 222, in urlopen
  File "urllib\request.pyc", line 525, in open
  File "urllib\request.pyc", line 543, in _open
  File "urllib\request.pyc", line 503, in _call_chain
  File "urllib\request.pyc", line 1393, in https_open
  File "urllib\request.pyc", line 1352, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)>

```

機動情報は
```
INFO - __main__ (20:07:02.413) - MainThread (10468):
Starting NVDA version 2021.2jp
INFO - core.main (20:07:02.487) - MainThread (10468):
Config dir: C:\nvda2021.2\userConfig
INFO - config.ConfigManager._loadConfig (20:07:02.487) - MainThread (10468):
Loading config: C:\nvda2021.2\userConfig\nvda.ini
INFO - core.main (20:07:02.515) - MainThread (10468):
Developer Scratchpad mode enabled
INFO - core.main (20:07:02.610) - MainThread (10468):
Windows version: Windows 10 20H2 (10.0.19042) workstation
INFO - core.main (20:07:02.610) - MainThread (10468):
Using Python version 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)]
INFO - core.main (20:07:02.610) - MainThread (10468):
Using comtypes version 1.1.8
INFO - core.main (20:07:02.610) - MainThread (10468):
Using configobj version 5.1.0 with validate version 1.0.1
```

何かの手がかりになれば幸いです。

**Comment by riku22** [comment]
NVDAのルート証明書の登録ですが、2021.2までのコードでは例外処理がうまく動いておらず、ルート証明書の登録が失敗しています。
なお、この問題は2021.3で修正されているようです。
とりあえず、NVDAのPython コンソールで下記を実行すると回避できるかもしれませんが、こちらの環境では特にエラーもなくアップデートチェックできているので、治るかどうかはなんともいえないです。

```
import updateCheck
updateCheck._updateWindowsRootCertificates()
```

**Comment by yncat** [comment]
```
>>> import updateCheck
>>> updateCheck._updateWindowsRootCertificates()
>>> updateCheck.UpdateChecker().check()
```

が成功して、あーできたな、登録しないとどうなるのかなと思ったら、以後失敗しなくなりました。
というか、 updateChecker のログが消えました。エラーがないから起動時にも出ないのかもしれない。
中身読んでないですが、これってなんかローカルの証明書をアップデートして書き込むようなもので、永続的に作用したりするんですかね。

**Comment by riku22** [comment]
Windowsのルート証明書に登録されるので、手動で削除しない限り、永続的に残るはずです。
また、自動アップデートチェックの間隔は1日に1回なので、前回のチェックが成功しているかつ前回のチェックから1日以上経っていない場合は、起動時にアップデートチェックのログは出ないと思います。

**Comment by nishimotz** [comment]
本家 https://github.com/nvaccess/nvda/pull/12729 ですね。情報提供ありがとうございます。

**Comment by nishimotz** [comment]
2021.3jp で修正されるのはよいのですが、
過去のバージョンからスムーズに更新できたほうがいいので、
サーバー証明書で Let's Encrypt の使用をやめることも引き続き検討中です。

**Comment by nishimotz** [comment]
10月11日11時ごろ www.nvda.jp サーバーの更新を行いました。
Let's Encrypt の証明書を使用しなくなったはずです。
内部的な構成をいろいろ変えているので、別の不具合が起きる可能性もあります。
すこし様子を見たいと思います。

**Comment by nishimotz** [comment]
更新サーバーのアクセス数が回復しているので、解決していると判断します。

なお、本家では 2021.2 向けに NVDA Certificate Patch Add-on を配布したとのことです。

https://www.nvaccess.org/post/in-process-19th-october-2021/

日本語版ではこのパッチは不要と考えています。

気になることがあればお知らせください。
