### ISSUE TITLE
Windows11 クリップボード履歴の不具合

### ISSUE THREAD

**Issue by yama3nomori** [nvdajp/nvdajp#311]
バージョン 21H2 (OS ビルド 22000.258)
Windows 11 Home
においてクリップボード履歴を正しく操作できていません。

 1. 1件目のみエンターでペイストできますが、
直前の画面にフォーカスが戻りません。

 2. 下カーソルでリストは閲覧できますが、
履歴の内容と内容の間に何も読まない項目が2つ含まれています。

**Comment by nishimotz** [comment]
以下を教えていただけますか？

* お使いの NVDA のバージョン
* もし比較が可能であれば Windows 10 で同様の操作をした場合の状況

**Comment by yama3nomori** [comment]
NVDAは
Version: 2021.3jp-beta-211021v
を使用しています。

Windows10 20H2では問題なく動作していますが、
Windows 21H1では、クリップボード履歴の1つ目を読み上げてはいますが、
下カーソルを押しても履歴は辿れず、元の画面ないを読み上げてしまいます。

**Comment by nishimotz** [comment]
Windows 10 version 21H1 でも発生しているのですね。
追加の質問ですが、なにかクリップボードや絵文字パネルに影響するアドオンをお使いでしょうか？
例えば Windows App Essentials などが考えられます。

**Comment by yama3nomori** [comment]
アドオンは
bluetoothaudio
speech history
が入っています。

**Comment by yama3nomori** [comment]
Version: 2021.3.4jp-beta-220317m
に更新しましたが、依然Windows11ではクリップボード履歴が操作できていません。
使用中のアドオンに変更はありません。
因みにWindows10 21H2では操作できています。

**Comment by nishimotz** [comment]
本家版 2022.1 の「Windows 11 対応のさまざまなバグ修正」でこの件も改善されそうです。

**Comment by yama3nomori** [comment]
情報をありがとうございました。
日本語版に適用されるのを楽しみにしています。

**Comment by nishimotz** [comment]
2022.1jp-beta で改善していなかったらお知らせください。
