### ISSUE TITLE
かな漢字変換の確定の時に「〆」という記号を「しめしめ」と読んでいる

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#320]
例えば「〆切」が「しめしめきり」になるという話です。

何か情報があればお知らせください。

**Comment by mitsugusakamoto** [comment]
1. notepad起動
2．　ｉｍｅをオンにして「しめきり」と変換候補を入力しスペースを押すと「しめ　きるしんせつのせつ」と変換候補を表示する。「〆」の詳細読みの候補は登録されてないのではないか。
3. 確定すると確定文字列が「しめしめきり」と音声と点字で表示される。
nvda: NVDA jpalpha_211201t 
Windows Version:
バージョン 21H1 (OS ビルド 19043.1415)

**Comment by nishimotz** [comment]
2024.1jp-beta-240327l + JTalk + 点字ビューアを使い、

> 確定文字列が「しめしめきり」と音声と点字で表示

を再現できなかったのでクローズします。

U+3006
〆

には詳細読みも「シメ」だけ登録されています。

テンキー2を2回押しても「シメ」なのは、不親切かも知れませんが、
いままでこういう仕様でした。

別途議論させてください。
