### ISSUE TITLE
Windows11 クリップボード履歴の不具合

### ISSUE THREAD

**Issue by yama3nomori** [nvdajp/nvdajp#347]
### 問題の再現手順

1. あいうえお　かきくけこ　さしすせそ　をそれぞれコピー。
2. win+Vでクリップボード履歴を開く。
3. 下カーソルでリストを閲覧。

問題の再現に必要なファイルは ZIP 形式のア
### 実際に起きること
リストが
さしすせそ
何も読み上げない
何も読み上げない
かきくけこ
何も読み上げない
何も読み上げない
あいうえお
何も読み上げない
何も読み上げない
で構成されている。
どの行でエンターを押しても貼り付けが実行されない。

### 期待されること

リストが
さしすせそ
かきくけこ
あいうえお
と辿れ、エンターで貼り付けが実行される。

### システム構成

NVDA 日本語版 2022.3jp-beta-220825q
Windows 11 バージョン 21h2 日本語環境

#### PC を再起動してもこの問題は再発しますか？
はい

#### 他のバージョンの NVDA と比較している場合はその結果
2022.2.1jpでは起きていません。

#### アドオンを無効化するとこの問題は解決しますか？
いいえ、解決しません。

#### NVDAメニュー / ツール / COM登録の修復ツールを使うとこの問題は解決しますか？
いいえ

**Comment by yama3nomori** [comment]
補足です。
jpalpha_220824v
ではこの問題は起きていません。

**Comment by nishimotz** [comment]
2022.3jp-beta-220825q
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/44574343/artifacts
https://github.com/nvdajp/nvdajp/commit/9bb99e6de0c2e10b8a04c392a0bd350bc3ac8544

jpalpha_220824v
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/44565010/artifacts
https://github.com/nvdajp/nvdajp/commit/d2f9b83219fd0180c38b769e52eafd358f20da2b

いま、両者のソースコードが完全に一致しているはすです。
そちらで片方だけ挙動が違うとのことですが、確認した環境などに違いはないでしょうか？

**Comment by yama3nomori** [comment]
同じ環境で
アルファ版
ベータ版
正式版
のそれぞれを試しています。

**Comment by nishimotz** [comment]
だいたい同じ状況をこちらでも再現しました。
なんとコード証明書を更新する前のビルドだと不具合が起きないので、
ビルドするたびに何かが変わる、という不安定な状況なのかも知れません。こまったな。。
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/44561132/artifacts

**Comment by nishimotz** [comment]
ほぼビルドし直しただけなのですが、新しいビルドだと大丈夫のようです。
ビルドをリリースする前になるべく手作業で確認しますね。。
https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/44584961/artifacts

**Comment by nishimotz** [comment]
jpalpha_220827x
2022.3jp-beta-220827w
いずれも Windows+V の動作確認をして提供開始しました。
コード証明書を更新したので Smart Screen の確認ページが出るかも知れませんが、
いずれ出なくなるはずです。

**Comment by yama3nomori** [comment]
お陰様でクリップボード履歴が使用でき、作業の効率があがっています。ありがとうございます。

最近使っていて気が付いたことですが、
クリップボード履歴のリストをカーソルでたどれる条件として
__フォーカスモード__
になっている必要があるようです。

__ブラウズモード__ → __自動フォーカスモード__
がチェックされている場合は問題なさそうですが、
チェックしていない場合は、手動で切り替える必要があることがあります。
一度切り替えた後は状態が記憶されるようで以後は切り替え操作は不要になります。

**Comment by yama3nomori** [comment]
お手間をおかけしました。
素早い対応に感謝です。
