### ISSUE TITLE
「数式を英語で読み上げる」を初期設定では無効にしていただけないか

### ISSUE THREAD

**Issue by takenspc** [nvdajp/nvdajp#390]
### 背景（不満や不便なこと）

NVDA日本語版 2023.1jp (2023.1.0.1991)と[MathPlayer 4.0](https://info.wiris.com/mathplayer-info)の組み合わせにおいて、初期設定ではMathMLなどで表現された数式が英語で読み上げられます。

NVDA日本語版の設定で「日本語設定」にある「数式を英語で読み上げる」を無効にすると日本語で読み上げられます。

NVAccessが配布しているNVDA 2023.1とMath Player 4.0では初期設定で数式が日本語で読み上げられます。

数式の例

*   [Wikipediaの二次方程式の解の公式](https://ja.wikipedia.org/wiki/%E4%BA%8C%E6%AC%A1%E6%96%B9%E7%A8%8B%E5%BC%8F%E3%81%AE%E8%A7%A3%E3%81%AE%E5%85%AC%E5%BC%8F)

### 提案したい機能や方法

NVDA日本語版は日本語ユーザー向けと理解していますので、「数式を英語で読み上げる」を初期設定では無効にすることを検討いただけると幸いです。

### 考慮した代案があればお書きください

個人の設定として「数式を英語で読み上げる」を無効にしています。

### 関連する情報があればお書きください

私はNVDA日本語版をWebコンテンツなどの検証に用いており常用ユーザーではありません。常用ユーザーにとって「数式を英語で読み上げる」が有効でなければ不利益が大きいということであれば、初期設定を変更されなくても構いません。

**Comment by nishimotz** [comment]
ご提案ありがとうございます。

過去の経緯
https://www.nvda.jp/nvda2023.1jp/ja/readmejp.html#toc24

数式の対話的ナビゲーションに関して、最近の環境では確認できていません。
