### ISSUE TITLE
NVDA（トップ）メニューのアクセスキー R 設定

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#401]
### 問題の再現手順

1. NVDA+NでNVDAメニューを開く

### 実際に起きること

言語が日本語モードの場合、「前回保存された設定に戻す(R)」にアクセスキーが設定されているが
「設定のリセット」にアクセスキーの定義がない。

### 期待されること

NVDAメニューが開いた状態でアクセスキー R を押した場合、
言語が英語モードの場合、「&Revert to saved configuration」と「＆Reset configuration to factory defaults」
の項目に交互にフォーカスがあたるようになっている。
言語が日本語モードの場合、同等のメニュー項目に対して「前回保存された設定に戻す(R)」のみ
アクセスキーが設定されていて、「設定のリセット」にアクセスキーの設定がない。

それほど実害はないが、メニュー操作として NVDA+N → R を行った場合、
英語モードの場合、２つのメニュー項目を聞き分けて目的の項目を選択することができるが、
日本語モードの場合は、「前回保存された設定に戻す(R)」が一意で実行されてしまう。
アクセスキーの定義は日英揃っていた方が、アクセスキー利用による操作説明の際、混乱を避けることができる。、

### システム構成

NVDA 日本語版 2023.2jp-r2 インストール環境

**Comment by nishimotz** [comment]
誤操作を防ぐために意図的にこうしていましたが、
本家が 2023.3 でショートカットを変更するので、
日本語ベータ版でいずれご確認いただけるはずです。
