### ISSUE TITLE
Win+V クリップボード履歴を正しく読み上げない

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#407]
### 問題の再現手順

1 クリップボードに適当にコピーしたテキストを保持する
2 メモ帳を起動する
3 メモ帳内に何か適当なテキストを入力する
4 Win+V でクリップボード履歴を開く
5 上下矢印キーで履歴を確認する

### 実際に起きること

メモ帳内のフォーカス位置の内容を読み上げる
Issue #211 と同様の事象が再発しているように思われる

### 期待されること

クリップボード履歴を読み上げる

### システム構成

NVDA 日本語版 2023.2jp-r2 インストール環境

**Comment by nishimotz** [comment]
#410 と同様にこちらも日本語アルファ版で再確認していただけるとありがたいです。

最近の絵文字パネルやクリップボード履歴では NVDA+スペースでブラウズモードとフォーカスモードの
切り替えができることも、あわせてご注意ください。

**Comment by nishimotz** [comment]
2024.1jp-beta-240327l で改善を確認しました。
