### ISSUE TITLE
絵文字パネルでの読み上げが正しくない

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#410]
### 問題の再現手順

【不具合事例１】
1. Wordを起動し、文中にダミーとして「サンプル」と入力し、「サ」の左側にカーソルがある状態にする
2. Win+.（ピリオド）で絵文字パネルを開く
3. 絵文字アイコン一覧が選択できる状態で、１番目のアイコンが選択された状態で左矢印キーを押す

【不具合事例２】
1. 絵文字パネルを開いた状態にする
2. Shift+Tabキーでカテゴリ選択にフォーカスをあてる
3. 左右矢印キーでカテゴリを切り替える

【不具合事例３】
1. 絵文字パネルを開いた状態にする
2. Tabキーでグループ選択にフォーカスをあてる
3. 左右矢印キーでグループを切り替える

### 実際に起きること

【不具合事例１】
Word内のカーソル位置の文字「サ」と読み上げる

【不具合事例２】
Word内のカーソル位置の文字「サ」と読み上げる

【不具合事例３】
Word内のカーソル位置の文字「サ」と読み上げる

### 期待されること

【不具合事例１】
特に何も読み上げない
（左矢印キーを押し続けても１番目のアイコンが選択された状態は変わらないため）

【不具合事例２】
選択したカテゴリ名を読み上げる

【不具合事例３】
選択したグループ名を読み上げる

### システム構成

NVDA 日本語版 2023.2jp-r2 インストール環境
Windows10 Pro 22H2
Microsoft IME 新旧バージョンに依存せず発生

**Comment by nishimotz** [comment]
本家の最近の変更を日本語アルファ版に取り込んでいます。
絵文字パネルの仕様が変わっていてご報告のとおりではないかも知れませんが、
改善されていると思います。

**Comment by nishimotz** [comment]
2024.1jp-beta-240327l で改善されていることを確認しました。
