### ISSUE TITLE
2023.3での漢字変換時に余計な読みが入る

### ISSUE THREAD

**Issue by yama3nomori** [nvdajp/nvdajp#411]
### 問題の再現手順

1. メモ帳を開く
2. 折り返し表示を解除しておく。
3. "さいとう" と入力してスペースを押す

### 実際に起きること

1. スペースを押す度にスペースのアナウンスと変換候補が読み上げられる
2. 2 or 3番目の候補当たりの最初に__候補リスト リスト__とアナウンスが入る
3. 変換を続けると__テーブルビューを開きました__とアナウンスする
4. 更に変換すると__次の列__とアナウンスする
5. そのまま変換を続けると__最後の列__とアナウンスする

### 期待されること

変換候補のみを読み上げる

### システム構成

NVDA 日本語版 Version: 2023.3jp-beta-231003m (2023.2.0.3144)

Windows 11 Home バージョン 22H2 (OS ビルド 22621.2361)

#### PC を再起動してもこの問題は再発しますか？

はい

#### 他のバージョンの NVDA と比較している場合はその結果

Version: 2023.2jp-r2 (2023.2.0.3096)
Version: jpalpha_230929h (2024.1.0.3139)
ではこの問題は発生しませんでした。

#### アドオンを無効化するとこの問題は解決しますか？
いいえ

#### NVDAメニュー / ツール / COM登録の修復ツールを使うとこの問題は解決しますか？

いいえ

**Comment by nishimotz** [comment]
本家アルファ版で（日本語版との仕様の違いを除いて）問題を再現できました。
Starting NVDA version alpha-29529,a380b6a7

「以前のバージョンのMicrosoft IME」では再現しません。

確定をした時の状況は #402 でカバーしているので、ここでは候補ウィンドウに絞って考察すると、
ここは Python でワークアラウンドをしているところです。
最近では #382 で変更をしました。

これに関して、不要な読み上げを抑止するワークアラウンドを、
日本語版で独自に行ってきましたが、それが効かなくなったと考えられます。

いままでの方法で続けるなら、これは本家へのフィードバックというよりも
日本語版でやってきたことの再検討になりそうです。

いったんここまでにします。

**Comment by nishimotz** [comment]
* 同じ現象がナレーターで起きている

**Comment by yama3nomori** [comment]
この問題、
Windows10 22H2
バージョン 22H2 (OS ビルド 19045.3636)
では発生しないようです。

**Comment by nishimotz** [comment]
日本語アルファ版 231130p で確認したら再現しなくなりました。

**Comment by yama3nomori** [comment]
確認しました。修正ありがとうございました。
