### ISSUE TITLE
ウェブの入力欄にクリップボード履歴から入力後のフォーカスの読み上げ

### ISSUE THREAD

**Issue by yama3nomori** [nvdajp/nvdajp#430]
### 問題の再現手順

 0. 事前にクリップボードに
- あいうえお
- かきくけこ
をコピーします。

 1. Chromeで [NVDA日本語チームへの問い合わせ](https://docs.google.com/forms/d/e/1FAIpQLScGhM1atwkqEDvxPGFxrdY5l8L383twCP385E-MEX3nVwq8dA/viewform) を開きます。

 2. お問合せ内容を選択してフォーカスモードにします。

 3. win+Vでクリップボード履歴を開きます。

 4. シタカーソルで 
あいうえお
を選びエンターします。

### 実際に起きること

あいうえお
が入力される。
カーソルは問い合わせ内容に戻るがカーソルキーを押しても何も読み上げられない。
alt+タブで画面のフォーカスを切り替えるか、
引き続き
かきくけこ
を入力するとカーソルの読み上げが復旧する。
※この現象はメモ帳では発生しません。

### 期待されること

クリップボード履歴からの入力終了後、カーソルキーで1文字読みが行われる。

### システム構成

Windows 11 ホーム 64ビット
バージョン 23H2 (OS ビルド 22631.2861)
NVDA 2024.1jp-beta-231215j (2024.1.0.3300)
Chrome バージョン: 120.0.6099.72（Official Build） （64 ビット）

#### PC を再起動してもこの問題は再発しますか？

はい

#### 他のバージョンの NVDA と比較している場合はその結果

Version: jpalpha_231215j (2024.2.0.3301)
Version: 2023.3jp
でも同様。

#### アドオンを無効化するとこの問題は解決しますか？

いいえ

#### NVDAメニュー / ツール / COM登録の修復ツールを使うとこの問題は解決しますか？

いいえ

**Comment by nishimotz** [comment]
現象は再現できましたが、本家アルファ版でも同じ状況でした。

**Comment by nishimotz** [comment]
2024.3jp beta で期待通りに動作しているようです。

**Comment by yama3nomori** [comment]
Version: 2024.3jp-beta-240816u (2024.3.0.3649)
で期待通りに動作していることを確認しました。
