### ISSUE TITLE
NVDAメニュー項目のショートカットキーの改善

### ISSUE THREAD

**Issue by koichimase** [nvdajp/nvdajp#452]
### 問題の再現手順

1. NVDA+N でメニューを開く
2. 項目「ツール」から更にサブメニューを開き、それぞれのメニュー項目を選択する

### 実際に起きること

メニュー項目切り替え（上下矢印キー）の際、それぞれ次の様に読み上げる

ログビューアー(L)  l
スピーチビューアー(S)  チェック  s
点字ビューアー(B)  b
アドオン ストア(A)...  a
Pythonコンソール(P)  p
ポータブル版の作成(C)...  c
COM 登録修復ツール...
プラグインの再読み込み  プ
日本語点字ビューアー  日

日本語表記のメニュー項目で、アクセスキー（アクセラレーターキー）が設定されていない
項目の場合、読み上げの語尾がメニュー項目の先頭１文字目を抽出した処理になっているようで、
意味のある読み上げになっていない。

上記の場合、以下の２項目が意味不明な状態となってしまっている。
プラグインの再読み込み  プ
日本語点字ビューアー  日

NVDAメニュー全般において、同様の処理になっていると思われる。

### 期待されること

アクセスキー相当の文字が日本語表記となる場合は、読み上げしないようにすべきなのでは？

### システム構成

NVDA 日本語版 2024.1jp インストール環境
Windows 10 バージョン 22H2 日本語環境

**Comment by nishimotz** [comment]
ご報告ありがとうございます。本家 master で確認すると

COM 登録修復ツール...
プラグインの再読み込み

どちらもアクセラレーターキーが設定されておらず、英語表記の1文字目のRがショートカットになっていました。
ショートカットが重複しているので、Rを押すと1件目に移動し、さらにRを押すと2件目に移動する、という挙動になります。

これに関してはなるべく本家版に揃えることを検討します。

日本語点字ビューアーについては、なにか割り当てを検討します。

**Comment by koichimase** [comment]
NVDAを使った検証中に、メニュー項目の読み上げの際、読み上げ語尾に聞きなれない音が
あったので、スピーチビューアーで確認したところ、アクセスキーの設定が場合の
挙動として先頭の１文字を拾ってきているようだと気づきました。
そのためメニュー項目の読み上げの語尾で「プ」とか「日」とか定義されて、それを単に
アクセスキーを意として読み上げても（アクセスキーの押し下げとして）意味がないのでは？
ということで報告させてもらいました。

**Comment by nishimotz** [comment]
本家版、日本語版、いずれもご指摘の挙動であることは認識しています。
マルチバイト文字がアクセラレーターキーであることも、
Windows の操作としては有効で、
IMEを有効にして実際に「プ」や「日」で選択できると思います。

とはいえ、文字説明を行っているわけでもなく、
カナ漢字変換をしてまでアクセラレータキーを使いたくないでしょう。
キーボード操作を想定すると、
明示的に半角英数字をアクセラレータキーに割り当てるのが妥当と思います。

**Comment by koichimase** [comment]
本件を起票した経緯を少し追記します。
この事象に気づいたのは、NVDAのアドオンを検証している時でした。
具体的には「Place markers」というアドオンを検証して時に、操作メニューが次のようになっていて

![image](https://github.com/nvdajp/nvdajp/assets/46223642/adcd6160-b4b3-4a0f-a9ce-58ea9268b343)

読み上げが「プレイスマーカー   サブメニュー   プ」となり、語尾の「プ」が何なのが気になって
調べていくうちに、このアドオン固有の問題でなく、NVDA本体でのメニュー項目でも発生していると
気づき、起票した次第です。
NVDA本体に関する定義の問題であればアクセスキーを定義すれば回避できると思いますが、
アドオンの場合は、アドオン開発者側でメニュー項目名がマルチバイト文字で、なおかつ
アクセスキーを明示的に定義していないとこの事象が発生するので、何らかの対応ができないかと
いうことで起票しました。
メニュー項目のアクセスキーに関する処理で共通したロジックが入っているのか分からりませんが、、
少なくともマルチバイト文字のメニュー項目でアクセスキーの定義がない場合、アクセスキーの
設定がない方がかえって混乱もなく、スマートなのではないかと個人的に思っています。

仕様というべきなのか、制限事項というべきなのか判断がつきませんが、アクセスキーを意識した
操作で全角文字を入力・指定することはあまり現実的ではないと思ったので、対応の余地があるそう
なのかが分かればと思っています。

**Comment by nishimotz** [comment]
ユーザーガイドの用語にあわせて、下記を作りました。

オブジェクトのショートカットキーの報告で日本語の文字を読み上げる
#454

ひきつづき、改善の検討ということで、上記を使わせてください。

このチケットでは、翻訳に関することをカバーしました。
