### ISSUE TITLE
NVDA+Alt+Tの点字モードの切り替えが機能していない

### ISSUE THREAD

**Issue by KatsutoshiTsuji** [nvdajp/nvdajp#460]
### 問題の再現手順

1. NVDA2024．2JPを起動する
2. NVDA+ALT+Tを押す

### 実際に起きること

なにも起こらない

### 期待されること

点字モードが切り替わる

### システム構成

NonVisual Desktop Access (NVDA) Version: 2024.2jp-beta-240627r (2024.2.0.3619)

Windows 11 Pro バージョン 23H2 (OS ビルド 22631.3810)

#### PC を再起動してもこの問題は再発しますか？

はい

#### 他のバージョンの NVDA と比較している場合はその結果

NVDA 2024.2 本家版ではこの機能は使用できる

#### アドオンを無効化するとこの問題は解決しますか？

いいえ

#### NVDAメニュー / ツール / COM登録の修復ツールを使うとこの問題は解決しますか？
いいえ

**Comment by nishimotz** [comment]
こちらでは点字ビューアーに関しては動作している（現象を再現できない）ので、以下を知りたいです。

* 使用している点字ディスプレイ
* NVDAの入力ヘルプで NVDA+Alt+T を押したときに機能が説明されるか
* NVDAの設定ダイアログの「点字」カテゴリから点字モードを切り替えることができているか

**Comment by KatsutoshiTsuji** [comment]
この件、手元のHPのコンピューターに固有の現象であることを確認しました。
状況として、Insertキー+Alt+Tであれば点字モードを変更できますが、無変換キー+Alt+Tでは動作しないというものでした。
本家版2024．2では機能が動作したのは、インサートキー+Alt+Tで動作を確認していたのが原因でした。
手元の別のPC(Lenovo)では無変換キー+Alt+Tで正常に機能が動作することを確認しました。
本件はPCに固有の問題なので、ここでクローズします。
