### ISSUE TITLE
NVDA+Chrome使用時にアプリケーションキーを押したコンテキストメニューが利用できない

### ISSUE THREAD

**Issue by mitsugusakamoto** [nvdajp/nvdajp#477]
### 問題の再現手順

1. Chrome を開く
2. www.nvda.jp を開く
3. 「NVDA日本語版をダウンロード」というリンクでアプリケーションキーを押す。
4. この選択されているリンクに対してのコンテキストメニューが出ない。

### 実際に起きること
このリンクを操作するためのコンテキストメニューが出ない

### 期待されること
このリンクを操作するためのコンテキストメニューが出て、メニューが表示される。

### システム構成

* Microsoft Windowsバージョン 22H2 (OS ビルド 19045.4291)
* NonVisual Desktop Access (NVDA)Version: jpalpha_240909p (2024.4.0.3696)
* Chromeバージョン: 128.0.6613.121（Official Build） （64 ビット）

#### PC を再起動してもこの問題は再発しますか？
再現します。

**Comment by nishimotz** [comment]
フォーカスモードでアプリケーションキーを押して、上下の矢印キーを押すと、コンテクストメニューのメニュー項目に移動できると思うのですが、いかがでしょうか。

少なくとも最近のバージョンのNVDA日本語版（どうやら本家版でも）で以下は把握できました。

* フォーカスモードでアプリケーションキーを押した直後には、コンテクストメニューそのものや、その中の項目にはフォーカスは移動しない
* ブラウズモードでアプリケーションキーを押すと、コンテクストメニューは開くが、コンテクストメニューの項目にフォーカスが移動しない

これらの挙動がリグレッション（過去のバージョンからどこかで挙動が変わった）かどうかは、まだ判断できていません。

**Comment by mitsugusakamoto** [comment]
はい、フォーカスモードにすればメニューは出せるのでこちらでもさほど問題ないことはわかりました。英語版でも確認しました。いつから変わっちゃったんだろう？

**Comment by KatsutoshiTsuji** [comment]
@mitsugusakamoto ご報告ありがとうございます。
ブラウズモードでリンクにフォーカスがある状態でコンテキストメニューが出せない件、手元でも昨日再現できました。
ただ先程、Windowsアップデートが動いてシステムが更新されたタイミングで、 [NVDA日本語版をダウンロード](https://i.nvda.jp/) にフォーカスした状態でコンテキストメニューが出るようになったような気がしています。
よろしければWindowsの更新後に再度試してみていただけますか?
僕が試した手元のChromeは
バージョン: 128.0.6613.138（Official Build） （64 ビット）
です。

**Comment by mitsugusakamoto** [comment]
私も基本的には治ったようなきがしています。

どうやら本家でも報告はされていそうです。
https://github.com/nvaccess/nvda/issues/17155
