### ISSUE TITLE
2024.4JPでのNVDA+ピリオドの挙動について

### ISSUE THREAD

**Issue by riku22** [nvdajp/nvdajp#480]
### 問題の再現手順

1. わかりやすいように日本語設定で仮名文字のフォネティック読みとアルファベットのフォネティック読みをオンにする。
2. メモ帳などで適当な文字を入力する。
今回は例として「テスト」と入力したものとする。
3. 入力した文字（今回であれば「テ」など）に移動してNVDA+ピリオドを2回または3回押す。
※キーボード配列がデスクトップの場合は、NVDA+テンキー2を押す。

### 実際に起きること

キーを2回押した場合、アルファベットやかな文字をフォネティック読みするはずがフォネティック読みされない。
キーを3回押した場合、文字コードの報告がされるが、16進数の報告がスペル読みになっている。

### 期待されること

キーを2回押した場合、アルファベットやかな文字をフォネティック読みする。
キーを3回押した場合の文字コード報告において、16進数を `ユー プラス ゼロエックスサンゼロシーロク` のように読み上げる。

### システム構成

- NVDA 2024.4jp-beta-241008l インストール環境
- Windows 11 24H2 (64ビット

#### PC を再起動してもこの問題は再発しますか？

はい

#### 他のバージョンの NVDA と比較している場合はその結果

2024.3.1JPまでは期待した挙動になることを確認しています。

#### アドオンを無効化するとこの問題は解決しますか？

いいえ

#### NVDAメニュー / ツール / COM登録の修復ツールを使うとこの問題は解決しますか？

いいえ

**Comment by nishimotz** [comment]
script_review_currentCharcter のマージを失敗しているようです。
ご指摘ありがとうございます。

**Comment by nishimotz** [comment]
nvda_2024.4jp-beta-241009t に更新しました。

**Comment by riku22** [comment]
nvda_2024.4jp-beta-241009t での修正を確認しました。
ありがとうございました。
