### ISSUE TITLE
開発者会向けマニュアル

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#60]
## ビルド環境準備とソースコード取得

NVDA 2017.4jp-beta の場合

### (1) Windows 10 64ビット

確実にビルドできる作業環境は Windows 10 64ビット (1703 / 1709)

### (2) Visual Studio 2017 Community

以下からダウンロードしてインストーラーを実行

https://www.visualstudio.com/ja/downloads/ 

2017年10月にリリースされた Visual Studio 2017 バージョン 15.4.0 を推奨。

#### (2.1) 選択する「ワークロード」の項目

(a) C++によるデスクトップ開発
(b) ユニバーサル Windows プラットフォーム開発

#### (2.2) 「概要」「C++によるデスクトップ開発」「オプション」で選択する項目

(a) VC++ 2017 v141 ツールセット（x86, x64）
(b) Windows 10 SDK (10.0.16299.0) for Desktop C++ x86 and x64

### (3) Git for Windows

Git for Windows サイトから Git-2.14.3-64-bit.exe をダウンロードする。

https://git-for-windows.github.io/

インストーラーを実行する。

Git の初心者は下記の設定を推奨。

* Adjusting your PATH environment : Use Git and optional Unix tools from the Windows Command Prompt

* Configuring the line ending conversions : Checkout as-is, commit as-is

その他はデフォルトで。

環境変数 PATH を自分で設定しなおす場合は、以下が登録されていること。

```
C:\Program Files\Git\cmd
C:\Program Files\Git\usr\bin
```

備考：
リモートリポジトリへのアップロード (git push) するためには
push 先（GitHubなど）のアカウントのセットアップや公開鍵の設定、権限の取得が必要。

### (4) 7-Zip (7z)

7-Zip サイトから 16.04 for Windows (7z1604-x64.exe) をダウンロードする。

http://www.7-zip.org/download.html

インストーラーを実行してデフォルトでインストールする。

環境変数 PATH に以下を登録する。

```
C:\Program Files\7-Zip
```

### (5) Python 3.6.3 / 2.7.14 (Windows 32bit)

それぞれダウンロードして両方実行し、インストールする。
オプションはデフォルトでよい。

https://www.python.org/downloads/release/python-363/

Windows x86 executable installer (python-3.6.3.exe)

https://www.python.org/downloads/release/python-2714/

Windows x86 MSI installer (python-2.7.14.msi)

### (6) 確認すること

コマンドプロンプトで

```
> py -2
```

を実行すると Python 2.7 が起動する。

コマンドプロンプトで git, patch, 7z がそれぞれ実行できる。

### (7) nvdajp 本体とサブモジュールの取得

```
> git clone --recursive https://github.com/nvdajp/nvdajp.git
> cd nvdajp
```

これだけで通常は問題なくサブモジュールも取得される。

本ドキュメントの完全版は
https://github.com/nvdajp/nvdajp/blob/jpbeta/jptools/readme.md

**Comment by ma10** [comment]
> コマンドプロンプトで git, patch, 7z がそれぞれ実行できる。

とありますが、patchはどのパッケージによってインストールされるはずでしょうか?

**Comment by nishimotz** [comment]
Git と一緒に入れた Unix tools にパスが通ってることの確認です。

**Comment by nishimotz** [comment]
補足です。
私が Windows でいつも使っている which.bat というバッチファイル

```
@echo off
for %%I in (%1 %1.com %1.exe %1.bat %1.cmd %1.vbs %1.js %1.wsf) do if exist %%~$path:I echo %%~$path:I
```

このバッチファイルに最優先で PATH を通してあるとすると、下記のようになります。

```
> which git
C:\Program Files\Git\cmd\git.exe

> which patch
C:\Program Files\Git\usr\bin\patch.exe

> which 7z
C:\Program Files\7-Zip\7z.exe
```

ちなみに Visual Studio 2017 インストーラーには Git for Windows を入れるオプションがなかったので、追加で Git を入れるように書いたのですが、実はインストールされてしまっていることにいま気づきました。

```
> "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\cmd\git" --version
git version 2.12.2.windows.3

> "C:\Program Files\Git\cmd\git.exe" --version
git version 2.14.3.windows.1
```

どちらの Git でも当面は問題ないので、マニュアルはこのままにします。
