### ISSUE TITLE
再○○の点訳

### ISSUE THREAD

**Issue by mitsugusakamoto** [nvdajp/nvdajp#66]
### 期待されること (Expected behavior):
再と放送の間はます開けをしない。
点訳の手引きの「接頭語・接尾語・造語要素と自立語との間は続けて書く」と言うルールではないかと思います。

### 実際に起きること (Actual behavior):
再●放送のように増す開けされる

### システム構成 (System configuration):
NVDA のバージョン (NVDA version):
NonVisual Desktop Access (NVDA)
Version: 2018.1jp-beta-171206x

**Comment by mitsugusakamoto** [comment]
再○○のような点訳でます開けが入る。

例:
再放送
再上陸

**Comment by nishimotz** [comment]
テンプレートの項目に合わせて必要な情報、特に下記を補っていただければ助かります。

* NVDAのバージョン
* 期待されること

特に、読み手は点訳の規則を知らない、という前提で「期待されること」を書いていただけると、いろいろな人が貢献しやすくなると思うので、よろしくお願いします。

**Comment by nishimotz** [comment]
「再起動」は今までマスアケしてきましたが、これもあけないのが正しいでしょうか？

**Comment by mitsugusakamoto** [comment]
おそらく開けません。

**Comment by nishimotz** [comment]
ありがとうございます。
実際の作業は nvdajpmiscdep で行ったので、チケットを立て直しました。

https://github.com/nvdajp/nvdajpmiscdep/issues/62

こちらは重複としてクローズします。
