### ISSUE TITLE
アドオン紹介ウェブサイトの翻訳

### ISSUE THREAD

**Issue by minakononogaki** [nvdajp/nvdajp#69]
2018年1月7日時点で安定版49、開発版のみ15、合計64のアドオンの紹介ページがあります。
翻訳が部分的にされた状態なので、順次進めます。

**Comment by minakononogaki** [comment]
2018/1/4に作業
IndentNav
2018/1/7に作業
Switchsynth
Objpad
Vitalsource Bookshelf
Speak password
Speech History

**Comment by minakononogaki** [comment]
2018/1/8に作業
Review cursor copier
Crash hero
Tip of the day
Visual Studio
Team Viewer (残りのみ)
Mozilla apps enhancements
Braille Extender
Say current keyboard language

**Comment by minakononogaki** [comment]
2018/1/8
Classic Selection

**Comment by minakononogaki** [comment]
2018/1/9
Report Symbols

**Comment by minakononogaki** [comment]
2018/1/10
Virtual Review

**Comment by nishimotz** [comment]
たぶん終わりのない仕事だと思うのでクローズしますが、
今後も完了報告があれば、こちらにコメントしてください。
