### ISSUE TITLE
OutlookやWordで文字の背景色が報告されない

### ISSUE THREAD

**Issue by minakononogaki** [nvdajp/nvdajp#76]
### 問題の再現手順:

1. Outlookで新規メールを書く。背景色を変更する(入力時は色が読まれる。確定後は色が報告されなくなる)。
2. 背景色を変更した位置でNVDA+F 書式情報の報告 をしても、書式なしになる
3. Wordでも同様のことが起こる

### 期待されること:

確定後も色が報告されること。また、NVDA+Fで色が正しく報告されること。

### 実際に起きること:
書式なしと読まれる。

### システム構成:
NVDA のバージョン:
nvda2018.1.1jp

インストール環境とポータブル版の種別:
インストール

その他の情報:
HP EliteBook 820 G3

Windows のバージョン:
Windows7

再現に必要なその他のアプリの名前やバージョン:
Outlook 2013
Word 2013

### その他の質問:

PC を再起動してもこの問題は再発しますか？
はい。

その他のバージョンの NVDA で状況を比較しましたか？
nvda2018.1.1(本家版) 書式なしと報告されるそうです。

### 参考情報
当面の解決方法
Outlook, Wordともに、html形式で保存すると書式がフォント色、背景色共に正確に読まれるため、その形式で保存して確認する。

**Comment by nishimotz** [comment]
テンプレートが配慮不足だったので改善したいのですが、
もとから書かれていた入力例を削除していただけませんか？

**Comment by minakononogaki** [comment]
野々垣です。

すみません、どこに何を書いたかわからなくならないように、消してはいけないかなと思っていました。後から修正って出来るんでしたっけ。

野々垣美名子

2018/04/02 15:32、Takuya Nishimoto <notifications@github.com>のメール:

**Comment by nishimotz** [comment]
github.com でログインして Issue を表示すると鉛筆のボタン Edit comment で編集できます。

**Comment by nishimotz** [comment]
いま Word 2013 でこの件を確認しようとして気づいたのですが、
Word で「文字の背景色」という機能がよく分からないので、
具体的に操作手順を説明していただけますか？

「蛍光ペンの色」と「文字の網掛け」は見つかるのですが、
背景色というのはこのいずれかのことでしょうか？

**Comment by nishimotz** [comment]
個人的にいただいた情報を踏まえて再度確認したのですが
リボンの段落「塗りつぶし」（Alt+H H）で文字の背景の色を変えることができ、
同じ情報が「線種とページ罫線と網かけの設定」ダイアログ
(Alt+H B O)
では「網掛け」タブの「背景の色」として反映されるようです。

調べたい文字を選択して「背景の色」にフォーカスを移動すれば
「塗りつぶしの色 (濃い赤)  ボタン」
のように確認できます。

現状 NVDA+F で Word の「フォントの色」は確認できますが、
この「背景色」は確認できていないようです。

以上、とりあえず把握した現状でした。

![image](https://user-images.githubusercontent.com/76300/39396748-1b2af45c-4b2f-11e8-934e-a4c514dc839b.png)

**Comment by nishimotz** [comment]
本家チケット
Report background and highlighting colors in Microsoft Word
https://github.com/nvaccess/nvda/issues/5866

**Comment by msuzu15** [comment]
こちらもともと私から問い合わせした問題と思いますが、
（以下、こちらで使用しているのがWord 2007の英語版なのでWord 2007 英語版での操作になります）

添付Wordファイル（「これはテストです.doc」）で、Word文書内の「これはテストです」という文の「テスト」の背景色を濃い赤系の色にしているのですが、
（背景色はリボンのHomeタブを選択してからTabキーを押していって"Text Highlight Color"と読み上げられたところでスペースキーを押して色を選択しました。上記でいうところの「蛍光ペンの色」にあたるかと思います）
その背景色をつけた「テスト」の部分を選択してから、

・Alt - H - B - Oと押すと、Borders and Shading dialogという画面が出てくるのですが、Shadingタブを選択するとFill ColorはNo Colorとなっています。
・Alt - H - Iと押すと"Text Highlight Color Yellow"と読み上げされ、これは選択されているテキストの背景色を報告しているというよりは背景色をつけるときのデフォルトの色を示しているようです。

ということで、現状の背景色の確認ができません。

また、上記で「HTML形式で保存すれば背景色を確認できる」とありますが、
上記WordファイルをHTML形式で保存してみましたが（添付「これはテストです.htm」）、やはり背景色の確認はできませんでした。

以上から、現状では、NVDAでは背景色を確認することはできないということでしょうか？

背景色のつけ方にはいろいろあるようですが、
今回この問い合わせをしたのは、お客様からのメールで「黄色くマークしたところを確認してください」のように書いてあったのがどの部分が黄色くマークされているのかNVDAで確認できなかったからで、
黄色いマークが「蛍光ペン」でつけたのか「網かけ」や「塗りつぶし」でつけたのか、メールを書いた

[180511.zip](https://github.com/nvdajp/nvdajp/files/1992759/180511.zip)

のは私でなく先方ですのでどのやり方でつけたのかわかりませんので、
どのやり方でつけた背景色でもNVDAで確認できないと困ります。

**Comment by nishimotz** [comment]
NVDA 本家の issue が優先度3になっているので、
すぐには対応されそうにないのですが、
本家に PR を出せばマージしてもらえそうです。

作業する時間がとれたら調べてみようと思っています。
報告すべき属性について Microsoft のドキュメントで定数などの定義を調べて、
英語版 Windows と英語版 Word でちゃんと動くようにパッチを作り、
メッセージを翻訳可能にしておいて日本語の用語を当てはめる、
という感じの作業です。
（Excel 罫線のときにこういう作業をしました）

今回、英語版の Word での操作を書いていただけたので、助かります。
ただ、私は新しい Word でしか英語環境を確認できないので、
まず Word 2013 か 2016 を対象に作業を行うつもりです。

あるいは、本家で進捗があったら、こちらでお知らせします。

**Comment by nishimotz** [comment]
本家 2023.2 で改善されました。

**Comment by msuzu15** [comment]
WordとOutlookで確認できました。ありがとうございました。
