### ISSUE TITLE
レビューカーソルの文字説明におけるフォネティック読み

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#78]
### 問題の再現手順:

* NVDAの設定：ラップトップ配列、「かな文字をフォネティック」チェックあり
* メモ帳で「日本語キーボード」と入力
* Home キーでキャレットを左端に戻す
* NVDA+右矢印で「キ」に移動
* NVDA+ピリオドを2回押す

### 期待されること:

* カタカナ キッテノキ

### 実際に起きること:

音声エンジンが SAPI 5 （Microsoft Haruka）および Nuance Vocalizer の場合
「キ」（1回または2回繰り返し）
となる。
音声エンジンが DTalker のときにもフォネティック読みされないという報告がある。

音声エンジンが JTalk および KC トーカーの場合はフォネティック読みされている

### システム構成:

NVDA 2018.1.1jp
インストール環境
Windows 10 バージョン 1709
（追記 64ビット）

### その他の質問:

その他のバージョンの NVDA：調査中

追記：音声設定「速さ」が遅いときに発生する（ように聞こえる）。詳しくは後述のコメント。

**Comment by ma10** [comment]
手元の環境 (NVDA 2018.1.1jp, Windows 10 Pro 1803) では、JTalkでも同様の状況が再現しました。

**Comment by nishimotz** [comment]
こちらでは以下で「カタカナ キッテノキ」の読み上げを確認しました。

* NVDA 2018.1.1jp インストール環境
* Windows 10 バージョン 1803 Insider ビルド 17127
* OneCore 音声 Microsoft Ichiro

NVDA+ピリオド（ラップトップ配列）を4回押して「読みかたモード」にすると、
違う読み方になりますが、NVDA を再起動するたびに「説明モード」に戻ります。
（読みかたモードの設定を保存するという課題をまだ実装していない）

**Comment by riku22** [comment]
こちらは、下記の環境ですが、NVDA+ピリオドを2度押しても、「キ」と読まれるだけです。  

- NVDA2018.2jp-beta-180328o インストール環境
- Windows10 Ver1803 64ビット ビルド17127.1
- 音声エンジン：KCトーカー

　何か参考になれば幸いです。

**Comment by nishimotz** [comment]
ありがとうございます。
いただいたご報告と同じ状況を再現できていないのですが、
私が報告したことを一つ訂正します。

* NVDA+ピリオド4回で「読み方モード」「説明モード」を切り替えるとき、どちらでもNVDA+ピリオド2回は「カタカナ キッテノキ」と読み上げる
* 確認した環境 NVDA 2018.1.1jp + Windows 10 バージョン 1709 + （たとえば）KCトーカー

**Comment by nishimotz** [comment]
こちらで確実に再現できるのが SAPI5 Haruka なので、NVDA のバージョン間の比較をしました。

再現手順と期待される読み上げは最初に書いたとおりです。

* 2017.4jp : キ
* 2018.1jp : キ
* 2018.1.1jp : キ

これだけを見ると「リグレッションではない」（つまり 2018.1.1jp のリリースをやり直すのではなく 2018.2jp 以降に向けた課題とする）という判断になりそうです。

ですが私の環境でも他の不具合と切り分けができていない問題があるので、もうすこし情報収集させてください。

**Comment by nishimotz** [comment]
どうやら音声の「速さ」の設定が再現手順に必要らしいです。

いま Windows 10 バージョン 1803 (17133.1) の SAPI5 Haruka で確認したら、
速さ100の場合は「カタカナ キッテノキ」らしい声が聞こえましたが、
速さ50の場合は「キ、キ」と聞こえました。

他の条件でも音声の速さが影響している可能性があります。

**Comment by nishimotz** [comment]
本家版 master で SAPI5 のいわゆる「音切れ」処理が改良されたようです。

すばやく2回押す操作では、1回押しの処理をまず出力し、
2回目が押されたら直前の音声出力をキャンセルして、
2回押しの処理を出力しなおす、という実装になっているので、
音切れのレスポンスが本件に影響を与えている可能性は高いです。

いま日本語ベータ版 180501n で確かめたところ、
速さを50くらいにしても SAPI5 Haruka で「カタカナ キッテノキ」と聞こえました。
Vocalizer では改善されていないようです。

**Comment by nishimotz** [comment]
SAPI5 Haruka については 2018.2jp で解決したと思いますが、いかがでしょうか。

**Comment by TetsuroOkane** [comment]
NVDAバージョン2019.3jp-beta-191216pでまたフォネティック読みが出来ない状態が再発している様子です。
こちらの環境はLenovo ThinkPad E440とMOUSE MB-F556-BN-S2の2台で発生し、Windows10のバージョンは共に1909です。
アドオンは無効化した状態で試しています。
音声エンジンはOneCoreのHarukaでもSAPI5のHarukaでも発生します。
JTalkでは、NVDA+ピリオド2回でのフォネティック読みが出来ない状態に加え、NVDA+Shift+ピリオドを2回以上押すと、スペル読みもせず1文字目のみ読み止まります。

**Comment by nishimotz** [comment]
遅くなりましたが、日本語アルファ版で「フォネティック読みができない」がどこから起きているか調べています。

* jpalpha 191106q では起きていない
  * alphajp-1159
  * https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/28650039
* jpalpha 191115q では起きている
  * alphajp-1160
  * https://ci.appveyor.com/project/TakuyaNishimoto/nvdajp/builds/28878932

**Comment by nishimotz** [comment]
191115q は下記の巨大リファクタリングを本家からマージした直後のはず。
このマージ作業が怪しい

https://github.com/nvdajp/nvdajp/commit/2e892bb6fbaff299c8c8c44d3fa5cbc51781952b

本家からのマージ、その前は下記だったが、このときのビルドが 191106q のはず

https://github.com/nvdajp/nvdajp/commit/e9f32c6fafb3842594aff6a707ff02479fda2577

**Comment by nishimotz** [comment]
作業メモ

* 問題が起きる前の状態に戻した作業ブランチを作る
* もう一度本家 master をマージして衝突を直す
* さらに alphajp をマージしなおす

上記を GitKraken でやり直して、正しく動くようになった。

**Comment by nishimotz** [comment]
2019.3jp-beta-191226p で修正しました。
日本語アルファ版もこれから修正版を出します。

最初に報告した現象と原因が違うと思うので、
クローズするのではなく、マイルストーン解除にしておきます。

**Comment by nishimotz** [comment]
日本語アルファ版を jpalpha_191226q に更新しました。

**Comment by nishimotz** [comment]
最初に報告した現象について SAPI5 Haruka で速さをかなり遅くしてみるなど、
確認しましたが、再現できないので、やはりクローズしておきます。
