### ISSUE TITLE
KCトーカー利用時にNVDAの更新を「更新を後で行う」にしたときの挙動

### ISSUE THREAD

**Issue by riku22** [nvdajp/nvdajp#80]
最近のベータ版から導入された「更新を後で行う」をKCトーカー利用中に実行すると、その後の操作が一切音声化されなくなります。

### 問題の再現手順

1. 音声エンジンを「KCトーカー」に切り替え。
1. NVDAのヘルプメニュー等から、更新をダウンロードし、ダウンロード完了後の画面で、「更新をあとで行う」を選択する。

### 期待されること

　通常通り音声読み上げが行われる。

### 実際に起きること

　Alt+Tab等でアプリを切り替えたり、Windows+Dでデスクトップを表示させたりなど、何を行っても、音声読み上げが行われず、NVDAを再起動するしかない状況になる。

### システム構成

- NVDA 日本語版 2018.1.1jp-beta-180420o インストール環境
- Windows10 Ver1803(64ビット) ビルド17133.1

### 補足事項

　この現象は、JTalkなどの他の音声エンジンでは発生しないことを確認しています。

**Comment by nishimotz** [comment]
こちらでは現象を再現できていません。

確認手順

* NVDA をアンインストール
* 180419r をインストール
* KCトーカーを有効化
* 更新を確認（180420o が入手可能）、更新をダウンロード
* 更新をあとで行う、を選択

状況

* Windows+D や Windows+T などのデスクトップ読み上げ、Alt+Tab などは正常

環境

* Windows 10 Ver 1709 (16299.371) 64bit
* KCトーカー 1.0.4

もしログにエラーなどが出ていたらご報告ください。
あるいは Windows 10 ビルド 17134 で確認が可能であればまたお知らせください。
こちらでもひきつづき調べてみます。

**Comment by riku22** [comment]
すみません。  
　先ほどもう1度ちゃんとテストしたら、再現しませんでした。  
　ご迷惑をおかけして申し訳ありませんでした。
