### ISSUE TITLE
Firefox で文字変換確定後左右矢印で入力済み文字の確認が出来ない

### ISSUE THREAD

**Issue by TetsuroOkane** [nvdajp/nvdajp#84]
### 問題の再現手順

1.Firefox (またはFirefox Developer Edition)を開く
2. www.google.com、www.yahoo.co.jpなどを開き文字入力欄に移動する
3. 漢字かな交じりの文字を入力し変換する
4. Enter キーを押し確定後左右矢印で入力済みの文字を確認しようとする

問題の再現に必要なファイルは ZIP 形式のアーカイブで添付

### 期待されること

入力済みの文字や漢字の詳細読みがされる

### 実際に起きること

入力確定後左右矢印を押しても入力済みの文字が読み上げられない。

### システム構成

NVDA 日本語版 2018.2jp-beta-180511i インストール環境

Windows 10 バージョン 1803 日本語環境

Firefox Quantum 60.0及びFirefox Developer Edition 61.0b4

### その他の質問

PC を再起動してもこの問題は再発する
はい

NVDA 日本語版 2018.1jp でも再現する
はい
[Log-2018-05-12-23-42.txt](https://github.com/nvdajp/nvdajp/files/1997693/Log-2018-05-12-23-42.txt)

**Comment by ma10** [comment]
この現象、私の手元でもirefox 58以降出ています。
入力を確定した後、一度そのフィールドから何らかの方法でフォーカスを外してから戻す (例: Tab→Shift+Tab、Alt→Alt、Alt+Tab→Alt+tabなど) と、普通にキャレット移動時に文字の確認ができるようです。
また、フォーカスを外す前にカーソルキーを操作した場合、フォーカスを外して戻ってきた時の様子から、読み上げはされていないくてもキャレットは操作通りに移動していることが推測できます。

**Comment by msuzu15** [comment]
> 1.Firefox (またはFirefox Developer Edition)を開く
> 2. www.google.com、www.yahoo.co.jpなどを開き文字入力欄に移動する
> 3. 漢字かな交じりの文字を入力し変換する
> 4. Enter キーを押し確定後左右矢印で入力済みの文字を確認しようとする

この時点で、フォーカスが入力欄でなくFirefoxのフレームワークに移動しているようです。
（この時点でNVDA+TABキーを押すと「Google - Mozilla Firefox  フレーム  読み取り専用」と読み上げされるため）

Alt+TABキーで他のウインドウをアクティブにしてからFirefoxに戻ると、フォーカスが入力欄に戻っています。
（この時点でNVDA+TABキーを押すと「Google - Mozilla Firefox Google  ドキュメント 検索  コンボボックス  折りたたみ  オートコンプリート  編集可能 テスト」のように読み上げされるため）

ところで、この現象は一度こちらで再現したのですが、もう一度Firefoxを開いたら再現しなくなってしまいました。

**Comment by msuzu15** [comment]
こちらの環境だけかもしれませんが、
Windows 7で、

(1) スタートボタンを押すとスタートメニューの左列に表示される最近起動したプログラムの中に出ている"Firefox"を選択してFirefoxを起動

→　報告されている手順で、問題が再現できました。Alt+TABでいったん他のウィンドウをアクティブにしてからもう一度Alt+TABキーを押してFirefoxに戻ってくると入力欄の内容が左右矢印キーで確認できます。
（Alt+TABでなくTAB～Shift+TABとした場合は入力欄の確認を左右矢印キーで行うことはできませんでした）

(2) スタート→すべてのプログラム→ Mozilla Firefox → Mozilla Firefoxと選択してFirefoxを起動

→　報告されている手順で問題の再現はできませんでした。入力欄で左右矢印キーを使って普通に内容の確認ができます。

ところで、(1)の手順でFirefoxを起動したときと(2)の手順でFirefoxを起動したときとで、Ctrl+Lキーを押してアドレス欄に移動したときの読み上げのされ方が違っていて（(1)の場合は「Enter URL or keyword」と読み上げされるが(2)の場合は「Search Bookmark or history」と読み上げされる）、いちおうどちらも起動したウインドウのタイトルはFirefoxになっているのですが(1)と(2)では別物が起動されている可能性があります。
ご参考までに、スクリーンショットを添付します。
（(1)でGoogleのページを開いた画面：Firefox_1.png、(2)でGoogleのページを開いた画面：Firefox_2.png）
![firefox_1](https://user-images.githubusercontent.com/33409989/40131937-50b6ee14-5976-11e8-9881-306b5cbe02e1.png)
![firefox_2](https://user-images.githubusercontent.com/33409989/40131960-645f4d08-5976-11e8-9119-64f122ae06dd.png)

**Comment by TetsuroOkane** [comment]
拡大鏡とピンチインを組み合わせて最大化した状態でスクリーンショットを拝見いたしました。
2枚目の方は、旧バージョンのFirefoxのように見受けられます。
画像のみでの判断は難しいので、Alt、H、Aと順に入力し、バージョンの確認をしてみてそれぞれのバージョンのご報告を頂けると助かります。

**Comment by msuzu15** [comment]
若干修正します。

(1) スタート→すべてのプログラム→FirefoxからFirefoxを起動
（ショートカット先："C:\Program Files\Mozilla Firefox\firefox.exe")

Alt - H - Aで表示される画面の内容：
Mozilla Firefox について  ダイアログ  60.0.1 (64 ビット)   Firefox をデザインしている Mozilla は、ウェブの公開性、公衆性、制限のないアクセス性を保つために共に活動している グローバルなコミュニティ です。  参加しませんか？ 寄付 または コミュニティへようこそ！ Firefox および Firefox ロゴは 米国 Mozilla Foundation の米国およびその他の国における商標です。

(2) スタート→すべてのプログラム→Mozilla Firefox→Mozilla FirefoxからFirefoxを起動
（ショートカット先："C:\Program Files (x86)\Mozilla Firefox\firefox.exe"）

Alt - H - Aで表示される画面の内容：
About Mozilla Firefox  ダイアログ  version 3.6.2
©1998-2009 Contributors. All rights reserved. ( ). Firefox and the Firefox logos are trademarks of the Mozilla Foundation. All rights reserved. 
OK  ボタン

(1)でFirefoxを起動したときは報告されている問題が再現し、(2)でFirefoxを起動した場合は問題は再現しません。

その他：
・問題が発生したときの回避策として、Alt+TABでアプリケーションを切り替える手順だけでなく、Tabキーで次のタブ順のコントロールに移動してからShift+Tabキーで入力欄に戻る手順でも問題を回避できました。
・入力欄で「あいうえお」と入力してEnterで確定、読み上げがされなくても左矢印キーを3回押して「情報」と漢字変換して入力してEnterで確定してからAlt+TabやTab～Shift+Tabでいったんフォーカスを移して入力欄に戻って入力欄の内容を確認すると「あい情報うえお」と入っているので、問題が発生した状態でも画面の見た目での動作は普段と同じ通常動作で（カーソル移動や文字入力など）、ただ読み上げだけがおかしくなっているようです。

**Comment by nishimotz** [comment]
本家で中国語の文字入力に関するチケット
https://github.com/nvaccess/nvda/issues/8321

**Comment by nishimotz** [comment]
ちゃんと追跡できていなかったのですが、
Firefox 61.0.2 （64ビット）と NVDA 2018.3jp-beta-180824k で
www.google.com をアクセスして、Microsoft IME の日本語入力を確定した直後の
キャレット移動で適切に読み上げできていることを確認しました。

クローズしたいと思うので、もし不具合が解決していなかったら教えてください。
