### ISSUE TITLE
日本語版ドキュメントの誤字

### ISSUE THREAD

**Issue by riku22** [nvdajp/nvdajp#86]
日本語版のドキュメントで、いくつか誤字を見つけたので、報告しておきます。

### NVDA最新情報
　2018.2の見出しのすぐ下の行内「HumanWare」が「Humanwear」になっています。

### NVDA日本語版の説明
　「7. 点字ディスプレイ」のセクション内の「7.1. 記号の出力」において、「出力」と「点字シンボル」が異なっている箇所があります。
　☆ 以下、
　記号：出力内容（原文）  出力内容（修正例）
の順に記載します。テーブルの書き方がわからなかったので。
\
　] 半角大括弧閉じ：2356-5  2356-2
　］ 全角大括弧閉じ：2356-5  2356-2
　” 全角コーテーション閉じ：2356-5  2356-2
　} 半角中括弧閉じ：2356-5  2356-2
　’ 全角シングル閉じ：2356-5  2356-2
　〕 亀甲閉じ：2356-5  2356-2
　｝全角中括弧閉じ：2356-5  2356-2
　〉 山括弧閉じ：2356-5  2356-2
　》 二重山括弧閉じ：2356-5  2356-2
　】 黒括弧閉じ：2356-5  2356-2
　〟 ヒゲ閉じ：2356-5  2356-2
　』 二重カギ閉じ：36-56  36-23
\
　それから、小なりと大なりが実際に点字ディスプレイに出力される点字シンボルと逆になっています。

**Comment by nishimotz** [comment]
最新情報ですが、
原文のスペルミスをそのまま書いていました。
#75 とあわせて修正をコミットしたので、本家版と日本語版のどちらも修正される見込みです。
日本語版の説明はこれから確認します。
