### ISSUE TITLE
JTalk 音声の振幅正規化の再検討

### ISSUE THREAD

**Issue by nishimotz** [nvdajp/nvdajp#87]
Twitter で指摘していただいた件。

JTalk tohoku-f01 で
「スクリーンリーダーNVDA日本語版のニュース」
「スクリーンリーダーNVDA日本語版ニュース」
前者のほうが音が小さく聞こえる気がする。

ちゃんと波形を見ていないが、例えば「の」が振幅が大きいわりに音圧が小さい、
といった場合にこういうことが起きる可能性はある。

音声はスペースで区切った文字列ごとに生成して、
生成された区間ごとに振幅正規化をしている。

最初に実装したころには m001 (lite) だけを前提にしていたので、
ワークアラウンドをしないほうがよい可能性はある。

再検討をするとしたら下記：

https://github.com/nvdajp/python-jtalk/blob/c6d7b22ba10c631f2b6904ae94dbcb8b6fc6304a/lib/libopenjtalk.c#L166

**Comment by mitsugusakamoto** [comment]
「の」よりもわかりやすそうなのが、
「NVDA日本語」「NVDA」
とすると、最後の「NVDA」の方が大きく聞こえます。

**Comment by nishimotz** [comment]
libopenjtalk.c で speech_normalize をやめてみました。
特に違和感はないので 2018.3jp ベータ版と、次のアルファ版に反映させてみます。

**Comment by nishimotz** [comment]
単純に speech_normalize をやめると JTalk の「音量」の変更ができなくなるので再検討します。
