### ISSUE TITLE
NVDA Remote AttributeError: 'MenuItem' object has no attribute 'SetCheckable'

### ISSUE THREAD

**Issue by msuzu15** [nvdajp/nvdajp#99]
### 問題の再現手順

1. http://www.nvdaremote.comよりNVDA Remote 2.1をダウンロrード。
2. NVDAメニューのツール→アドオンマネージャを使って、NVDA Remote 2.1をインストール。
3. NVDAを再起動。
4. NVDAメニューからツールまで選ぶと、NVDA Remoteがインストールされていればリモートというサブメニューが表示されるのだが、リモートというサブメニューが表示されない。
5. NVDAメニューのツール→ログビューアでログを確認すると、以下のエラーが記録されている。

ERROR - globalPluginHandler.initialize (14:45:44.137):
Error initializing global plugin <class 'globalPlugins.remoteClient.GlobalPlugin'>
Traceback (most recent call last):
  File "globalPluginHandler.pyo", line 32, in initialize
  File "C:\Users\msuzuki\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 56, in __init__
  File "C:\Users\msuzuki\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 104, in create_menu
AttributeError: 'MenuItem' object has no attribute 'SetCheckable'

6. ログに記録されているC:\Users\msuzuki\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.pyの104行目は以下のようになっている。

		self.mute_item.SetCheckable(True)

この部分は、NVDAメニューのツール→リモート→相手の音声をミュートのメニューをチェック可能メニューに設定している部分と思われるが（つまり相手の音声をミュートする状態のときは「相手の音声をミュート」の横にチェックマークを表示しそうでないときは非表示にする）、どこかのベータ版でSetCheckableという属性がサポートされなくなったためにエラーが発生するようになったと思われる。

### 期待されること

手順4.において、ツールの下にリモートというサブメニューが表示される。
手順5.で発生しているようなエラーが発生しない。

### 実際に起きること

手順4.にあるような現象が発生し、手順5.にあるようなエラーが発生している。

### システム構成

NVDA 日本語版 2018.3jp-beta-180806n インストール環境

Windows 7 SP1 英語版

### その他の質問

PC を再起動してもこの問題は再発する
→　発生します。
NVDA 日本語版 2018.1jp でも再現する
→　この現象はNVDA 2018.3jp-beta-180803以降で発生しているようです。

再現手順にあるグローバルプラグインのファイルはインストールされたそのままのもので、何も編集していません。
NVDA RemoteはいままでのNVDA日本語版で動いていたものが途中のベータ版から動かなくなっていて、NVDA Remoteの変更により発生した問題ではないので、NVDA Remoteのほうにではなくまずこちらにご報告させていただきます。

**Comment by riku22** [comment]
ご指定のエラーは、NVDA2018.3よりGUI部品を扱うモジュールであるWXPythonがVer.3からVer.4に変更されたことに伴うものです。  
　手元のファイルではソースコードを編集して、動作するようにしてあるんですが、公開してもよいものやら？

**Comment by msuzu15** [comment]
ご参考までに、どのソースファイルをどのように書き換えればエラーを回避できるのか教えていただけますか。

**Comment by msuzu15** [comment]
WXPythonのVer.3からVer.4への変更というのが本家版のNVDA 2018.3での変更ということでしたら、
この問題はNVDA RemoteのほうのIssueに登録します。
（見たところこの問題はNVDA Remoteのほうにはまだ報告されていないようで、まだ皆さんNVDA 2018.2を使ってるということかもしれないです）

**Comment by riku22** [comment]
一応関連チケットが下記に立っています。  
[Support for WX Python Phoenix by leonardder · Pull Request #170 · NVDARemote/NVDARemote](https://github.com/NVDARemote/NVDARemote/pull/170/files/09c8abaf38b0bf48c9331f8c5f5c6b3a979ba2e4)
　ソースコードですが、「\<NVDAアドオンフォルダ\>\\remote\\globalPlugins\\remoteClient\\__init__.py」を開きます。  
　そして、102行目から105行目までを削除して、下記のソースに置き換えます。  

			# Translators: Menu item in NvDA Remote submenu to mute speech and sounds from the remote computer.
			if int(wx.version()[0]) <= 3:
				self.mute_item = self.menu.Append(wx.ID_ANY, _("Mute remote"), _("Mute speech and sounds from the remote computer"))
				self.mute_item.SetCheckable(True)
			else:
				self.mute_item = self.menu.Append(wx.ID_ANY, _("Mute remote"), _("Mute speech and sounds from the remote computer"), kind=wx.ITEM_CHECK)
			self.mute_item.Enable(False)
			gui.mainFrame.sysTrayIcon.Bind(wx.EVT_MENU, self.on_mute_item, self.mute_item)

　変更が終わったら、上書き保存して、NVDAを再起動してください。

**Comment by riku22** [comment]
失礼しました。  

> 「<NVDAアドオンフォルダ>\remote\globalPlugins\remoteClient\init.py」

ではなく、

「\<NVDAアドオンフォルダ\>\\remote\\globalPlugins\\remoteClient\\\_\_init\_\_.py」

でした。

**Comment by msuzu15** [comment]
NVDA RemoteのIssueに登録しました。

https://github.com/NVDARemote/NVDARemote/issues/176

教えていただいたコードは、こちらで試してみてうまくいったら、上記Issueに追加してみます。
（ver.3とver.4で処理を分岐させているようですが、NVDA 2018.3では必ずver.4が使用されるのであればver.4のコードだけ残せばいいのかなとも思いましたが）

**Comment by msuzu15** [comment]
教えていただいたコードをNVDA 2018.2と2018.3で試して、うまくいくことを確認しました。
（「ツール」メニュー以下に「リモート」メニューが表示され、また「相手の音声をミュート」メニューも動作する）
NVDA RemoteのIssueにも追記しました。

https://github.com/NVDARemote/NVDARemote/issues/176

（NVDA RemoteはNVDA 2018.2以前のバージョンとも使われる可能性があるため、WXPython ver.3用のコードも残しました）

これで少し様子を見てみます。

ありがとうございました。

**Comment by nishimotz** [comment]
本家のMLでも非公式の修正版が紹介されているので、情報共有しておきます。

NvDA Remote Support add-on: emergency hotfix for wxPython 4 users posted

https://nvda-addons.groups.io/g/nvda-addons/message/3286

**Comment by nishimotz** [comment]
NVDA 2018.3 と互換性のある NVDA Remote 2.2 がリリースされました。

https://nvdaremote.com/download/
